### PR TITLE
storagenode/pieces: Remove duplicated orders test

### PR DESCRIPTION
**Pull request by ifraixedes**
What: Remove a Storage Node DB test case which belongs to orders rather than pieces.

Why: Because it doesn't belong to pieces and the test already exists in the `storagenode/orders` package.

Please describe the tests: N/A
Please describe the performance impact: N/A

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by egonelbre** [comment]
I suspect this might have needed to be some other test and it was a copy-paste error.

**Comment by ifraixedes** [comment]
I'm fine opening a ticket for it if you want that somebody takes a look deeper to figure out what test is missing.
Let me know if you want to create a ticket.

**Comment by egonelbre** [comment]
@ifraixedes the PR that moved the tests was https://github.com/storj/storj/pull/2596 ... and it seems the test that got lost was https://github.com/storj/storj/pull/2596/files#diff-55c8b6ea331cf80cfd7e3e4760cba864L18

**Comment by ifraixedes** [comment]
then, I'm going restore that one into this file.

**Pull request merged**
