### PR TITLE
Added notification to multinode

### PR DESCRIPTION
**Pull request by ptdatta**
What: Added `web/satellite` notification system to `web/multinode`

image

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by ptdatta** [comment]
@ifraixedes @profclems can you review this PR. Once I get a green flag I can add this to all over `web/multinode`

**Review by profclems — DISMISSED** [review]

**Review by profclems — COMMENTED** [review]
This looks good. You just need to fix the lint errors with `npm run lint`

**Comment by ptdatta** [comment]
> This looks good. You just need to fix the lint errors with `npm run lint`

Yes yes I am waiting for your review I need to fix the lint and comment the function descriptions.
Thanks for reviewing.

**Comment by ptdatta** [comment]
> This looks good. You just need to fix the lint errors with `npm run lint`

@profclems Lint and comments done.✅

**Review by profclems — APPROVED** [review]

**Review by egonelbre — APPROVED** [review]

**Review by profclems — DISMISSED** [review]

**Review by egonelbre — APPROVED** [review]

**Review by profclems — APPROVED** [review]

**Pull request merged**
