### PR TITLE
Create admin node cmd

### PR DESCRIPTION
**Pull request by dylanlott**
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/105)

### CODE REVIEW

**Comment by coyle** [comment]
Review status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @dylanlott, @jtolds, @coyle, and @navillasa)

---

*[go.mod, line 0 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbkJs5FSY5L-LQlji:-LFZbkJs5FSY5L-LQljj:bxmxeha) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/go.mod#L0)):*
we shouldn't delete this

---

*[Gopkg.lock, line 0 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbmLP112Z5XI1c-Gg:-LFZbmLQ8JV22dP4WkBK:b-d4bpmp) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/Gopkg.lock#L0)):*
nor delete this

---

*[cmd/admin/main.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZqN0cBtLZLegEtqpe:-LFZqN0cBtLZLegEtqpf:baof1b6) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/cmd/admin/main.go#L1)):*
> ```Go
> package main
> ```

copyright

---

*[pkg/overlay/cache.go, line 85 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZobKt8fBKYiMrmHFT:-LFZobKt8fBKYiMrmHFU:b-l6mwxj) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L85)):*
> ```Go
> 	nodes, err := o.DHT.GetNodes(ctx, "0", 1280)
> 
> 	fmt.Printf("%+v\n", nodes)
> ```

remove

---

*[pkg/overlay/cache.go, line 88 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZoe-q-niv_Hjf0Z23:-LFZoe-q-niv_Hjf0Z24:bu2d1ig) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L88)):*
> ```Go
> 
> 	if err != nil {
> 		fmt.Printf("error getting nodes %s", err)
> ```

should use zap

---

*[pkg/overlay/cache.go, line 89 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZoi1uAAIkm4dspjGR:-LFZoi1v006ivkg8OtB7:bbbynde) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L89)):*
> ```Go
> 	if err != nil {
> 		fmt.Printf("error getting nodes %s", err)
> 		return err
> ```

can we wrap the error with zeebo?

---

*[pkg/overlay/test_redis-server.log, line 0 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZol2g6ujAP-KzATMz:-LFZol2g6ujAP-KzATN-:b-m0y0x5) ([raw file](https://github.com/storj/storj/blob/045dae5f0d7fc86dcd21884f53a0c65c1f0bd90f/pkg/overlay/test_redis-server.log#L0)):*
add to .gitignore

---

*[pkg/process/process.go, line 63 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZqVGd-rRFyVp78kxf:-LFZqVGd-rRFyVp78kxg:bz1r6fp) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/process/process.go#L63)):*
> ```Go
> 	}
> 
> 	wg.Wait()
> ```

this will never return because we are never calling wg.Done()

But I think we shouldn't wait until everything is done but stop processing if any error

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by dylanlott** [comment]
Review status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @dylanlott, @coyle, @jtolds, and @navillasa)

---

*[go.mod, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbkJs5FSY5L-LQlji:-LFsQ4OQ4GFjO00r9qkQ:brs52yn) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/go.mod#L)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

we shouldn't delete this
</blockquote></details>

I can cherry pick this out of the commit

---

*[Gopkg.lock, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbmLP112Z5XI1c-Gg:-LFsQ5p31ye7WmuOXynH:b-pjwuyu) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/Gopkg.lock#L)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

nor delete this
</blockquote></details>

Same with this one, I can cherry pick this out. 

---

*[cmd/admin/main.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZqN0cBtLZLegEtqpe:-LFckyaXAemCYc_ph3jK:b-896fix) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/cmd/admin/main.go#L1)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

copyright
</blockquote></details>

Done.

---

*[pkg/overlay/cache.go, line 85 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZobKt8fBKYiMrmHFT:-LFsZgtb5MVKk2lQVFXX:bb6un1j) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L85)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done

---

*[pkg/overlay/cache.go, line 88 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZoe-q-niv_Hjf0Z23:-LFsZgEb9-q-i3OrOt9l:bb6un1j) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L88)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should use zap
</blockquote></details>

Done

---

*[pkg/overlay/cache.go, line 89 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZoi1uAAIkm4dspjGR:-LFsZVjU8QYNqXT_0JJQ:bb6un1j) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/overlay/cache.go#L89)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

can we wrap the error with zeebo?
</blockquote></details>

Done

---

*[pkg/process/process.go, line 63 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZqVGd-rRFyVp78kxf:-LFcyq7Z0CCOohNEUOIo:b-896fix) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/process/process.go#L63)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

this will never return because we are never calling wg.Done()

But I think we shouldn't wait until everything is done but stop processing if any error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by dylanlott** [comment]
Review status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @dylanlott, @coyle, @jtolds, and @navillasa)

---

*[go.mod, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbkJs5FSY5L-LQlji:-LFsePBr45796cggyotx:b-iwda8k) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/go.mod#L)):*
<details><summary><i>Previously, dylanlott (Dylan Lott) wrote…</i></summary><blockquote>

I can cherry pick this out of the commit
</blockquote></details>

Added back

---

*[Gopkg.lock, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbmLP112Z5XI1c-Gg:-LFseQB21vnSDLhvaTmo:b-iwda8k) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/Gopkg.lock#L)):*
<details><summary><i>Previously, dylanlott (Dylan Lott) wrote…</i></summary><blockquote>

Same with this one, I can cherry pick this out. 
</blockquote></details>

Added back

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by dylanlott** [comment]
Review status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[pkg/overlay/test_redis-server.log, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZol2g6ujAP-KzATMz:-LFseXN8DdbrOnGhh-Nn:b-896fix) ([raw file](https://github.com/storj/storj/blob/045dae5f0d7fc86dcd21884f53a0c65c1f0bd90f/pkg/overlay/test_redis-server.log#L)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

add to .gitignore
</blockquote></details>

Done.

---

*[go.mod, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbkJs5FSY5L-LQlji:-LFseYIcAOz8VJe50SJM:b-896fix) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/go.mod#L)):*
<details><summary><i>Previously, dylanlott (Dylan Lott) wrote…</i></summary><blockquote>

Added back
</blockquote></details>

Done.

---

*[Gopkg.lock, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZbmLP112Z5XI1c-Gg:-LFseYfg1zkOGTrwiekM:b-896fix) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/Gopkg.lock#L)):*
<details><summary><i>Previously, dylanlott (Dylan Lott) wrote…</i></summary><blockquote>

Added back
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by coyle** [comment]
Reviewed 3 of 8 files at r1, 7 of 7 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @coyle, @dylanlott, @jtolds, and @navillasa)

---

*[pkg/netstate/service.go, line 22 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfOR33X9pjroXCU1t:-LFsfOR33X9pjroXCU1u:b-31y39p) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/netstate/service.go#L22)):*
> ```Go
> 
> var (
> 	port   = flag.Int("port", 8080, "port")
> ```

Not here with this PR, but something to think about when you do the config fixes for the rep is we probably don't want any of our flags defaulting. Going to be really confusing when something that you aren't specifying starts breaking.

---

*[pkg/netstate/service.go, line 29 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfLByC3x-R2RHq4yr:-LFsfLByC3x-R2RHq4ys:b-d7xofp) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/netstate/service.go#L29)):*
> ```Go
> func (s *Service) Process(ctx context.Context) error {
> 	if err := setEnv(); err != nil {
> 		s.logger.Error("error configuring environment for netstate server")
> ```

probably just return the error since main logs 

---

*[pkg/overlay/cache.go, line 21 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfzCj8_ilHGUBlnV5:-LFsfzCj8_ilHGUBlnV6:bpsjxxc) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/overlay/cache.go#L21)):*
> ```Go
> 
> var ErrNodeNotFound = errs.New("Node not found")
> var OverlayError = errs.Class("Overlay Error")
> ```

going to need a comment here

---

*[pkg/overlay/test_redis-server.log, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZol2g6ujAP-KzATMz:-LFsh26S5yLLxaGAJZ39:bgbncqo) ([raw file](https://github.com/storj/storj/blob/045dae5f0d7fc86dcd21884f53a0c65c1f0bd90f/pkg/overlay/test_redis-server.log#L)):*
<details><summary><i>Previously, dylanlott (Dylan Lott) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this should be deleted too

---

*[pkg/process/process.go, line 63 at r1](https://reviewable.io/reviews/storj/storj/105#-LFZqVGd-rRFyVp78kxf:-LFsgQIV4lQ02arfkVWZ:b9sxwq0) ([raw file](https://github.com/storj/storj/blob/dd9593bab7714f8f472a23fc700a5f4b2d91cc0c/pkg/process/process.go#L63)):*
this looks good but I'm thinking we want to bail if any of the services error.

>Wait blocks until all function calls from the Go method have returned, then returns the first non-nil error (if any) from them. 

we might want to implement our own version of this that listens for any error and immediately cleans up and returns

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by dylanlott** [comment]
Review status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @coyle, @dylanlott, @jtolds, and @navillasa)

---

*[pkg/netstate/service.go, line 22 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfOR33X9pjroXCU1t:-LFsjN9c3iNqcLcB4XI5:b-98jmvu) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/netstate/service.go#L22)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Not here with this PR, but something to think about when you do the config fixes for the rep is we probably don't want any of our flags defaulting. Going to be really confusing when something that you aren't specifying starts breaking.
</blockquote></details>

This is probably a good discussion to have on the config handling updates.  

---

*[pkg/netstate/service.go, line 29 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfLByC3x-R2RHq4yr:-LFswEKn1uEUlHuzO_H7:b-896fix) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/netstate/service.go#L29)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

probably just return the error since main logs 
</blockquote></details>

Done.

---

*[pkg/overlay/cache.go, line 21 at r2](https://reviewable.io/reviews/storj/storj/105#-LFsfzCj8_ilHGUBlnV5:-LFsjjQSD77sOSB1blVC:b-896fix) ([raw file](https://github.com/storj/storj/blob/89da6f5072542088cd314d070efe5be001a68c52/pkg/overlay/cache.go#L21)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

going to need a comment here
</blockquote></details>

Done.

---

*[pkg/overlay/test_redis-server.log, line  at r1](https://reviewable.io/reviews/storj/storj/105#-LFZol2g6ujAP-KzATMz:-LFt89eR-oiUDy2KGaO9:b-896fix) ([raw file](https://github.com/storj/storj/blob/045dae5f0d7fc86dcd21884f53a0c65c1f0bd90f/pkg/overlay/test_redis-server.log#L)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

this should be deleted too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by coyle** [comment]
Reviewed 1 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dylanlott, @jtolds, and @navillasa)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by coyle** [comment]
Review status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @coyle, @dylanlott, @jtolds, and @navillasa)

---

*[pkg/process/process.go, line 64 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxSmtq8TI71twYtjkY:-LFxSmtq8TI71twYtjkZ:b-l6mwxj) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L64)):*
> ```Go
> 
> 	for _, service := range s {
> 		fmt.Printf("starting service %+v\n", service)
> ```

remove

---

*[pkg/process/process.go, line 71 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxT70hAk6YvteSCtK7:-LFxT70hAk6YvteSCtK8:bqmzn5q) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L71)):*
> ```Go
> 			err := StartService(service)
> 			select {
> 			case <-ctx.Done():
> ```

Should pass the context into StartService and handle cancels there as well

---

*[pkg/process/process.go, line 73 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxStkr4DrcolB6NYh-:-LFxStkr4DrcolB6NYh0:bll0xcj) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L73)):*
> ```Go
> 			case <-ctx.Done():
> 				return
> 			default:
> ```

don't need this

---

*[pkg/process/process.go, line 77 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxTLCb0cf5-COiqNgm:-LFxTLCb0cf5-COiqNgn:b-4tite8) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L77)):*
> ```Go
> 			if err != nil {
> 				cancel()
> 				return
> ```

`return err`

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by coyle** [comment]
Review status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @coyle, @dylanlott, @jtolds, and @navillasa)

---

*[pkg/process/process.go, line 84 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxTiTF6jmqsUFRcw5b:-LFxTiTF6jmqsUFRcw5c:bk1g655) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L84)):*
> ```Go
> 
> 	wg.Wait()
> 	return ctx.Err()
> ```

There won't be an error here. You will need to pass the errors out from the go funcs

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Comment by dylanlott** [comment]
Review status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @coyle, @dylanlott, @jtolds, and @navillasa)

---

*[pkg/process/process.go, line 64 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxSmtq8TI71twYtjkY:-LFxeb6QBtEv_f1ht3sr:b-896fix) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L64)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[pkg/process/process.go, line 71 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxeZm93GMciOlQB6vn:-LFxeZm93GMciOlQB6vo:b-qbllhg) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L71)):*
> ls there as well

---

*[pkg/process/process.go, line 71 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxT70hAk6YvteSCtK7:-LFxe_uUAyMY51DBk-hM:b-896fix) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L71)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Should pass the context into StartService and handle cancels there as well
</blockquote></details>

Done.

---

*[pkg/process/process.go, line 73 at r5](https://reviewable.io/reviews/storj/storj/105#-LFxStkr4DrcolB6NYh-:-LFxX5fU8wbQzc-zYuEC:b-896fix) ([raw file](https://github.com/storj/storj/blob/594b680587bc498a580b02449861ca8d922a4e24/pkg/process/process.go#L73)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

don't need this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/105)*

**Pull request closed without merging**
