### PR TITLE
pkg/process: start replacing pkg/process with cobra helpers

### PR DESCRIPTION
**Pull request by jtolds**
Seems like what we had set up in pkg/process doesn't work well with cobra.

Start a new cobra-supporting scheme. All this does right now is set up logging.

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/98)

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jtolds and @cam-a)

---

*[pkg/proc/exec.go, line 23 at r1](https://reviewable.io/reviews/storj/storj/98#-LFMH3O74-ESgtfzVPoF:-LFMH3O74-ESgtfzVPoG:b-7i4s8s) ([raw file](https://github.com/storj/storj/blob/431632eec77e89e67ec4888ca6673989b8e98684/pkg/proc/exec.go#L23)):*
> ```Go
> 	home, err := homedir.Dir()
> 	if err != nil {
> 		return ""
> ```

How about assigning the current working directory to `home` (i.e. `home = ""`) and continue the execution? This way this method will always return a valid path for the config file, even on systems where the go-homedir library does not work for some reason.

And we should log the error for debugging purpose.

---

*[pkg/proc/exec.go, line 40 at r1](https://reviewable.io/reviews/storj/storj/98#-LFMILSm6jb374kvlQn4:-LFMILSo1xqhjqNzqX1F:bn3moy2) ([raw file](https://github.com/storj/storj/blob/431632eec77e89e67ec4888ca6673989b8e98684/pkg/proc/exec.go#L40)):*
> ```Go
> 		"config file")
> 
> 	var outer_defers []func()
> ```

This does not follow the Go naming convention - the linter complains.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by jtolds** [comment]
sorry friends, just saw your comments. they should be addressed though in this latest (probably more upsetting) change

**Comment by kaloyan-raev** [comment]
Review status: 0 of 14 files reviewed, 7 unresolved discussions (waiting on @jtolds and @cam-a)

---

*[examples/metric-receiver/main.go, line 11 at r2](https://reviewable.io/reviews/storj/storj/98#-LFNzXCaAeKUE6eZTOEw:-LFNzXCaAeKUE6eZTOEx:bcut2of) ([raw file](https://github.com/storj/storj/blob/cca89a3e5218f627e4666e11cabf31aac70cbc17/examples/metric-receiver/main.go#L11)):*
> ```Go
> 	"fmt"
> 
> 	"github.com/spf13/cobra"
> ```

There should be empty line below this line.

---

*[examples/metric-sender/main.go, line 10 at r2](https://reviewable.io/reviews/storj/storj/98#-LFNzbce6u8kfhbNtnl7:-LFNzbce6u8kfhbNtnl8:b-4khfkf) ([raw file](https://github.com/storj/storj/blob/cca89a3e5218f627e4666e11cabf31aac70cbc17/examples/metric-sender/main.go#L10)):*
> ```Go
> 	"flag"
> 
> 	"github.com/spf13/cobra"
> ```

Empty line below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by jtolds** [comment]
Review status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @coyle, @jtolds, and @cam-a)

---

*[examples/metric-sender/main.go, line 10 at r2](https://reviewable.io/reviews/storj/storj/98#-LFNzbce6u8kfhbNtnl7:-LFQ_ky94aCDPXAxZTRZ:b-irq5c7) ([raw file](https://github.com/storj/storj/blob/cca89a3e5218f627e4666e11cabf31aac70cbc17/examples/metric-sender/main.go#L10)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

Empty line below.
</blockquote></details>

whoops

---

*[pkg/proc/exec.go, line 23 at r1](https://reviewable.io/reviews/storj/storj/98#-LFMH3O74-ESgtfzVPoF:-LFQ_i6f9EOpInrewJAN:b-6pj7zu) ([raw file](https://github.com/storj/storj/blob/431632eec77e89e67ec4888ca6673989b8e98684/pkg/proc/exec.go#L23)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

How about assigning the current working directory to `home` (i.e. `home = ""`) and continue the execution? This way this method will always return a valid path for the config file, even on systems where the go-homedir library does not work for some reason.

And we should log the error for debugging purpose.
</blockquote></details>

whoops, missed the comment about logging

---

*[pkg/proc/exec.go, line 42 at r1](https://reviewable.io/reviews/storj/storj/98#-LFMm-Sf7Mxoo3y1sD6u:-LFQ_gxKE5lKPILZVIGW:b-896fix) ([raw file](https://github.com/storj/storj/blob/431632eec77e89e67ec4888ca6673989b8e98684/pkg/proc/exec.go#L42)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

why do this vs just use defer ?
</blockquote></details>

Done.

---

*[pkg/proc/exec.go, line 60 at r1](https://reviewable.io/reviews/storj/storj/98#-LFMlqgiArEGvXezgBy1:-LFQ_hAIEPNYlH_yDTnp:b-896fix) ([raw file](https://github.com/storj/storj/blob/431632eec77e89e67ec4888ca6673989b8e98684/pkg/proc/exec.go#L60)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should we panic here vs return os.exit ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by coyle** [comment]
Reviewed 8 of 16 files at r2, 4 of 4 files at r3.
Review status: 12 of 14 files reviewed, 7 unresolved discussions (waiting on @jtolds and @cam-a)

---

*[pkg/process/exec.go, line 26 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQ-vt4Cz6QvXb6f_5:-LFrQ-vu6uXCsCO4d9nY:b6qi5hw) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L26)):*
> ```Go
> 	home, err := homedir.Dir()
> 	if err != nil {
> 		log.Println(err)
> ```

Do we care if this errors? also, do we want to use zap?

---

*[pkg/process/exec.go, line 42 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQMCr6rEMGdS8baZv:-LFrQMCr6rEMGdS8baZw:b-nds49t) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L42)):*
> ```Go
> 	cobra.OnInitialize(func() {
> 		viper.BindPFlags(cmd.Flags())
> 		viper.SetEnvPrefix("storj")
> ```

nit - do we want this to be an exportable prefix so other services can use process.EnvPrefix ?

---

*[pkg/process/exec.go, line 52 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQYR01MbECXlhV68s:-LFrQYR01MbECXlhV68t:b-f7070u) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L52)):*
> ```Go
> 	err := cmd.Execute()
> 	if err != nil {
> 		os.Exit(1)
> ```

should we log the error ?

---

*[pkg/process/exec.go, line 76 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQaOfEi0TUnGxnJsC:-LFrQaOg9S8Mix0AfMY6:b-7fqhgd) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L76)):*
> ```Go
> func Must(err error) {
> 	if err != nil {
> 		log.Fatal(err)
> ```

zap ?

---

*[pkg/process/service.go, line 59 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQvdN8ff7kKWSyff9:-LFrQvdN8ff7kKWSyffA:b-pexdfi) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L59)):*
> ```Go
> 
> // SetLogger implements the Service interface but is a no-op
> func (f ServiceFunc) SetLogger(*zap.Logger) error { return nil }
> ```

should this do anything?

---

*[pkg/process/service.go, line 62 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQz8g1NIzTQta8FbQ:-LFrQz8hCA6aWgXhntXn:b-pexdfi) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L62)):*
> ```Go
> 
> // SetMetricHandler implements the Service interface but is a no-op
> func (f ServiceFunc) SetMetricHandler(*monkit.Registry) error { return nil }
> ```

should this do anything?

---

*[pkg/process/service.go, line 65 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrR9GiEdLF4Pth06BP:-LFrR9Gj3Qb5EupPzlcg:b-pexdfi) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L65)):*
> ```Go
> 
> // InstanceID implements the Service interface and expects default behavior
> func (f ServiceFunc) InstanceID() string { return "" }
> ```

should this do anything?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by jtolds** [comment]
Review status: 12 of 14 files reviewed, 7 unresolved discussions (waiting on @jtolds and @cam-a)

---

*[pkg/process/exec.go, line 26 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQ-vt4Cz6QvXb6f_5:-LFrzoh18JKStovaHLCl:bavaey3) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L26)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Do we care if this errors? also, do we want to use zap?
</blockquote></details>

lol, no i don't think we care if this errors. unfortunately, this function is happening before we parse commandline arguments (it's setting a default value), so we don't have any logging configured yet (should zap be prod or dev? etc)
my vote was to not even log at all but kaloyan thought we should log and i don't care much.

---

*[pkg/process/exec.go, line 42 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQMCr6rEMGdS8baZv:-LFs-78v1jIKWVRaBpkw:br5yafd) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L42)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

nit - do we want this to be an exportable prefix so other services can use process.EnvPrefix ?
</blockquote></details>

why would another process need to use process.EnvPrefix?

---

*[pkg/process/exec.go, line 52 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQYR01MbECXlhV68s:-LFs-C8g1VfORX5K_Q0T:bn536dk) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L52)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should we log the error ?
</blockquote></details>

oh my goodness yes, thank you

---

*[pkg/process/exec.go, line 76 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQaOfEi0TUnGxnJsC:-LFs-EFT7zjU6AvWrPSi:bfsi87y) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L76)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

zap ?
</blockquote></details>

which zap?

---

*[pkg/process/service.go, line 59 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQvdN8ff7kKWSyff9:-LFs-HZsAoiwhpqvUdSa:b-pfl2du) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L59)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should this do anything?
</blockquote></details>

for a ServiceFunc? no.

---

*[pkg/process/service.go, line 62 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQz8g1NIzTQta8FbQ:-LFs-JOA8agOpoFCtGVe:bb7od0r) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L62)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should this do anything?
</blockquote></details>

same

---

*[pkg/process/service.go, line 65 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrR9GiEdLF4Pth06BP:-LFs-KFLEjO_C1qNFWu0:b3fg9lc) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L65)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should this do anything?
</blockquote></details>

"" means default behavior.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by coyle** [comment]
:lgtm:

---

Reviewed 2 of 16 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @coyle and @cam-a)

---

*[pkg/process/exec.go, line 26 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQ-vt4Cz6QvXb6f_5:-LFs1wRFCfejg5sshGor:b-rpn526) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L26)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

lol, no i don't think we care if this errors. unfortunately, this function is happening before we parse commandline arguments (it's setting a default value), so we don't have any logging configured yet (should zap be prod or dev? etc)
my vote was to not even log at all but kaloyan thought we should log and i don't care much.

</blockquote></details>

perfect

---

*[pkg/process/exec.go, line 42 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQMCr6rEMGdS8baZv:-LFs23ioC-Vr-BSgzH9w:btcljaz) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L42)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

why would another process need to use process.EnvPrefix?
</blockquote></details>

I was thinking along the lines of the prefix maybe being a environment like 'dev' or 'prod'. We would reuse that for other setup.

---

*[pkg/process/exec.go, line 76 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQaOfEi0TUnGxnJsC:-LFs4kml7AVP4ScbE1r_:bfru85h) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L76)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

which zap?
</blockquote></details>

I think this was answered in your comments above about zap not being initialized at this point in the code

---

*[pkg/process/service.go, line 65 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrR9GiEdLF4Pth06BP:-LFs5CytEAp9FJihTIEF:b5lgwte) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/service.go#L65)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

"" means default behavior.
</blockquote></details>

missed that thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98#-:-LFs5MAg2WO-HV7kczHI:bnfp4nl)*

**Comment by jtolds** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cam-a)

---

*[pkg/process/exec.go, line 42 at r3](https://reviewable.io/reviews/storj/storj/98#-LFrQMCr6rEMGdS8baZv:-LFstLN82N2Vv921EJeD:bx5cgrc) ([raw file](https://github.com/storj/storj/blob/67bbbb7b3c7631769621a5e17ea9005f49899fdf/pkg/process/exec.go#L42)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I was thinking along the lines of the prefix maybe being a environment like 'dev' or 'prod'. We would reuse that for other setup.
</blockquote></details>

oh, very interesting! do you mind if i noodle on that more in another pull request?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98)*

**Comment by cam-a** [comment]
:lgtm:

---

Reviewed 6 of 16 files at r2, 2 of 4 files at r3, 6 of 6 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/98#-:-LFyz7CO5cMsRXRqDgQ0:bnfp4nl)*

**Pull request merged**
