### PR TITLE
Reduce number of nodes in captplanet to 10

### PR DESCRIPTION
**Pull request by jtolds**
Fixes https://storjlabs.atlassian.net/browse/V3-835

Make captain planet only use 10 nodes instead of 100

### CODE REVIEW

**Comment by jtolds** [comment]
@littleskunk does your test work on master? master has had some config changes. you may need to regenerate your config

**Comment by jtolds** [comment]
oh, sorry, no, you're right, this change depends on https://github.com/storj/storj/pull/791

**Comment by jtolds** [comment]
wait no, lol, i don't know what's going on. i'll fix it

**Comment by jtolds** [comment]
okay i think it's fixed now

**Comment by kaloyan-raev** [comment]
Just found this thing: https://github.com/storj/storj/blob/master/cmd/storagenode/main.go#L64
Is it anything that has to be adjusted as part of this change?

**Pull request merged**
