### PR TITLE
Rename Satellites in the Wizard

### PR DESCRIPTION
**Pull request by stefanbenten**
What: Renaming satellites from planets to regions.

Why: It needs to be done

Please describe the tests:
 - Test 1: -
 - Test 2: -
 
Please describe the performance impact: -

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by stefanbenten** [comment]
> some other change should take PromptForSatellite out of cfgstruct (it should not be in cfgstruct)

Where should it go?

**Comment by jtolds** [comment]
maybe pkg/process? maybe a new pkg/wizard? pkg/cfgstruct should just be about parsing/handling config structs

**Comment by jtolds** [comment]
worth making clear that doesn't need to be this pr

**Comment by egonelbre** [comment]
`internal/wizard` maybe... maybe even in `cmd/internal/wizard`?

**Pull request merged**
