### PR TITLE
internal/testplanet: WORKAROUND Don't call shutdown in constructors

### PR DESCRIPTION
**Pull request by ifraixedes**
What: `NewCustom` `Planet` calls shutdown on any error without having started the
planet.

Why: Because calling `Shutdonw` before the planet instance is started returns an error making the error of `NewCustom`, and any other constructors, to return a second error message which isn't justified and is always the same.

This is a workaround until the shutdown process will be split in two parts and it's possible to close resources from without checking if the Planet has started. See https://github.com/storj/storj/pull/3346#issuecomment-545387710

Please describe the tests: None have been added because `testsplanet` is a utility for testing and we don't test them up to the point to check the error messages.
Please describe the performance impact: N/A

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by egonelbre** [comment]
The reason it's doing shutdown is because otherwise things leak. Folders are left undeleted, listeners unclosed etc.

Of course, it should be possible to call shutdown on partially constructed planet and it shouldn't hide the original error.

**Comment by ifraixedes** [comment]
I don't understand what `Shutdown` does in the constructor.

`Shutdowns` first check is to ensure that `planet` is started and if it isn't then it returns an error https://github.com/storj/storj/pull/3346/files#diff-c2ce7a2c9b2f4920e2de524c0fffd2f1L244.

I had this test error output:

```
 go test ./uplink/...                                                                                                                           git:(master)  
?       storj.io/storj/uplink   [no test files]                 
--- FAIL: TestECClient (0.00s)                
    logger.go:130: 2019-10-23T11:53:59.408+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Satellite"}
    logger.go:130: 2019-10-23T11:53:59.408+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Storagenode"}
    logger.go:130: 2019-10-23T11:53:59.408+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Uplink"}
    logger.go:130: 2019-10-23T11:53:59.408+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Gateway"}
    logger.go:130: 2019-10-23T11:53:59.408+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Identity"}
    logger.go:130: 2019-10-23T11:53:59.408+0200 DEBUG   versioncontrol  setting version info to: {"Satellite":"0.0.1","Storagenode":"0.0.1","Uplink":"0.0.1","Gateway":
"0.0.1","Identity":"0.0.1","processes":{"satellite":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"storagen
ode":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"uplink":{"minimum":{"version":"","url":""},"suggested":
{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"gateway":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","curso
r":""}},"identity":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}}}}
    logger.go:130: 2019-10-23T11:53:59.408+0200 DEBUG   versioncontrol   addr= 127.0.0.1:41873                                                                        
    require.go:794:                                                                                                                                                   
                Error Trace:    client_planet_test.go:41                                                                                                              
                Error:          Received unexpected error:                                                                                                            
                                group:                                                                                                                                
                                --- Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0
                                --- Start was never called
                Test:           TestECClient                
FAIL                                                                                                                                                                  
FAIL    storj.io/storj/uplink/ecclient  0.121s
ok      storj.io/storj/uplink/eestream  0.145s                  
?       storj.io/storj/uplink/metainfo  [no test files]
ok      storj.io/storj/uplink/metainfo/kvmetainfo       0.148s   
?       storj.io/storj/uplink/piecestore        [no test files]                                                                                                       
?       storj.io/storj/uplink/storage/buckets   [no test files]
?       storj.io/storj/uplink/storage/meta      [no test files]
?       storj.io/storj/uplink/storage/objects   [no test files]                                                                                                       
ok      storj.io/storj/uplink/storage/segments  0.006s                                                                                                                
ok      storj.io/storj/uplink/storage/streams   0.069s                                                                                                                
?       storj.io/storj/uplink/stream    [no test files]   
```

And after applied these changes, I've got

```
 go test ./uplink/...                                                                                                                   git:(orange/v3-2620)  
?       storj.io/storj/uplink   [no test files]  
--- FAIL: TestECClient (0.00s)     
    logger.go:130: 2019-10-23T12:03:51.349+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Satellite"}
    logger.go:130: 2019-10-23T12:03:51.349+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Storagenode"}                             
    logger.go:130: 2019-10-23T12:03:51.349+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Uplink"}                                  
    logger.go:130: 2019-10-23T12:03:51.349+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Gateway"}
    logger.go:130: 2019-10-23T12:03:51.349+0200 WARN    versioncontrol  rollout config error: empty seed        {"binary": "Identity"}
    logger.go:130: 2019-10-23T12:03:51.349+0200 DEBUG   versioncontrol  setting version info to: {"Satellite":"0.0.1","Storagenode":"0.0.1","Uplink":"0.0.1","Gateway":
"0.0.1","Identity":"0.0.1","processes":{"satellite":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"storagen
ode":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"uplink":{"minimum":{"version":"","url":""},"suggested":
{"version":"","url":""},"rollout":{"seed":"","cursor":""}},"gateway":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","curso
r":""}},"identity":{"minimum":{"version":"","url":""},"suggested":{"version":"","url":""},"rollout":{"seed":"","cursor":""}}}}
    logger.go:130: 2019-10-23T12:03:51.350+0200 DEBUG   versioncontrol   addr= 127.0.0.1:36455
    require.go:794:
                Error Trace:    client_planet_test.go:41
                Error:          Received unexpected error:
                                Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0
                Test:           TestECClient
FAIL
FAIL    storj.io/storj/uplink/ecclient  0.056s
ok      storj.io/storj/uplink/eestream  (cached)
?       storj.io/storj/uplink/metainfo  [no test files]
ok      storj.io/storj/uplink/metainfo/kvmetainfo       0.053s
?       storj.io/storj/uplink/piecestore        [no test files]
?       storj.io/storj/uplink/storage/buckets   [no test files]
?       storj.io/storj/uplink/storage/meta      [no test files]
?       storj.io/storj/uplink/storage/objects   [no test files]
ok      storj.io/storj/uplink/storage/segments  (cached)
ok      storj.io/storj/uplink/storage/streams   0.060s
?       storj.io/storj/uplink/stream    [no test files]

```

What's the difference?

Before the change, you get

```
                Error:          Received unexpected error:                                                                                                            
                                group:                                                                                                                                
                                --- Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0
                                --- Start was never called
```

After, you get:

```
                Error Trace:    client_planet_test.go:41
                Error:          Received unexpected error:
                                Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0
                Test:           TestECClient

```

Not a big change, but I prefer not to see misguiding error messages.

**Comment by egonelbre** [comment]
I think it should split the shutdown into two parts one that does the starting checks and the other that closes everything. That way the constructor can call the other closing without tripping over the starting check.

The `Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0` should be fixed as well. e.g. in the beginning of newSatellite check whether the enviornment variable has been set.

**Comment by ifraixedes** [comment]
> The Could not parse DB URL &search_path=testecclient%2F1d729566c74d%2Fs0 should be fixed as well. e.g. in the beginning of newSatellite check whether the enviornment variable has been set.

Great to know, but I stumbled over it working in another thing and got the test failure and realizing that now we need postgres for everything though the testing doc hasn't been updated (this is something that I will update later if nobody has done before).

I'm fine closing the PR and creating a ticket for making all those improvements. This PR was a quick improvement if we want to go with a better but more time dedication improvement, it should be planned.

**Comment by egonelbre** [comment]
In this PR we could give a more descriptive error when https://github.com/storj/storj/blob/master/internal/testplanet/satellite.go#L224 doesn't have the connection string defined.

**Comment by ifraixedes** [comment]
> In this PR we could give a more descriptive error when https://github.com/storj/storj/blob/master/internal/testplanet/satellite.go#L224  doesn't have the connection string defined.

Being honest, I didn't look for where that error came, I just gave a try to define the `STORJ_POSTGRES_TEST` env variable and it worked. I supposed that it was that from the message when I took the test that failed but I wondered what was that `Start was never called` and quickly found that it could be removed from it without not leaking resources at the point where it was called.

**Comment by ifraixedes** [comment]
@egonelbre do you prefer to close this PR and leave for the future the better improvement that you commented?

**Comment by egonelbre** [comment]
Let's add the better description in this PR and fix the closing errors later. e.g.

https://github.com/storj/storj/blob/master/internal/testplanet/satellite.go#L232

```
if !satellitedbtest.Defined() { return ..., error.New }
```

That should be an easy change, but would prevent this exact problem occurring.

**Comment by ifraixedes** [comment]
I added a comment in the description of the PR, pointing that this is a workaround. I also mention that in PR's subject.

**Comment by egonelbre** [comment]
I made a clearer fix here https://github.com/storj/storj/pull/3539

**Comment by egonelbre** [comment]
@ifraixedes I think you can close this for now.

**Comment by ifraixedes** [comment]
Closed in favor of https://github.com/storj/storj/pull/3539

**Pull request closed without merging**
