### PR TITLE
Make sed a little more cross platformable.

### PR DESCRIPTION
**Pull request by brimstone**
What: Make sed a little more cross platform.

Why: go:generate should work on linux AND macOS

Please describe the tests: No more tests.

Please describe the performance impact: No impact.

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible?
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by zeebo** [comment]
I'm still getting errors running this. I think the problem is that `go:generate` only interprets `"` as grouping, so it needs to be

```
//go:generate sed -i'' "1i //lint:file-ignore * generated file\n" satellitedb.dbx.go
```

**Comment by brimstone** [comment]
Do those quotes work?

**Comment by zeebo** [comment]
Yes, but then the `-i''` is broken with gnused (linux).

**Comment by zeebo** [comment]
```
//go:generate bash -c "sed -i'' '1i //lint:file-ignore * generated file\n' satellitedb.dbx.go"
```

seems to work for me.

**Comment by zeebo** [comment]
Be sure to run `go generate` after as well because it doesn't have a newline that currently exists.

**Pull request merged**
