### PR TITLE
updating the reed solomon numbers 

### PR DESCRIPTION
**Pull request by iglesiasbrandon**
Data Science initial numbers
n = 95
o = 80 
m = 35
k = 29

### CODE REVIEW

**Comment by egonelbre** [comment]
Please also test the potential performance impact of these numbers.

**Comment by littleskunk** [comment]
> Please also test the potential performance impact of these numbers.

That is easy to predict. At the moment up and download speed is depending on the storage expansion factor. The pull request will increase the storage expansion factor from 2.5 to 3.3. The maximum up and download speed will decrease by 30%.
Note: We have an open feature request that should disconnect the download speed from the storage expansion factor.

Doesn't replace the requested speed test. This is just my expactation.

**Comment by egonelbre** [comment]
Since the erasure parameters changed then the cost of doing erasure shares also changes.
Similarly there's more internal overhead for communicating with multiple nodes.

**Comment by iglesiasbrandon** [comment]
@egonelbre these are the reed Solomon numbers the data science team came up with given some constraints we gave them like it has to be less than 100 and we need 11 9's of durability. I think these numbers will be changing based on how our node churn looks in production. @pgerbes1 or @benjaminsirb would be really good people to talk to if you want to know more about how they came to these numbers!

**Comment by egonelbre** [comment]
@iglesiasbrandon sure, I'm not questioning the numbers themselves. Just want to make sure we don't just by accident make upload/download 100x slower. I know it's unlikely that it's that bad, but it's good to have a rough idea what the impact on other metrics is.

**Comment by iglesiasbrandon** [comment]
@egonelbre you definitely have a good point, I will make sure we have baseline metrics before this gets merged so that we can compare performance after.

**Comment by brimstone** [comment]
Staging is now ready for this PR.

**Pull request merged**
