### PR TITLE
Reverting uplink(V3-1717) and gateway(V3-1718) enc key changes

### PR DESCRIPTION
**Pull request by aligeti**
What: 
Not want to encrypt paths so we get ordered listing
Why:
With encrypted paths you can’t get alphabetical listing, which means we cant not require enc.key

Will be reverting changes associated with Tickets V3-1717(PR #1952) & V3-1718(PR #1923)
Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by jtolds** [comment]
Wait wait, I'm miscommunicating to a bunch of folks.

**Comment by jtolds** [comment]
Wait wait, I'm miscommunicating to a bunch of folks.

@ifraixedes @aligeti @iglesiasbrandon 

We want to support unencrypted paths in the data model and in the config file. We want to make sure people can get ordered listing if they really want.

That's separate than what the wizard does. IF there's a passphrase, we should require it. If someone is intending to encrypt their data (which is what the wizard does), we should make them choose a non-empty passphrase. If we want to extend the wizard to let people choose unencrypted paths, then that's different, but we should not allow empty passphrases.

We don't need to revert these changes. Okay to close this PR without merging?

**Comment by aligeti** [comment]
> Wait wait, I'm miscommunicating to a bunch of folks.
> 
> @ifraixedes @aligeti @iglesiasbrandon
> 
> We want to support unencrypted paths in the data model and in the config file. We want to make sure people can get ordered listing if they really want.
> 
> That's separate than what the wizard does. IF there's a passphrase, we should require it. If someone is intending to encrypt their data (which is what the wizard does), we should make them choose a non-empty passphrase. If we want to extend the wizard to let people choose unencrypted paths, then that's different, but we should not allow empty passphrases. Empty passphrases are not the same thing as choosing to not encrypt your paths.
> 
> We don't need to revert these changes. Okay to close this PR without merging?

got it ...closing the PR.

**Comment by ifraixedes** [comment]
> If we want to extend the wizard to let people choose unencrypted paths, then that's different

It means that at some point we are going to allow the users to configure if they want to encrypt the path or not, but the data will be always encrypted?

**Pull request closed without merging**
