### PR TITLE
Coyle/kad client

### PR DESCRIPTION
**Pull request by coyle**
Adds a new client interface to interact with the overlay service.

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/91)

### CODE REVIEW

**Comment by jtolds** [comment]
Review status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @coyle)

---

*[pkg/overlay/client.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9RcL3O4gC4DPf0o4:-LEq9RcN1qAkDcVt-hLH:b-o4m57n) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L1)):*
> ```Go
> package overlay
> ```

copyright?

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LEq9VedC4HqqVyVwM_H:bvb8w4o) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
> ```Go
> //  over X amount of time
> type Client interface {
> 	Choose(ctx context.Context, amount int, space, bw int) ([]NodeID, error)
> ```

i'd prefer to do bytes instead of kilobytes. no reason to waste granularity. the tradeoff is we'll have to use int64 instead of int or else we're limited to 2GB but that's fine to use int64

---

*[pkg/overlay/client.go, line 46 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9vkE0ZyfBEceed9O:-LEq9vkE0ZyfBEceed9P:b-wj9avz) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L46)):*
> ```Go
> 		ids = append(ids, NodeID(v.GetId()))
> 	}
> 	return ids, nil
> ```

so, it actually would be stellar if while we're making this request with the overlay service if we get addresses too. otherwise we're going to have to immediately go back and look up len(id) node ids in just a second. that's kind of why i was thinking this would return []Node. I don't care if we use the dtypes.Node struct. I'm okay if it's a proto.Node, but we should return the addresses here. 

---

*[pkg/overlay/client.go, line 53 at r1](https://reviewable.io/reviews/storj/storj/91#-LEqAGxBDYRdAXDeZl71:-LEqAGxBDYRdAXDeZl72:bcnemx5) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L53)):*
> ```Go
> 	resp, err := o.client.Lookup(ctx, &proto.LookupRequest{NodeID: nodeID.String()})
> 	if err != nil {
> 		return &proto.Node{}, err
> ```

you can just return nil, err, right?

---

*[pkg/overlay/client_test.go, line 11 at r1](https://reviewable.io/reviews/storj/storj/91#-LEqAKzj8wLdszPpHpWE:-LEqAKzj8wLdszPpHpWF:b-4pk4bx) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client_test.go#L11)):*
> ```Go
> 	"github.com/stretchr/testify/assert"
> 	"google.golang.org/grpc"
> 	proto "storj.io/storj/protos/overlay"
> ```

newline before storj.io stanza

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @jtolds and @coyle)

---

*[pkg/overlay/client.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9RcL3O4gC4DPf0o4:-LEqP_Vv6salF3O3aanx:b-896fix) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L1)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

copyright?
</blockquote></details>

Done.

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LEqQ1KCD35ppIfgPET7:b4garoj) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

i'd prefer to do bytes instead of kilobytes. no reason to waste granularity. the tradeoff is we'll have to use int64 instead of int or else we're limited to 2GB but that's fine to use int64
</blockquote></details>

This was just a straw man. I didn't know what was appropriate. I'll make the change.

For bandwidth, what is the duration the bandwidth is over?

---

*[pkg/overlay/client.go, line 46 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9vkE0ZyfBEceed9O:-LEqRqgTBleklKhwe5J_:b-896fix) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L46)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

so, it actually would be stellar if while we're making this request with the overlay service if we get addresses too. otherwise we're going to have to immediately go back and look up len(id) node ids in just a second. that's kind of why i was thinking this would return []Node. I don't care if we use the dtypes.Node struct. I'm okay if it's a proto.Node, but we should return the addresses here. 
</blockquote></details>

Done.

---

*[pkg/overlay/client.go, line 53 at r1](https://reviewable.io/reviews/storj/storj/91#-LEqAGxBDYRdAXDeZl71:-LEqS4SO0esAJhwqD7YD:b-896fix) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L53)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

you can just return nil, err, right?
</blockquote></details>

Done.

---

*[pkg/overlay/client_test.go, line 11 at r1](https://reviewable.io/reviews/storj/storj/91#-LEqAKzj8wLdszPpHpWE:-LEqSJKl-CV3d3g8Xe-B:b-896fix) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client_test.go#L11)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

newline before storj.io stanza
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds and @coyle)

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LEtNAAR5RtgwJfXMiw-:bigxnmf) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
> ```Go
> // amount is the number of nodes you would like returned,
> // space is the storage amount in bytes and
> // bandwidth is the amount of bandwidth in bytes requested over X amount of time
> ```

So nice to have this additional documentation. Is the in method declaration in the interface a better place for it? My guess is that having it on the interface will help editors provide better intellisense.

---

*[pkg/overlay/client_test.go, line 23 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOfeLEhRyzajNUo1w:-LEtOfeLEhRyzajNUo1x:b-xpo441) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L23)):*
> ```Go
> 	}{
> 		{
> 			address: "127.0.0.1:8080",
> ```

How about adding more test cases, e.g. missing port, missing host, invalid port, etc.?

---

*[pkg/overlay/client_test.go, line 49 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOsVe9VQFUuswJXFQ:-LEtOsVe9VQFUuswJXFR:b8z5exp) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L49)):*
> ```Go
> 			bw:            1000,
> 			expectedCalls: 1,
> 		},
> ```

More test cases here too for testing boundary and invalid input values?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds and @coyle)

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LEt_btt4H72UR1aYBUB:b3ysoye) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

So nice to have this additional documentation. Is the in method declaration in the interface a better place for it? My guess is that having it on the interface will help editors provide better intellisense.
</blockquote></details>

I has it on the interface but Kishore asked me what each was when using the method so I thought it might be better there. Maybe on both ?

---

*[pkg/overlay/client_test.go, line 23 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOfeLEhRyzajNUo1w:-LEtZqfu3CEPkFC2UgVf:b-o83fao) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L23)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

How about adding more test cases, e.g. missing port, missing host, invalid port, etc.?
</blockquote></details>

Great comment! I'm doing this with the current ticket:

https://www.pivotaltracker.com/story/show/158260327

I need the underlying code tested/working appropriately in the edge cases before these will pass in those cases. I will add more tests for this pkg at the same time.

---

*[pkg/overlay/client_test.go, line 49 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOsVe9VQFUuswJXFQ:-LEt_RshEeFp0c9b4jXu:bnj7hl0) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L49)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

More test cases here too for testing boundary and invalid input values?
</blockquote></details>

same as above

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds and @kaloyan-raev)

---

*[pkg/overlay/client_test.go, line 49 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOsVe9VQFUuswJXFQ:-LEuAbEI4nC2g8l9OEmR:b9udeh7) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L49)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

perhaps you could use `testing/quick`https://golang.org/pkg/testing/quick/

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds and @kaloyan-raev)

---

*[pkg/overlay/client_test.go, line 49 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtOsVe9VQFUuswJXFQ:-LEuBCJo40ifcPyqX9-j:bv1yb3q) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client_test.go#L49)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

perhaps you could use `testing/quick`https://golang.org/pkg/testing/quick/
</blockquote></details>

but then I'm just testing the mock right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @jtolds and @kaloyan-raev)

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LEuhI-RD7OxY0Ys6E_N:bnfs9nq) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I has it on the interface but Kishore asked me what each was when using the method so I thought it might be better there. Maybe on both ?
</blockquote></details>

How about having the documentation on the interface and refer to it in the implementation? Isn't there some best practice or convention?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds, @coyle, and @kaloyan-raev)

---

*[pkg/overlay/node.go, line 7 at r3](https://reviewable.io/reviews/storj/storj/91#-LEukVDmDuvJw4ZQCVLf:-LEukVDoD0sTYRah8DLp:bykcv8f) ([raw file](https://github.com/storj/storj/blob/b57d27e9ff9889aec9fb7631836ef48e8f45c318/pkg/overlay/node.go#L7)):*
> ```Go
> 
> // NodeID is the unique identifer of a Node in the overlay network
> type NodeID string
> ```

We should have a common place to define types like this. For example, the NetClient also has `NoteID` in its interface and it should be the same type like this one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @jtolds, @coyle, and @kaloyan-raev)

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LEurjdY9ZQogUVsDo58:b-in0oe2) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

How about having the documentation on the interface and refer to it in the implementation? Isn't there some best practice or convention?
</blockquote></details>

I think adding to the interface is correct and then a comment that it implements the interface would suffice.

---

*[pkg/overlay/node.go, line 7 at r3](https://reviewable.io/reviews/storj/storj/91#-LEukVDmDuvJw4ZQCVLf:-LEurtiV4SfVer0mvy4z:by64jpz) ([raw file](https://github.com/storj/storj/blob/b57d27e9ff9889aec9fb7631836ef48e8f45c318/pkg/overlay/node.go#L7)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

We should have a common place to define types like this. For example, the NetClient also has `NoteID` in its interface and it should be the same type like this one.
</blockquote></details>

I think eith overlay.NodeID should be the source of truth or we create a package for NodeIDs. There will be a lot of functionality added to the NodeID type in the future for s/kad and proof of work etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @jtolds and @kaloyan-raev)

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LEuuKCqAoWmBm457GCe:b-ba7jcz) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I think adding to the interface is correct and then a comment that it implements the interface would suffice.
</blockquote></details>

Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by jtolds** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @coyle and @kaloyan-raev)

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LF13eTP3iiT5t42NAXh:bjf2kww) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

This was just a straw man. I didn't know what was appropriate. I'll make the change.

For bandwidth, what is the duration the bandwidth is over?
</blockquote></details>

I think that's up to the node but it should at least encompass the next hour

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LF2c5hqEXrvqsgTFWN7:b-1acck4) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

I think that's up to the node but it should at least encompass the next hour
</blockquote></details>

Should we add an extra parameter for time? I'm not understanding the point of bandwidth if there isn't a clearly defined time scope. requesting 100mib of bandwidth over the next hour is completely different than the same amount over a month.

---

*[pkg/overlay/client.go, line 38 at r2](https://reviewable.io/reviews/storj/storj/91#-LEtNAAR5RtgwJfXMivz:-LF2d2-J7I5w1bJ91FXM:b-896fix) ([raw file](https://github.com/storj/storj/blob/786443b63f72798deb3c929c5fd26252869873c7/pkg/overlay/client.go#L38)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by jtolds** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev and @coyle)

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LF2z6iw2qWFcSqoIdZF:b-y6sk1) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Should we add an extra parameter for time? I'm not understanding the point of bandwidth if there isn't a clearly defined time scope. requesting 100mib of bandwidth over the next hour is completely different than the same amount over a month.
</blockquote></details>

the time scope is immediate. calling Choose is saying "we're asking to store x amount of bytes right now".  the dht cache is only going to have something that's up to an hour stale. meanwhile, the dht nodes have a rolling window of how much bandwidth they're allowed to use to stay under a rule that any given consecutive 30 day window, they use less than y bytes. so each dht node will be able to say "at this given moment, i can use up to z bytes of bandwidth and still stay under my rolling y bandwidth limit" and that's what they'll be reporting over the dht.

it's worth pointing out that this is a bit race condition-y: two uploads could both decide to use the last 4 MB of some node's space or bandwidth. one or both of them might fail. that's okay. we're going to have to retry a few uploads from time to time anyway

i suppose this does mean that space and bw could be the same variable. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev and @coyle)

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LF30M8K-KlPk7_ztzOC:b7mik0k) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

the time scope is immediate. calling Choose is saying "we're asking to store x amount of bytes right now".  the dht cache is only going to have something that's up to an hour stale. meanwhile, the dht nodes have a rolling window of how much bandwidth they're allowed to use to stay under a rule that any given consecutive 30 day window, they use less than y bytes. so each dht node will be able to say "at this given moment, i can use up to z bytes of bandwidth and still stay under my rolling y bandwidth limit" and that's what they'll be reporting over the dht.

it's worth pointing out that this is a bit race condition-y: two uploads could both decide to use the last 4 MB of some node's space or bandwidth. one or both of them might fail. that's okay. we're going to have to retry a few uploads from time to time anyway

i suppose this does mean that space and bw could be the same variable. 
</blockquote></details>

This makes way more sense now. Thanks! 

I say we combine space and bandwidth since they will always be the same.

---

*[pkg/overlay/client.go, line 13 at r4](https://reviewable.io/reviews/storj/storj/91#-LF2oi-3DEUcD66KCGPM:-LF30FjH3-_IcQLTaPdc:b-h7rx6l) ([raw file](https://github.com/storj/storj/blob/0508d3a071a33b79ecb2920b9d42809592f96697/pkg/overlay/client.go#L13)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

I noticed that the documentation in go built-in packages has an empty line between the interface documentation and that of its methods. Should we have an empty line here too?
</blockquote></details>

I'm not entirely sure I understand:

https://golang.org/src/io/io.go?s=4043:4083#L88

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev and @coyle)

---

*[pkg/overlay/client.go, line 13 at r4](https://reviewable.io/reviews/storj/storj/91#-LF2oi-3DEUcD66KCGPM:-LF30ymm71PYIWshje2d:bf753ub) ([raw file](https://github.com/storj/storj/blob/0508d3a071a33b79ecb2920b9d42809592f96697/pkg/overlay/client.go#L13)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I'm not entirely sure I understand:

https://golang.org/src/io/io.go?s=4043:4083#L88
</blockquote></details>

Wait, I think I see what you mean. I had never noticed this before:
https://golang.org/src/io/io.go?s=4043:4083#L163

but yes, I think that would be great to do here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by jtolds** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---

*[pkg/overlay/client.go, line 14 at r1](https://reviewable.io/reviews/storj/storj/91#-LEq9VedC4HqqVyVwM_G:-LF31Oo4DiJrs57LONfK:b-7jh2x4) ([raw file](https://github.com/storj/storj/blob/3d5b7ba027d52d717ac0432a054f76e94e1c0142/pkg/overlay/client.go#L14)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

This makes way more sense now. Thanks! 

I say we combine space and bandwidth since they will always be the same.
</blockquote></details>

sgtm

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---

*[pkg/overlay/client.go, line 13 at r4](https://reviewable.io/reviews/storj/storj/91#-LF2oi-3DEUcD66KCGPM:-LF371Lq3Eb78uIaK3HR:b-896fix) ([raw file](https://github.com/storj/storj/blob/0508d3a071a33b79ecb2920b9d42809592f96697/pkg/overlay/client.go#L13)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Wait, I think I see what you mean. I had never noticed this before:
https://golang.org/src/io/io.go?s=4043:4083#L163

but yes, I think that would be great to do here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Comment by jtolds** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91#-:-LFI7emF-4SG0YDVbWXa:bnfp4nl)*

**Comment by kaloyan-raev** [comment]
Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/91)*

**Pull request merged**
