### PR TITLE
Bolt backed overlay cache

### PR DESCRIPTION
**Pull request by bryanchriswhite**
([see story #158259670](https://www.pivotaltracker.com/story/show/158259670))

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/94)

### CODE REVIEW

**Comment by coyle** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @bryanchriswhite)

---

*[Gopkg.lock, line 298 at r1](https://reviewable.io/reviews/storj/storj/94#-LEz_JgY0gty9VV1K5lY:-LEz_JgY0gty9VV1K5lZ:b2k0yaf) ([raw file](https://github.com/storj/storj/blob/1ebd66d880bcaa83587f2982737b2ebf8aee7050/Gopkg.lock#L298)):*
> ```TOML
> 
> [[projects]]
>   name = "github.com/julienschmidt/httprouter"
> ```

we got rid of this dependency ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by bryanchriswhite** [comment]
Review status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @coyle and @bryanchriswhite)

---

*[Gopkg.lock, line 298 at r1](https://reviewable.io/reviews/storj/storj/94#-LEz_JgY0gty9VV1K5lY:-LEzfVlw-qRxvTB2XIn3:b-juq7f6) ([raw file](https://github.com/storj/storj/blob/1ebd66d880bcaa83587f2982737b2ebf8aee7050/Gopkg.lock#L298)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

we got rid of this dependency ?
</blockquote></details>

pretty sure this is just from running `dep ensure`

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by jtolds** [comment]
Review status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @coyle and @bryanchriswhite)

---

*[pkg/overlay/service.go, line 137 at r2](https://reviewable.io/reviews/storj/storj/94#-LF14igTCD1a_CyZccXu:-LF14igTCD1a_CyZccXv:b-89zgwx) ([raw file](https://github.com/storj/storj/blob/b5f27f9f538552694a74dea27a4f535377d5b101/pkg/overlay/service.go#L137)):*
> ```Go
> 	mux := http.NewServeMux()
> 	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintln(w, "OK") })
> 	go func() { http.ListenAndServe(fmt.Sprintf(":%s", httpPort), nil) }()
> ```

should probably pass mux to ListenAndServe for its second argument?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by bryanchriswhite** [comment]
Review status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @coyle and @jtolds)

---

*[pkg/overlay/service.go, line 137 at r2](https://reviewable.io/reviews/storj/storj/94#-LF14igTCD1a_CyZccXu:-LFHvs1d6WklSwUj3ylg:b-896fix) ([raw file](https://github.com/storj/storj/blob/b5f27f9f538552694a74dea27a4f535377d5b101/pkg/overlay/service.go#L137)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

should probably pass mux to ListenAndServe for its second argument?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by coyle** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @jtolds and @bryanchriswhite)

---

*[pkg/overlay/service_test.go, line 30 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI2Wzs1zKCfnAVcU4d:-LFI2Wzt1PL7DN4YecL9:b-39tvfd) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L30)):*
> ```Go
> 
> func setPortFlags(t *testing.T) {
> 	availablePort, err := test.NewPort()
> ```

Great! 

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by coyle** [comment]
:lgtm:

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @jtolds and @bryanchriswhite)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94#-:-LFI2kQYDbkjKRLETc8x:bnfp4nl)*

**Comment by jtolds** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @jtolds and @bryanchriswhite)

---

*[internal/test/port.go, line 1 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8He07kK5bOcU_w8M:-LFI8He07kK5bOcU_w8N:baof1b6) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L1)):*
> ```Go
> package test
> ```

copyright

---

*[internal/test/port.go, line 17 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8L93DbEx6KkoPc8S:-LFI8L93DbEx6KkoPc8T:b-owevsq) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L17)):*
> ```Go
> 	// If there's an error it likely means no ports
> 	// are available or something else prevented finding
> 	// an open port
> ```

you don't need to leave this comment, lol. i prefer

```
server, err := net.Listen("tcp", ":0")
if err != nil { 
  return 0, err
}
```

---

*[internal/test/port.go, line 35 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8pGA0JgIZmpBxGnQ:-LFI8pGA0JgIZmpBxGnR:b9x3i8m) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L35)):*
> ```Go
> 
> 	// Return the port as an int
> 	return strconv.Atoi(portString)
> ```

overall, this function is racy. if this listen succeeds and chooses a port, the minute you return and close the listener, the port may get grabbed by something else and the assumption the port is free is no longer true. it is generally the case that ports are allocated sequentially so this is a minor issue, but why use this function at all? could you instead just use Listen("tcp", ":0") at the location you need a port instead?

---

*[internal/test/port.go, line 39 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI9IiCDpjVYaqKfKlv:-LFI9IiCDpjVYaqKfKlw:bvgvtvj) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L39)):*
> ```Go
> 
> // CheckPort checks if a port is available
> func CheckPort(port int) (status bool, err error) {
> ```

same overall feedback. 

---

*[pkg/overlay/service_test.go, line 33 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI9RRZ6iZlKkeOtUiH:-LFI9RRZ6iZlKkeOtUiI:b3u7q5w) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L33)):*
> ```Go
> 	assert.NoError(t, err)
> 
> 	flag.Set("localPort", strconv.Itoa(availablePort))
> ```

this says to me something isn't taking appropriate constructor arguments. having to set a flag to change an instantiation argument is a code smell.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by kaloyan-raev** [comment]
Review status: all files reviewed, 7 unresolved discussions (waiting on @jtolds and @bryanchriswhite)

---

*[pkg/overlay/service_test.go, line 94 at r3](https://reviewable.io/reviews/storj/storj/94#-LFID2oE8HV4Hsa1aK71:-LFID2oE8HV4Hsa1aK72:bvexl75) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L94)):*
> ```Go
> 		defer func() {
> 			if err := os.Remove(boltdbPath); err != nil {
> 				log.Printf("%s\n", errs.New("error while removing test bolt db: %s", err))
> ```

`log.Println` looks like a better fit here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by bryanchriswhite** [comment]
Review status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @bryanchriswhite)

---

*[pkg/overlay/service_test.go, line 33 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI9RRZ6iZlKkeOtUiH:-LFIITsdCZJqw_KRun83:bu6onqw) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L33)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

this says to me something isn't taking appropriate constructor arguments. having to set a flag to change an instantiation argument is a code smell.
</blockquote></details>

I'm not sure i follow here but instead of doing this, I've in-lined the `localPort` flag setting with the rest of the individual `flag.Set`s. After removing ports.go there was not enough common behavior to pull into a function like this.

---

*[internal/test/port.go, line 1 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8He07kK5bOcU_w8M:-LFIH19L-FIJ3xQJvJm5:bt5njtd) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L1)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

copyright
</blockquote></details>

port.go was copied from a gist but based on your other feedback I've realized i didn't need it.

---

*[internal/test/port.go, line 17 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8L93DbEx6KkoPc8S:-LFIHNIY2pYh1JC6LmFX:b-896fix) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L17)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

you don't need to leave this comment, lol. i prefer

```
server, err := net.Listen("tcp", ":0")
if err != nil { 
  return 0, err
}
```
</blockquote></details>

Done.

---

*[internal/test/port.go, line 35 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI8pGA0JgIZmpBxGnQ:-LFIHNoD8dxdW3RelVtJ:b-896fix) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L35)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

overall, this function is racy. if this listen succeeds and chooses a port, the minute you return and close the listener, the port may get grabbed by something else and the assumption the port is free is no longer true. it is generally the case that ports are allocated sequentially so this is a minor issue, but why use this function at all? could you instead just use Listen("tcp", ":0") at the location you need a port instead?
</blockquote></details>

Done.

---

*[internal/test/port.go, line 39 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI9IiCDpjVYaqKfKlv:-LFIHOC4BYTGfxq7osBz:b-896fix) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/internal/test/port.go#L39)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

same overall feedback. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by bryanchriswhite** [comment]
Review status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @kaloyan-raev)

---

*[pkg/overlay/service_test.go, line 94 at r3](https://reviewable.io/reviews/storj/storj/94#-LFID2oE8HV4Hsa1aK71:-LFIKaW-B-cfkwKWVuQH:b-896fix) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L94)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

`log.Println` looks like a better fit here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by coyle** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 7 unresolved discussions (waiting on @jtolds and @kaloyan-raev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by jtolds** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @kaloyan-raev)

---

*[pkg/overlay/service_test.go, line 33 at r3](https://reviewable.io/reviews/storj/storj/94#-LFI9RRZ6iZlKkeOtUiH:-LFQZy827jE0vRTf1bnG:bhw6bua) ([raw file](https://github.com/storj/storj/blob/fe67a7edf143f921e5dc3c4d9a5cbbe43d7813cc/pkg/overlay/service_test.go#L33)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

I'm not sure i follow here but instead of doing this, I've in-lined the `localPort` flag setting with the rest of the individual `flag.Set`s. After removing ports.go there was not enough common behavior to pull into a function like this.
</blockquote></details>

okay so my main comment is that if tests have to use flag.Set at all, then that smells like something should be passed in to a constructor instead of using a flag. i mean i get it, sometimes tests should test flag behavior, but in general, tests shouldn't need to set flags to test other behavior

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94)*

**Comment by coyle** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/94#-:-LFSaC6J6vXjuE3GrZ7D:bnfp4nl)*

**Pull request merged**
