### PR TITLE
db: set max idle connections higher to avoid redialing all the time

### PR DESCRIPTION
**Pull request by egonelbre**
Currently we are opening and closing database connections all the time. Set the MaxIdleConns = 100.

Using benchmark from https://github.com/storj/storj/pull/1968 and adjusted for parallel.

```
// max idle = 100
BenchmarkOverlay/KnownUnreliableOrOffline-8               10000            120700 ns/op
BenchmarkOverlay/UpdateAddress-8                          10000            156453 ns/op
BenchmarkOverlay/UpdateStats-8                            10000            159600 ns/op
BenchmarkOverlay/UpdateNodeInfo-8                         10000             88152 ns/op
BenchmarkOverlay/UpdateUptime-8                           10000            153208 ns/op

// max idle = 2 (default)
BenchmarkOverlay/KnownUnreliableOrOffline-8               10000            166000 ns/op
BenchmarkOverlay/UpdateAddress-8                          10000            394842 ns/op
BenchmarkOverlay/UpdateStats-8                            10000            521502 ns/op
BenchmarkOverlay/UpdateNodeInfo-8                         10000            339348 ns/op
BenchmarkOverlay/UpdateUptime-8                           10000            548532 ns/op
```

For uploading 2GB of data to storj-sim by using database connection debugging log https://github.com/storj/storj/pull/1989:
```
// max idle = 100
conns opened = 15
conns alive  = 15
conns closed = 0

// max idle = 2
conns opened = 1984
conns alive  = 5
conns closed = 1979 
```

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by egonelbre** [comment]
Note: needs proper benchmarking before merging.

**Comment by thepaul** [comment]
This looks like a massive win. Should we also take the opportunity to consolidate the different places where we open db connections so that this change is always applied if we add more?

**Comment by egonelbre** [comment]
@thepaul nothing against consolidating this stuff, but might be better for a separate PR, because I suspect that will take some time to move things into the right place.

**Comment by thepaul** [comment]
Fair enough. I'll do some additional benchmarking.

**Pull request merged**
