### PR TITLE
updates the refresh interval in captplanet test script

### PR DESCRIPTION
**Pull request by dylanlott**
updates the refresh interval in the captplanet script to make it work. 3s refresh interval wasn't working on my local machine.

### CODE REVIEW

**Comment by dylanlott** [comment]
> Use early run as in https://github.com/storj/storj/blob/master/pkg/audit/service.go#L86 to avoid the need to change the sleep.

The sleep has been removed, it was a leftover from testing, but it wasn't necessary. Only the interval changes are in there now.

**Comment by egonelbre** [comment]
I mean it should also work with an interval of 30s, if it doesn't there probably is a bug somewhere.

**Comment by coyle** [comment]
The issue is the cache has an unimplemented Bootstrap method. So the only way to populate the cache is via refresh.

**Comment by coyle** [comment]
Bootstrap is being worked on now but until then this fixes it from not working locally for people.

**Pull request merged**
