### PR TITLE
lib/uplinkc: make .so smaller

### PR DESCRIPTION
**Pull request by aleitner**
What: Make the libuplink shared object smaller. Omit the DWARF symbol table and omit the symbol table and debug information when building the .so

Why: Our shared object is many megabytes too big.

### CODE REVIEW

**Comment by JessicaGreben** [comment]
how much does this change the size?

**Comment by aleitner** [comment]
> how much does this change the size?

22mb -> 16mb

**Comment by JessicaGreben** [comment]
nice!

**Comment by mniewrzal** [comment]
Linux (fedora): 24.8mb -> 19.8mb

**Pull request merged**
