### PR TITLE
storagenode/piecestore: log piece size on upload

### PR DESCRIPTION
**Pull request by iAmGroute**
What: Show the piece size in the existing log entries when an upload completes/fails.

Why: This will allow SNOs to get more accurate metrics on their node's performance out of the log file. For example, an upload cancellation/failure rate can be calculated based on total size and not just number of uploads.

Please describe the tests: n/a
 - Test 1:
 - Test 2:
 
Please describe the performance impact: negligible

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by iAmGroute** [comment]
Is the CLA really needed, considering the changes are trivial?

**Comment by ifraixedes** [comment]
> Is the CLA really needed, considering the changes are trivial?
Yes, it's.

**Review by ifraixedes — APPROVED** [review]

**Review by littleskunk — APPROVED** [review]

**Comment by stefanbenten** [comment]
Hey @iAmGroute ,
do you intend to sign the CLA? We are really looking forward to your contribution!

**Comment by iAmGroute** [comment]
I'd rather not sign it. It requires personal info I'm not really keen on giving. Especially for a trivial contribution like this, I don't care about the copyright and don't think it even applies. Anyway, should I close the pull request or should you close it ? You can then redo the changes manually or not add them at all, it's not that important.

**Comment by ifraixedes** [comment]
> I'd rather not sign it. It requires personal info I'm not really keen on giving. Especially for a trivial contribution like this, I don't care about the copyright and don't think it even applies.

This is a personal opinion, not one from Storj.
I'm not a lawyer, so no idea if because of these minimal changes it's required or not, however, I expect that it's :cry: . I understand your feelings, I think that this is how the world has been f*** up because of past lawsuits where big corporates didn't want to play fairly.

> Anyway, should I close the pull request or should you close it ? You can then redo the changes manually or not add them at all, it's not that important.

I will replay your changes, so even we cannot attribute the contribution of them to you, at least, you'll be able to get the enhancement in a near-future release.

**Comment by ifraixedes** [comment]
Closed in favor of https://review.dev.storj.io/c/storj/storj/+/3496

**Pull request closed without merging**
