### PR TITLE
Mirroring

### PR DESCRIPTION
**Pull request by Barterio**
Initial Commit for Mirroring service

### CODE REVIEW

**Comment by egonelbre** [comment]
I think this would be better off as a separate repo, rather than in the core.

**Comment by jtolds** [comment]
heh, i asked them to pull it in, so that it will be easier to have this package depend on bucketstore once we're ready for that. i can go either way though

**Comment by jtolds** [comment]
okay, I relent. sorry @Barterio, let's do another repo. do you want me to make another repo for you?

**Comment by Barterio** [comment]
Hey, @jtolds, can you create a separate repository for us?

We choose name for mirroring service as "Erised"

This is a reference to the magic mirror (mirror - due to Mirroring service) from Harry Potter universe, called Mirror of Erised. It appears in the first book (and in the film).

Erised - its desire, but reversed.

**Comment by egonelbre** [comment]
I went ahead and created one https://github.com/storj/erised

**Comment by jtolds** [comment]
@egonelbre we're worried about legality. don't want to upset the estate of one of England's richest authors. i gave @barterio some other options

**Comment by jtolds** [comment]
https://github.com/storj/ditto is set up!

**Pull request closed without merging**
