### PR TITLE
releases: update alpha dockerfiles to embed release tags

### PR DESCRIPTION
**Pull request by jtolds**
WIP: where do the arm binaries get built?

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
I build ARM binaries in a Ubuntu VM where I have the necessary ARM cross-compile tooling installed.

**Comment by jtolds** [comment]
@kaloyan-raev right but is there a place i can update the go build command you run? it needs to change like the amd64 one here

**Comment by kaloyan-raev** [comment]
I updated the build command I execute on that VM. You can check the result on quay.io if you want.

**Comment by jtolds** [comment]
it would be nice to have in source control eventually

**Comment by kaloyan-raev** [comment]
My assumption has been that it is a very temporary solution. But if we put this in the version control, we need to find how to setup the build environment.

**Comment by jtolds** [comment]
okay that's fair

**Pull request closed without merging**
