### PR TITLE
Fix URL parsing exception for storagenode/trust test case 

### PR DESCRIPTION
**Pull request by tomhb**
What: 
Unit tests failing for storagenode/trust

=== RUN   TestHTTPSourceNew/not_a_valid_URL
    TestHTTPSourceNew/not_a_valid_URL: http_source_test.go:54: 
        	Error Trace:	http_source_test.go:54
        	Error:      	Error message not equal:
        	            	expected: "HTTP source: \"://\": not a URL: parse ://: missing protocol scheme"
        	            	actual  : "HTTP source: \"://\": not a URL: parse \"://\": missing protocol scheme"
        	Test:       	TestHTTPSourceNew/not_a_valid_URL

Changed test to match exception.

Why:
Unit test are failing on master due to string format mismatch.

Please describe the tests:
 - Test 1:   go test -v ./storagenode/trust/
 
Please describe the performance impact:
None - updating unit test 

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by tomhb** [comment]
This update breaks the jenkins build, I will do some more investigation.

**Comment by egonelbre** [comment]
@tomhb there's a difference how go 1.13 and go 1.14 so this fix would need to have a list of errors that err needs to match.

**Comment by wthorp** [comment]
Or just removed the double quotes and have a single test

**Comment by egonelbre** [comment]
We fixed this in https://github.com/storj/storj/commit/a9fb7b7694795ec9c4508a0dc8d4c96761c7edfc

**Comment by tomhb** [comment]
@egonelbre thanks! This went a bit above my golang skills.

**Pull request closed without merging**
