### PR TITLE
Implement psclient interface

### PR DESCRIPTION
**Pull request by aleitner**
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/107)

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @aleitner)

---

*[examples/piecestore/rpc/client/main.go, line 36 at r1](https://reviewable.io/reviews/storj/storj/107#-LFalexWB0M2HdcHACX2:-LFalexWB0M2HdcHACX3:b-zfn22u) ([raw file](https://github.com/storj/storj/blob/0ef3ae5e054e40e30d89fbdbfd683762782da98c/examples/piecestore/rpc/client/main.go#L36)):*
> ```Go
> 	}
> 	defer conn.Close()
> 	routeClient := client.NewPSClient(conn)
> ```

This var should be renamed too.

---

*[examples/piecestore/rpc/client/main.go, line 65 at r1](https://reviewable.io/reviews/storj/storj/107#-LFakHH0BzgIaKLEBnGP:-LFakHH0BzgIaKLEBnGQ:b-6l97ae) ([raw file](https://github.com/storj/storj/blob/0ef3ae5e054e40e30d89fbdbfd683762782da98c/examples/piecestore/rpc/client/main.go#L65)):*
> ```Go
> 
> 				var length = fileInfo.Size()
> 				var ttl = time.Now().Add(time.Second * 86400)
> ```

Is this 1 day? Using `24 * time.Hour` would make it clearer.

---

*[pkg/piecestore/rpc/client/client.go, line 31 at r1](https://reviewable.io/reviews/storj/storj/107#-LFakXzK24bVU1JyAtfm:-LFakXzK24bVU1JyAtfn:b255lzv) ([raw file](https://github.com/storj/storj/blob/0ef3ae5e054e40e30d89fbdbfd683762782da98c/pkg/piecestore/rpc/client/client.go#L31)):*
> ```Go
> }
> 
> // NewPSClient -- Initilize Client
> ```

It's a good time to start following the convention for doc comments and make them read like a sentence: https://blog.golang.org/godoc-documenting-go-code

---

*[pkg/piecestore/rpc/client/client.go, line 32 at r1](https://reviewable.io/reviews/storj/storj/107#-LFakweY-y3SVSZ3z0To:-LFakweY-y3SVSZ3z0Tp:bccjryu) ([raw file](https://github.com/storj/storj/blob/0ef3ae5e054e40e30d89fbdbfd683762782da98c/pkg/piecestore/rpc/client/client.go#L32)):*
> ```Go
> 
> // NewPSClient -- Initilize Client
> func NewPSClient(conn *grpc.ClientConn) *Client {
> ```

This should return the PSClient interface. BTW, where do you define the interface? I don't see it in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[cmd/piecestore-cli/main.go, line 44 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvT8yD24tQHYNNrbyg:-LFvT8yD24tQHYNNrbyh:bf5otfe) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L44)):*
> ```Go
> 				id := c.Args().Get(0)
> 
> 				if c.Args().Get(0) == "" {
> ```

Arg 0 is the id, no? Should you check for `c.Args().Get(1)` here?

---

*[cmd/piecestore-cli/main.go, line 48 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvTOCF9RUY3f7ncxp7:-LFvTOCF9RUY3f7ncxp8:b-z1owv1) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L48)):*
> ```Go
> 				}
> 
> 				if c.Args().Get(1) == "" {
> ```

`c.Args().Get(2)` to check for output dir param?

---

*[cmd/piecestore-cli/main.go, line 52 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvTera1g57Bw5RbSfw:-LFvTera1g57Bw5RbSfx:b-l1ytfi) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L52)):*
> ```Go
> 				}
> 
> 				file, err := os.Open(c.Args().Get(0))
> ```

`c.Args().Get(1)` for input file?

---

*[cmd/piecestore-cli/main.go, line 60 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvTmBm5SwjmUxxagcK:-LFvTmBm5SwjmUxxagcL:b-l1ytfi) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L60)):*
> ```Go
> 				defer file.Close()
> 
> 				fileInfo, err := os.Stat(c.Args().Get(0))
> ```

`c.Args().Get(1)` for input file?

---

*[cmd/piecestore-cli/main.go, line 66 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvTo4iBkliiZ88XTa2:-LFvTo4iBkliiZ88XTa3:b-l1ytfi) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L66)):*
> ```Go
> 
> 				if fileInfo.IsDir() {
> 					return argError.New(fmt.Sprintf("Path (%s) is a directory, not a file", c.Args().Get(0)))
> ```

`c.Args().Get(1)` for input file?

---

*[cmd/piecestore-cli/main.go, line 69 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvTpPVBElMijOI3q5l:-LFvTpPVBElMijOI3q5m:b-k76ejd) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L69)):*
> ```Go
> 				}
> 
> 				dataFileChunk, err := pstore.StoreWriter(id, c.Args().Get(1))
> ```

`c.Args().Get(2)` for output dir?

---

*[cmd/piecestore-cli/main.go, line 89 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvURZNBJQwP9p08Fmd:-LFvURZNBJQwP9p08Fme:b-vw5pyr) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L89)):*
> ```Go
> 			Action: func(c *cli.Context) error {
> 				if c.Args().Get(0) == "" {
> 					return argError.New("Missing data id")
> ```

It would be nice to have consistent error messages between the different commands. In the `store` command you have 'No id specified' for the same missing argument.

Perhaps you can use error variables, i.e. ErrNoId, ErrNoInputFile, ErrNoOutputDir, etc.

---

*[pkg/piecestore/rpc/client/client.go, line 15 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvVrny6f9mwkuicaDz:-LFvVrny6f9mwkuicaE-:b-f72k1t) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L15)):*
> ```Go
> 	"golang.org/x/net/context"
> 	"google.golang.org/grpc"
> ```

No empty line here.

---

*[pkg/piecestore/rpc/client/client.go, line 23 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvauksCh8zIIreNlsF:-LFvauksCh8zIIreNlsG:bcb0rzj) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L23)):*
> ```Go
> type PSClient interface {
> 	Meta(ctx context.Context, id PieceID) (*pb.PieceSummary, error)
> 	Put(ctx context.Context, id PieceID, ttl time.Time) (io.WriteCloser, error)
> ```

This method should be `Put(ctx context.Context, pieceID PieceID, data io.Reader, expiration time.Time) error`, i.e. it should take a Reader instead of returning a WriteCloser. The Get method of all interfaces above the stack (ECClient, SegmentStore, StreamStore, ObjectStore) have similar signature.

---

*[pkg/piecestore/rpc/client/client.go, line 24 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvaHBk2hFET4NleYwY:-LFvaHBm1pWnzqvOnFsO:b-xh2wyv) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L24)):*
> ```Go
> 	Meta(ctx context.Context, id PieceID) (*pb.PieceSummary, error)
> 	Put(ctx context.Context, id PieceID, ttl time.Time) (io.WriteCloser, error)
> 	Get(ctx context.Context, id PieceID, offset, length int64) (io.ReadCloser, error)
> ```

This method should be `Get(ctx context.Context, pieceID PieceID, size int64) (ranger.RangeCloser, error)`, i.e. it should return RangeCloser instead of ReadCloser. You can take the GRPCRanger from the ranger package and move it here (perhaps also rename it to PieceRanger) to provide this functionality.

---

*[pkg/piecestore/rpc/client/client.go, line 32 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvYP3B6W2SsWTWt2jZ:-LFvYP3B6W2SsWTWt2j_:bosgdjb) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L32)):*
> ```Go
> 
> // IDLength -- Minimum ID length
> const IDLength = 20
> ```

As PieceID is now a type, you can encapsulate this in an `IsValid` method, which would check that `len(id) >= 20`.

---

*[pkg/piecestore/rpc/client/client.go, line 96 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvXuPy-aiphKY2Yytb:-LFvXuPy-aiphKY2Yytc:bvrsbe1) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L96)):*
> ```Go
> 
> // DetermineID creates random id
> func DetermineID() PieceID {
> ```

`NewPieceID` sounds like a better name.

Perhaps you can move this function up next to the PieceID definition as it is closely related.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by coyle** [comment]
Review status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[cmd/piecestore-cli/main.go, line 44 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvT8yD24tQHYNNrbyg:-LFwQlGt13tnwtd6HL3R:b-596t3a) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L44)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

Arg 0 is the id, no? Should you check for `c.Args().Get(1)` here?
</blockquote></details>

maybe instead of `0` or `1` we have consts defined like:
```
const (
    id int = iota
    inputFile
    outputDir
)

if c.Args().Get(id) == "" {
    ...
}
```

---

*[pkg/piecestore/rpc/client/client.go, line 101 at r2](https://reviewable.io/reviews/storj/storj/107#-LFwRweKEXzAZZ--2MNK:-LFwRweKEXzAZZ--2MNL:b-rkvfrt) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L101)):*
> ```Go
> 	_, err := rand.Read(b)
> 	if err != nil {
> 		panic(err)
> ```

you shouldn't panic but handle the error

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[cmd/piecestore-cli/main.go, line 44 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvT8yD24tQHYNNrbyg:-LFwev-e4uTjOD_8edrl:b-rlob0d) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L44)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

maybe instead of `0` or `1` we have consts defined like:
```
const (
    id int = iota
    inputFile
    outputDir
)

if c.Args().Get(id) == "" {
    ...
}
```
</blockquote></details>

I like this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[pkg/piecestore/rpc/client/pieceranger.go, line 26 at r3](https://reviewable.io/reviews/storj/storj/107#-LG0q9i1C2qs2PJao7Ne:-LG0q9i1C2qs2PJao7Nf:b-y86vpg) ([raw file](https://github.com/storj/storj/blob/270aef86bdff1bb389cd8b9137d0bd3c1778c080/pkg/piecestore/rpc/client/pieceranger.go#L26)):*
> ```Go
> }
> 
> // PieceRanger turns a gRPC connection to piece store into a Ranger
> ```

This doc comment is outdated and not accurate at the moment. It should say something like: "PieceRanger returns a RangeCloser from a PieceID."

---

*[pkg/piecestore/rpc/client/pieceranger.go, line 27 at r3](https://reviewable.io/reviews/storj/storj/107#-LG0ppKc0sMVUFu_HyHJ:-LG0ppKc0sMVUFu_HyHK:bk6nyss) ([raw file](https://github.com/storj/storj/blob/270aef86bdff1bb389cd8b9137d0bd3c1778c080/pkg/piecestore/rpc/client/pieceranger.go#L27)):*
> ```Go
> 
> // PieceRanger turns a gRPC connection to piece store into a Ranger
> func PieceRanger(ctx context.Context, c *Client, id PieceID) (ranger.RangeCloser, error) {
> ```

I think from API point of view it would be better if the constructor takes PSClient instead of *Client. This way API users will be able to create a PieceRanger by having a PSClient and a PieceID.

---

*[pkg/piecestore/rpc/client/pieceranger.go, line 38 at r3](https://reviewable.io/reviews/storj/storj/107#-LG0rEA519B8YskQWh_F:-LG0rEA519B8YskQWh_G:b-fcy5nv) ([raw file](https://github.com/storj/storj/blob/270aef86bdff1bb389cd8b9137d0bd3c1778c080/pkg/piecestore/rpc/client/pieceranger.go#L38)):*
> ```Go
> // Use it if you know the piece size. This will safe the extra request for
> // retrieving the piece size from the piece storage.
> func PieceRangerSize(c *Client, id PieceID, size int64) ranger.RangeCloser {
> ```

PSClient here too instead of *Client.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[pkg/piecestore/rpc/client/client.go, line 15 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvVrny6f9mwkuicaDz:-LG0t2Us4PoWAXmPlcxu:b-1ljzha) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L15)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

No empty line here.
</blockquote></details>

Hmm, you added another empty line. This is not what I meant. I meant there should be no new line between:

"golang.org/x/net/context"
"google.golang.org/grpc"
"github.com/mr-tron/base58/base58"

All they are in the 3rd party pkgs group. We put empty lines only between groups. There are 3 groups total: bultin, 3rd party, storj.io.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
Review status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[pkg/piecestore/rpc/client/pieceranger.go, line 27 at r3](https://reviewable.io/reviews/storj/storj/107#-LG0ppKc0sMVUFu_HyHJ:-LG0zJsJ28dkPWASJG5g:b-sy3o99) ([raw file](https://github.com/storj/storj/blob/270aef86bdff1bb389cd8b9137d0bd3c1778c080/pkg/piecestore/rpc/client/pieceranger.go#L27)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

I think from API point of view it would be better if the constructor takes PSClient instead of *Client. This way API users will be able to create a PieceRanger by having a PSClient and a PieceID.
</blockquote></details>

Alex, sorry for the above. I forgot the PieceRanger needs access to the client's route and this is only possible if it has a reference to the implementation. If someone needs a PieceRanger, he should call PSClient.Get, no the PieceRanger constructor.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by coyle** [comment]
Review status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @kaloyan-raev, @aleitner, and @coyle)

---

*[pkg/piecestore/rpc/client/client.go, line 101 at r2](https://reviewable.io/reviews/storj/storj/107#-LFwRweKEXzAZZ--2MNK:-LG1RusyDxr1qb5Sw2ks:b-vuyv0s) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L101)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

you shouldn't panic but handle the error
</blockquote></details>

After talking in person, reasonable to leave this for now since this will be changing soon and something would need to go horribly wrong for this to error

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by aleitner** [comment]
Review status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @kaloyan-raev and @aleitner)

---

*[pkg/piecestore/rpc/client/client.go, line 101 at r2](https://reviewable.io/reviews/storj/storj/107#-LFwRweKEXzAZZ--2MNK:-LG1TZ40BkJQ1xSGpquE:b-tch5zw) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/pkg/piecestore/rpc/client/client.go#L101)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

After talking in person, reasonable to leave this for now since this will be changing soon and something would need to go horribly wrong for this to error
</blockquote></details>

We're leaving the panic in. If read fails then there is something wrong with your computer

---

*[cmd/piecestore-cli/main.go, line 89 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvURZNBJQwP9p08Fmd:-LG1TSigB0FFi0TgCuKk:b-896fix) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L89)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

It would be nice to have consistent error messages between the different commands. In the `store` command you have 'No id specified' for the same missing argument.

Perhaps you can use error variables, i.e. ErrNoId, ErrNoInputFile, ErrNoOutputDir, etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by aleitner** [comment]
Review status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @kaloyan-raev and @coyle)

---

*[pkg/piecestore/rpc/client/client.go, line 31 at r1](https://reviewable.io/reviews/storj/storj/107#-LFakXzK24bVU1JyAtfm:-LG1WNN_101F2g0N2jdx:b-896fix) ([raw file](https://github.com/storj/storj/blob/0ef3ae5e054e40e30d89fbdbfd683762782da98c/pkg/piecestore/rpc/client/client.go#L31)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

It's a good time to start following the convention for doc comments and make them read like a sentence: https://blog.golang.org/godoc-documenting-go-code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by aleitner** [comment]
Review status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @kaloyan-raev and @coyle)

---

*[cmd/piecestore-cli/main.go, line 89 at r2](https://reviewable.io/reviews/storj/storj/107#-LFvURZNBJQwP9p08Fmd:-LG1WTdF4UMBzMty4RQr:b-uacuje) ([raw file](https://github.com/storj/storj/blob/41afc4c1faf2a406e565ed3c45044eee6d39dd40/cmd/piecestore-cli/main.go#L89)):*
<details><summary><i>Previously, aleitner (Alexander Leitner) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not adding errors since it is an example

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by coyle** [comment]
Reviewed 2 of 6 files at r2, 1 of 6 files at r3, 3 of 4 files at r4, 1 of 2 files at r5.
Review status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by coyle** [comment]
Reviewed 1 of 6 files at r3, 1 of 2 files at r5.
Review status: all files reviewed, 2 unresolved discussions (waiting on @kaloyan-raev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107)*

**Comment by kaloyan-raev** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/107#-:-LG1YDuq4HyHxs-5sVUb:bnfp4nl)*

**Pull request merged**
