### PR TITLE
Fix typo in sender

### PR DESCRIPTION
**Pull request by nerdatwork**
There is a typo in sender.go

### CODE REVIEW

**Comment by stefanbenten** [comment]
Hey @nerdatwork !
You have to sign our CLA and in addition your commit is not done with a proper Github Identity.
Could you please check both?

**Comment by nerdatwork** [comment]
@cla-bot check:

**Comment by stefanbenten** [comment]
@nerdatwork It looks like your commit that you made was pushed with the wrong name. I think the best way to get around this problem is to close this PR and open an new one, with the correct git settings on your machine, or even easier, make the change directly from the Web Browser.

**Comment by stefanbenten** [comment]
Also i noticed, that you did not sign the CLA yet, which is available here:
https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform

**Pull request closed without merging**
