### PR TITLE
satellite/analytics: Track event "Credit Card Added"

### PR DESCRIPTION
**Pull request by prerna-parashar**
Added code to track event "Credit Card Added" and send it to segment.io to understand when user becomes a "PRO" account.

### CODE REVIEW

**Comment by ifraixedes** [comment]
I'm wondering why we track that a credit card is added when the user's account become pro and not just track an event specifically for that. I would see clearly that event rather than having to know that we only track "card added" when the user's account becomes pro.

**Comment by prerna-parashar** [comment]
> I'm wondering why we track that a credit card is added when the user's account become pro and not just track an event specifically for that. I would see clearly that event rather than having to know that we only track "card added" when the user's account becomes pro.

@ifraixedes is there a possibility of user stays in free tier even after adding a credit card? I am assuming user automatically upgrades to PRO account after adding a credit card.

**Comment by prerna-parashar** [comment]
> @prerna-parashar the user should always move to paid tier after adding a credit card the first time. My question is what are you trying to track?
> 
> * they added a card
> * they moved from free tier -> paid tier
> * both
> 
> If they have already added a card and are in paid tier now, do we still want to track if they added a second card? If they added multiple cards, do we want to separately know when they transitioned from free tier to paid tier?

Actually I am trying to track both, I am planning to create a workflow in HubSpot which will set a user property "Pro Account" to "Yes" if not already whenever user has a trigger event "Credit Card Added". I will also update this property for the existing users in HubSpot.

**Comment by mobyvb** [comment]
So is there a problem with having an event such as "entered paid tier", and in Hubspot you can have the same kind of workflow in Hubspot? Basically, I am curious if you also need to know about if the user added a credit card for any reason other than to put them in the paid tier.
If I already have a card added, and I am already in paid tier, and Hubspot already knows this, do you still want another "card added" event if I add a second credit card?

**Comment by prerna-parashar** [comment]
> So is there a problem with having an event such as "entered paid tier", and in Hubspot you can have the same kind of workflow in Hubspot? Basically, I am curious if you also need to know about if the user added a credit card for any reason other than to put them in the paid tier.
> If I already have a card added, and I am already in paid tier, and Hubspot already knows this, do you still want another "card added" event if I add a second credit card?

I think @stoweandi would be best to clarify this. If she doesn't want to have a credit card event other than to know when a user becomes a PRO account, then I will change the name of the event to "entered paid tier" otherwise I can just replace the event code outside the paid tier checkbox.

**Comment by prerna-parashar** [comment]
> > So is there a problem with having an event such as "entered paid tier", and in Hubspot you can have the same kind of workflow in Hubspot? Basically, I am curious if you also need to know about if the user added a credit card for any reason other than to put them in the paid tier.
> > If I already have a card added, and I am already in paid tier, and Hubspot already knows this, do you still want another "card added" event if I add a second credit card?
> 
> I think @stoweandi would be best to clarify this. If we don't want to have a credit card event other than to know when a user becomes a PRO account, then I will change the name of the event to "entered paid tier" otherwise I can just replace the event code outside the paid tier checkbox.

@mobyvb I have moved the code outside the paid tier checkbox to be able to send event every time card is added.

**Comment by mobyvb** [comment]
@prerna-parashar I think it is fine either way. However, if it is inside the `if !auth.User.PaidTier {`, I just think it should be called something other than "credit card added". Such as "entered paid tier".

**Review by mobyvb — APPROVED** [review]

**Comment by ifraixedes** [comment]
> @prerna-parashar I think it is fine either way. However, if it is inside the if !auth.User.PaidTier {, I just think it should be called something other than "credit card added". Such as "entered paid tier".

My comment was in this direction.

**Pull request merged**
