### PR TITLE
Delete old psserver

### PR DESCRIPTION
**Pull request by egonelbre**
What: remove old psserver from the system

Why: By now storage nodes should have sent all their agreements to satellite. So we can remove the old system completely.

Note, this still needs some other code cleanup, but making this as minimal as possible.

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
I am a little bit confused to have both:
- /storagenode/piecestore
- /storagenode/psserver

Doesn't it make sense to have them all under /storagenode/piecestore?

**Comment by egonelbre** [comment]
Yeah, I would rename `psserver` to `oldpsserver` or something, but that would cause more changes in code - so more conflicts. However, since it's going to be deprecated soon anyways, I think we can manage the confusion for now.

**Comment by kaloyan-raev** [comment]
If we are going to delete it soon, why bothering of moving it at all?

**Comment by egonelbre** [comment]
@kaloyan-raev yeah, just started wondering whether we could remove it now instead.

**Pull request merged**
