### PR TITLE
web/satellite: Fix social media sharing links

### PR DESCRIPTION
**Pull request by nerdatwork**
Currently the title or text for a shared file is not visible on some of the social media websites.
1. Reddit

image

2. Twitter

image

3. Hacker News

image

4. Linkedin
image

5. Telegram
image

### CODE REVIEW

**Review by mobyvb — APPROVED** [review]

**Review by VitaliiShpital — APPROVED** [review]

**Comment by stefanbenten** [comment]
@nerdatwork Do you mind revisiting this and resolving the conflicts?
I am sorry that this has not been merged previously.

**Comment by nerdatwork** [comment]
Hi @stefanbenten  I have no idea how to proceed as this is my first time dealing with github conflict. A google search showed a nice `Resolve conflicts` button which is not seen on my end. I would very much appreciate your help in this regard.

image

**Comment by stefanbenten** [comment]
@nerdatwork The conflict does seem to be a little more tricky to resolve, hence it is necessary to do it via the CLI.
If you want to try that locally that is probably also a good learning experience :) Else i can look into resolving the conflict.

**Comment by nerdatwork** [comment]
I will try my best. Thank you.

**Comment by nerdatwork** [comment]
I don't have a local copy as I edited the file on github. I have tried different things but I couldn't access my branch `nerdatwork:patch-1`. I had deleted my branch after `nerdatwork:patch-2` was merged.

I have stumbled upon `rebase` but I have no clue on how to move ahead with it. Can you please guide me on how to proceed ?

**Comment by mobyvb** [comment]
@nerdatwork there are two ways you can approach it - with and without rebase
* without rebase (this is probably easier on Github)
```
git pull origin main
```
then you will need to resolve you conflicts. They will look like this in the files that have them
```
<<<<<<< HEAD
conflicting changes from main
=======
conflicting changes on your branch
>>>>>>> your_branch
```
after all the conflicts are resolved (and you remove the `<<<`, `===`, and `>>>` lines), you should be able to add the files and do something like `git commit -m 'merge main'`, and `git push nerdatwork patch-1` 
* with rebase
This is very similar, but conceptually, it is kind of the opposite. Rather than putting the `main` changes on top, rebase will temporarily remove your changes, then put new commits from `main` in, and finally try to merge your changes into the branch. You can initiate this by running `git pull --rebase origin main`. If you mess up and need to start over, you can always do `git rebase --abort`. Because rebase kind of works the opposite way of a regular merge, your conflicts will be flipped too, like this:
```
<<<<<<< HEAD
conflicting changes on your branch
=======
conflicting changes from main
>>>>>>> your_branch
```
After you resolve conflicts, you can add the files, as if you are about to commit, then run `git rebase --continue`. Once the rebase is complete, you can push. Because the git history will have been rewritten, you need to force push. I recommend using `git push --force-with-lease nerdatwork patch-1`

Let me know if you would like clarification on any of this :) I probably didn't cover everything

**Comment by nerdatwork** [comment]
@mobyvb Thank you for that in-depth post. I opted for rebase. I couldn't see any  `<<<`, `===`, and `>>>` lines in the conflicting file. Here is a screenshot of the said commands.

image

**Comment by mobyvb** [comment]
@nerdatwork it may be that you had duplicate changes on your branch that have since been merged into `main`, and when you rebased, these duplicate commits were dropped and you did not need to resolve any conflicts. Since it says currently up to date with the main branch, you should try to push to remote again and see if it works

**Comment by nerdatwork** [comment]
image

What happened here?

**Comment by mobyvb** [comment]
@nerdatwork you need to replace the `nerdatwork` with whatever origin is pointing to your repository at https://github.com/nerdatwork/storj
Most likely, you need to do `git push --force-with-lease origin patch-1`
But you can verify if your `origin` is correct with `git remote -v`
Another thing that this reminded me is that when you pull from `main`, you will need to pull from `main` on github.com/storj/storj, not github.com/nerdatwork/storj, since your origin will not necessarily have the most up to date changes. If you have not done this already, you can add a new origin with `git remote add storj git@github.com:storj/storj.git`. From there, you can pull like `git pull --rebase storj main` rather than `git pull --rebase origin main`, since `origin` is probably using your nerdatwork repo.

**Comment by nerdatwork** [comment]
image

image

image

The following command executed without any error message.
`$ git remote add storj git@github.com:storj/storj.git`

**Comment by mobyvb** [comment]
@nerdatwork in this case, it looks like you already have it added as `upstream`. So you don't need to add the new remote. It looks like the reason it isn't working, by the way, is that I gave you the ssh link to the repository, but you would need to [add an ssh key to Github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to use a remote starting with `git@` rather than `https://`

Anyways, it's not a problem, just try
`git pull --rebase upstream main`

**Comment by nerdatwork** [comment]
image

The conflicting file does not show the markers for conflicts <<<, ===, and >>>

Under `Github desktop` I see the following

image

**Comment by mobyvb** [comment]
@nerdatwork that probably means your rebase completed successfully with no conflicts. You can verify by typing `git log` (use j and k to scroll down and up, and q to quit). If it worked, you should see your commits at the top, and the first commit that is not from you should be the top commit on https://github.com/storj/storj/ - `cmd/uplinkng: rename parallelism flags, small fixes` as of this comment.

You don't need to do that, but just a tip if you want to verify before pushing. You should be able to push now, and if it worked, you shouldn't see the "this branch has conflicts that must be resolved" thing on this page anymore.

**Comment by nerdatwork** [comment]
I don't see my commit at the top

image

**Comment by nerdatwork** [comment]
Updated PR at https://github.com/storj/storj/pull/4321

**Pull request closed without merging**
