### PR TITLE
protos/netstate: remove stuff we're not using

### PR DESCRIPTION
**Pull request by jtolds**
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/100)

### CODE REVIEW

**Comment by navillasa** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @jtolds and @navillasa)

---

*[protos/netstate/netstate.proto, line 7 at r1](https://reviewable.io/reviews/storj/storj/100#-LFNzQTo7mUyqFYFTsIf:-LFNzQTp1_zGGF8c57ej:b-atcl0k) ([raw file](https://github.com/storj/storj/blob/4babb7b95da9599bf545bb112da2582d623368fb/protos/netstate/netstate.proto#L7)):*
> ```protobuf
> package netstate;
> 
> import "google/protobuf/timestamp.proto";
> ```

nice, I could never get this import to work lol

---

*[protos/netstate/netstate.proto, line 55 at r1](https://reviewable.io/reviews/storj/storj/100#-LFNzVR-85nBgnj2umYs:-LFNzVR-85nBgnj2umYt:bwblbci) ([raw file](https://github.com/storj/storj/blob/4babb7b95da9599bf545bb112da2582d623368fb/protos/netstate/netstate.proto#L55)):*
> ```protobuf
>   repeated RemotePiece remote_pieces = 3;
> 
>   bytes merkle_root = 4; // root hash of the hashes of all of these pieces
> ```

why do we still need the merkle root but not the merkle size?

---

*[protos/netstate/netstate.proto, line 68 at r1](https://reviewable.io/reviews/storj/storj/100#-LFNz_yG5aVOHsnDrPjd:-LFNz_yG5aVOHsnDrPje:b-sidiqr) ([raw file](https://github.com/storj/storj/blob/4babb7b95da9599bf545bb112da2582d623368fb/protos/netstate/netstate.proto#L68)):*
> ```protobuf
>   bytes inline_segment = 3;
>   RemoteSegment remote = 4;
>   int64 size = 5;
> ```

will this still be the encrypted_unencrypted_size, but just called "size" now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100)*

**Comment by navillasa** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @jtolds)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100)*

**Comment by navillasa** [comment]
:lgtm:

---

Review status: all files reviewed, 3 unresolved discussions (waiting on @jtolds)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100#-:-LFO--ToAn_zDLPQiPRs:bnfp4nl)*

**Comment by jtolds** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @jtolds)

---

*[protos/netstate/netstate.proto, line 55 at r1](https://reviewable.io/reviews/storj/storj/100#-LFNzVR-85nBgnj2umYs:-LFQZHcW8zANLlHbnpdw:bcoyxv7) ([raw file](https://github.com/storj/storj/blob/4babb7b95da9599bf545bb112da2582d623368fb/protos/netstate/netstate.proto#L55)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

why do we still need the merkle root but not the merkle size?
</blockquote></details>

i convinced myself that the merkle size is something we're actually going to be able to figure out from the data we already have. i might be wrong

---

*[protos/netstate/netstate.proto, line 68 at r1](https://reviewable.io/reviews/storj/storj/100#-LFNz_yG5aVOHsnDrPjd:-LFQZUmfCQYXX_7wfkNt:b-clkrmw) ([raw file](https://github.com/storj/storj/blob/4babb7b95da9599bf545bb112da2582d623368fb/protos/netstate/netstate.proto#L68)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

will this still be the encrypted_unencrypted_size, but just called "size" now?
</blockquote></details>

it's the size of the segment. the segment no longer knows about encryption, so it seemed silly to have that weirdness. encryption (and padding) will happen at a higher layer, so now we don't have to worry about leaking information or keeping details private here. so it's better to just use the size directly

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100)*

**Comment by coyle** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @jtolds and @navillasa)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100#-:-LFwV_qSBpxxCjR3ySbk:bnfp4nl)*

**Comment by navillasa** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @jtolds and @navillasa)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100)*

**Comment by navillasa** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/100#-:-LFwdzWT1EXZRZarwa6y:bnfp4nl)*

**Pull request merged**
