### PR TITLE
storagenode/console: structure service dependencies

### PR DESCRIPTION
**Pull request by rikysya**
What: Structure console service dependencies

Why: Because constructor became too massive

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by rikysya** [comment]
I am don't quite like `console.Storage` as name for struct encapsulating all `DBs` and sources... May be anyone has some better suggestions?

**Comment by egonelbre** [comment]
@rikysya I think the issue with a lot of dependencies could be that a single service tries to do everything. I think there should be a better solution for them.

**Comment by rikysya** [comment]
@egonelbre the only way I can think of to split them up is to differentiate between `dashboard` data, which is not related to concrete `satellite`, and `satellite` specific data into 2 separate services `console/dashboard.Service` and `console/satellite.Service`. Then using them as separate services in `server`, or combine under `console.Service` which is what `server` will use. But I am not sure that it is significantly better approach...

**Comment by rikysya** [comment]
outdated

**Pull request closed without merging**
