### PR TITLE
Improve Node Selection Query

### PR DESCRIPTION
**Pull request by stefanbenten**
What: Remove unnecessary UNION and Selects

Why: Improves Speed
 
Please describe the performance impact: less queries, thus better throughput

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by stefanbenten** [comment]
@BlackDuck888 There you go 👍

**Comment by stefanbenten** [comment]
Query Plan:
image

**Comment by BlackDuck888** [comment]
Let this one open, I step in tomorrow. I thought futher, to reduce one step more.

**Comment by stefanbenten** [comment]
@BlackDuck888 I'll change that now.

**Comment by stefanbenten** [comment]
@BlackDuck888 We cannot further reduce the query, if we merge the last two Select Statements, we are squashing/removing the randomness of nodes within the last_net segment

**Comment by egonelbre** [comment]
It also would be nice to have a benchmark for the improvement.

**Comment by egonelbre** [comment]
@thepaul I think that is fine, since during initial connect, discovery or refresh we should get an IP... so it should rarely happen that a node doesn't have `last_net`.

**Comment by stefanbenten** [comment]
@thepaul I agree with Egon, we definitely have the last_net with any connection now. The only exception are nodes that are on versions before we implemented that change, but they wont be selected anyway.

**Comment by thepaul** [comment]
Oh ok! I missed that we had made that change. Yes, this is great then.

**Comment by stefanbenten** [comment]
As discussed with @BlackDuck888 , we will merge this for now and he opens a nother PR to further improve it!

**Pull request merged**
