### PR TITLE
Avoid extra Range requests for content type detection

### PR DESCRIPTION
**Pull request by kaloyan-raev**
This is another performance improvement for the eestream library when working with http rangers. It's independent from https://github.com/storj/storj/pull/22.

The `ServeContent` function had a premature content type detection. This detection requires check of the first 512 bytes of the content, which led to an additional `Range(0, 4096)` call to each of the farmers.

However, detecting the content type at this point is only useful for processing multi-range requests, which is not the usual use case for content streaming.

This PR moves the content type detection to the code block related to multi-range requests, to avoid the extra `Range` request for the content streaming use case.

Note that the content type will still be properly detected and included in the response at a later moment, just before sending the response to the client: https://github.com/golang/go/blob/master/src/net/http/server.go#L1348

### CODE REVIEW

**Comment by jtolds** [comment]
Okay, so, the content type is still useful to detect for non-multirange requests actually, so I don't thiiink this should move.

I did leave a TODO here (cache this so we don't have to pull it out again) - specifically, for non-multirange requests we should start the full stream and then buffer the header, but the logic required is horrible and complicated.

In the meantime, you could just set the content type to "application/octet-stream" to avoid hitting this codepath?

**Comment by jtolds** [comment]
also, line 113 overwrites all the work you did in the multirange codepath

**Comment by kaloyan-raev** [comment]
The content type for single-range requests will still be detected, but at a later step, yet before sending the response: https://github.com/golang/go/blob/master/src/net/http/server.go#L1348

If I set "application/octet-stream" earlier then the above won't happen.

Alternatively, I can pass a meaningful `name` to the `ServeContent` function (which is not currently the case in the example app). Then the content type will be detected from the file extension, which should be cheap operation. I think this could be feasible approach since the Storj client will have the file name.

**Comment by kaloyan-raev** [comment]
The `ctype` variable is used in the multupart response as the MIME header of each part.

**Comment by jtolds** [comment]
ah right, okay, well, i still think it makes sense to only use the filename for detection when getting the first few bytes are hard.

**Comment by kaloyan-raev** [comment]
`mime.TypeByExtension` is super dumb: https://play.golang.org/p/xm9ab2PjYt3

**Comment by jtolds** [comment]
oh that's aggressively dumb. okay i don't know what to do. what i do know is streaming video is going to almost always hit the multirange path, so we want that path to go fast.

**Comment by kaloyan-raev** [comment]
My observation with VLC so far is that it always sends single-range requests.

Any other software I can check?

**Comment by jtolds** [comment]
Yeah, if you use Chrome and click around, immediately skip to the middle end of the video, it will start off with a full request, then kill the request and start doing byte range requests

**Comment by jtolds** [comment]
it may depend on the video file format you have. depends on where the keyframes are and so on

**Comment by kaloyan-raev** [comment]
@jtolds I tried Chrome too with MKV and MP4 formats, but it still does single-range byte range requests.

When you say "it will start off with a full request, then kill the request and start doing byte range requests", are those single-range or multi-range requests?

Could you share the file you are testing with?

**Comment by jtolds** [comment]
whoops you're totally right, i meant single byte range requests. i misread what you said. okay

**Pull request merged**
