### PR TITLE
storagenode/bandwidthdb: Use existing indexes

### PR DESCRIPTION
**Pull request by littleskunk**
What: Instead of full table scans use the existing indexes.

Why: Because currently, we are stressing the storage nodes with some full table scans.
Old query with full table scan
```
sqlite> .eqp on
sqlite> SELECT action, sum(a) amount from(
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage
   ...> WHERE datetime('2020-10-01') <= datetime(created_at) AND datetime(created_at) <= datetime('2020-11-01')
   ...> GROUP BY action
   ...> UNION ALL
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage_rollups
   ...> WHERE datetime('2020-10-01') <= datetime(interval_start) AND datetime(interval_start) <= datetime('2020-11-01')
   ...> GROUP BY action
   ...> ) GROUP BY action;
QUERY PLAN
|--CO-ROUTINE 2
|  `--COMPOUND QUERY
|     |--LEFT-MOST SUBQUERY
|     |  |--SCAN TABLE bandwidth_usage
|     |  `--USE TEMP B-TREE FOR GROUP BY
|     `--UNION ALL
|        |--SCAN TABLE bandwidth_usage_rollups
|        `--USE TEMP B-TREE FOR GROUP BY
|--SCAN SUBQUERY 2
`--USE TEMP B-TREE FOR GROUP BY
```

New query with an index scan:
```
sqlite> .eqp on
sqlite> SELECT action, sum(a) amount from(
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage
   ...> WHERE '2020-10-01' <= created_at AND created_at <= '2020-11-01'
   ...> GROUP BY action
   ...> UNION ALL
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage_rollups
   ...> WHERE '2020-10-01' <= interval_start AND interval_start <= '2020-11-01'
   ...> GROUP BY action
   ...> ) GROUP BY action;
QUERY PLAN
|--CO-ROUTINE 2
|  `--COMPOUND QUERY
|     |--LEFT-MOST SUBQUERY
|     |  |--SEARCH TABLE bandwidth_usage USING INDEX idx_bandwidth_usage_created (created_at>? AND created_at<?)
|     |  `--USE TEMP B-TREE FOR GROUP BY
|     `--UNION ALL
|        |--SEARCH TABLE bandwidth_usage_rollups USING INDEX sqlite_autoindex_bandwidth_usage_rollups_1 (interval_start>? AND interval_start<?)
|        `--USE TEMP B-TREE FOR GROUP BY
|--SCAN SUBQUERY 2
`--USE TEMP B-TREE FOR GROUP BY
```

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Review by stefanbenten — APPROVED** [review]
LGTM

**Comment by stefanbenten** [comment]
We should discuss a linter/test for this.

**Comment by ReneSmeekes** [comment]
I think the suggested approach casts the columns to text type implicitly for the comparison. It would be better to only remove the type cast on the column and keep it in place on the constant, to ensure a timestamp comparison. This also allows for index usage.

Example
```
sqlite> .eqp on
sqlite> SELECT action, sum(a) amount from(
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage
   ...> WHERE datetime('2020-05-01') <= created_at AND created_at <= datetime('2020-06-01')
   ...> GROUP BY action
   ...> UNION ALL
   ...> SELECT action, sum(amount) a
   ...> FROM bandwidth_usage_rollups
   ...> WHERE datetime('2020-05-01') <= interval_start AND interval_start <= datetime('2020-06-01')
   ...> GROUP BY action
   ...> ) GROUP BY action;
QUERY PLAN
|--CO-ROUTINE 2
|  `--COMPOUND QUERY
|     |--LEFT-MOST SUBQUERY
|     |  |--SEARCH TABLE bandwidth_usage USING INDEX idx_bandwidth_usage_created (created_at>? AND created_at<?)
|     |  `--USE TEMP B-TREE FOR GROUP BY
|     `--UNION ALL
|        |--SEARCH TABLE bandwidth_usage_rollups USING INDEX sqlite_autoindex_bandwidth_usage_rollups_1 (interval_start>? AND interval_start<?)
|        `--USE TEMP B-TREE FOR GROUP BY
|--SCAN SUBQUERY 2
`--USE TEMP B-TREE FOR GROUP BY
1|68009246976
2|3622305536
3|120832
5|4447795200
```

**Comment by littleskunk** [comment]
Ok good point. I have changed it.

**Review by stefanbenten — DISMISSED** [review]

**Review by mobyvb — APPROVED** [review]

**Review by mobyvb — APPROVED** [review]

**Review by stefanbenten — APPROVED** [review]

**Pull request merged**
