### PR TITLE
Cleanup & bolt-backed cache

### PR DESCRIPTION
**Pull request by bryanchriswhite**
see stories [#158259670](https://www.pivotaltracker.com/story/show/158259670) and [#158260077](https://www.pivotaltracker.com/story/show/158260077)

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/87)

### CODE REVIEW

**Comment by coyle** [comment]
Review status: 0 of 17 files reviewed, 9 unresolved discussions (waiting on @bryanchriswhite)

---

*[pkg/netstate/client_test.go, line 29 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_T7gBsDmx4DGlka0:-LEo_T7h4U8BbfA-OV-4:bgqhsxe) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L29)):*
> ```Go
> 	assert.NoError(t, err)
> 
> 	mdb := storage.NewMockStorageClient(map[string][]byte{})
> ```

Is this coming from "storj.io/storj/storage/common" ?

---

*[pkg/netstate/client_test.go, line 74 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_eLW691-2RMZIfhT:-LEo_eLX3xo9AWtqtgG_:b-4501pd) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L74)):*
> ```Go
> 	}
> 
> 	if !bytes.Equal(mdb.Data[string(pr1.Path)], pointerBytes) {
> ```

We should add a method on Pointer to stringify it `pr1.Path()` that returns a string

---

*[pkg/netstate/netstate.go, line 20 at r1](https://reviewable.io/reviews/storj/storj/87#-LEodFwBEPqIKYlqBvxd:-LEodFwBEPqIKYlqBvxe:bir7lwf) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/netstate.go#L20)):*
> ```Go
> )
> 
> // PointerEntry - Path and Pointer are saved as a kv pair to boltdb.
> ```

nit -- should read as a sentence

---

*[pkg/overlay/service.go, line 35 at r1](https://reviewable.io/reviews/storj/storj/87#-LEohS_ZExQZuuwNl4tM:-LEohS_ZExQZuuwNl4tN:b-l6mwxj) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/overlay/service.go#L35)):*
> ```Go
> 	flag.StringVar(&bootstrapIP, "bootstrapIP", "", "Optional IP to bootstrap node against")
> 	flag.StringVar(&bootstrapPort, "bootstrapPort", "", "Optional port of node to bootstrap against")
> 	// flag.Parse()
> ```

remove

---

*[pkg/overlay/service.go, line 97 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojHIk3XMgL8ZLJWHe:-LEojHIk3XMgL8ZLJWHf:b5ofg1) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/overlay/service.go#L97)):*
> ```Go
> 	// bootstrap cache
> 	var cache *Cache
> 	if redisAddress != "" {
> ```

should check for bolt configs as well

---

*[storage/common/common.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojsSF57pY2kXGUzpg:-LEojsSF57pY2kXGUzph:ba5yhpz) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L1)):*
> ```Go
> package storage
> ```

opinion -- this should go in `storage/overlay.go` and be called `OverlayDB` since there might be multiple DB types down the road that won't want to adhere to this interface i.e Postgress,  CockroachDB, etc.

---

*[storage/common/common.go, line 7 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokwFxAdW7DjWTPFMQ:-LEokwFxAdW7DjWTPFMR:b-q7iiww) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L7)):*
> ```Go
> // db clients other than bolt
> type DB interface {
>   Put([]byte, []byte) error
> ```

Should we define a type vs []byte ?

---

*[storage/redis/client.go, line 52 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokXFu9jOHdbD1r69o:-LEokXFu9jOHdbD1r69p:bsrdnyj) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/redis/client.go#L52)):*
> ```Go
> }
> 
> func (c *redisClient) List() (_ [][]byte, _ error) {
> ```

should we make a `type Keys [][]byte` then add methods on that to make dealing with keys for consumers easier Keys.String() , Keys.Exists("foo") etc.?

---

*[storage/redis/client.go, line 76 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojUKN1xUIAMKluHMo:-LEojUKN1xUIAMKluHMp:bu16l9p) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/redis/client.go#L76)):*
> ```Go
> // Ping returns an error if pinging the underlying redis server failed
> // TODO: needed?
> // func (c *redisClient) Ping() error {
> ```

Thought was it allowed to check for aliveness but probably don't need it

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 17 files reviewed, 9 unresolved discussions (waiting on @bryanchriswhite and @coyle)

---

*[pkg/netstate/client_test.go, line 29 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_T7gBsDmx4DGlka0:-LEtHtKkAjEWKXhf61da:b-61rbfb) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L29)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Is this coming from "storj.io/storj/storage/common" ?
</blockquote></details>

Moved to `/internal/...` as we discussed

(see https://github.com/storj/storj/pull/87/commits/63b8512e84658aeeb6490d45f74f2478051dff2c)

---

*[pkg/netstate/client_test.go, line 74 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_eLW691-2RMZIfhT:-LEtIFXo8BcRani4O5Fx:b4hkll) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L74)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

We should add a method on Pointer to stringify it `pr1.Path()` that returns a string
</blockquote></details>

Agreed; does it need to be part of this PR?

---

*[pkg/overlay/service.go, line 35 at r1](https://reviewable.io/reviews/storj/storj/87#-LEohS_ZExQZuuwNl4tM:-LEtInaLASqiD1wfGnQe:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/overlay/service.go#L35)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[pkg/overlay/service.go, line 97 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojHIk3XMgL8ZLJWHe:-LEtIqBYBNx2Oq4YJ4Cs:bsettva) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/overlay/service.go#L97)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should check for bolt configs as well
</blockquote></details>

I'd like to do that in a different PR for https://www.pivotaltracker.com/story/show/158259670. I realize there already is some code in this one for that; i can remove it from this branch if you want, otherwise it'd just be in a bit early.

---

*[storage/redis/client.go, line 52 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokXFu9jOHdbD1r69o:-LEtKk0h4bvnVkueThsv:b-d7bhn0) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/redis/client.go#L52)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should we make a `type Keys [][]byte` then add methods on that to make dealing with keys for consumers easier Keys.String() , Keys.Exists("foo") etc.?
</blockquote></details>

will do

---

*[storage/common/common.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojsSF57pY2kXGUzpg:-LEtKO740olSSoTTHWUH:bs01c4r) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L1)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

opinion -- this should go in `storage/overlay.go` and be called `OverlayDB` since there might be multiple DB types down the road that won't want to adhere to this interface i.e Postgress,  CockroachDB, etc.
</blockquote></details>

`OverlayDB` is too specific of a name for this interface; it is used by overlay and netstate services.

How do we feel about `Store` or `KeyValueStore` or something along those lines?

---

*[storage/common/common.go, line 7 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokwFxAdW7DjWTPFMQ:-LEtKenHC2Z8as3kroGi:b-louncl) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L7)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Should we define a type vs []byte ?
</blockquote></details>

Yes, will do.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @coyle and @bryanchriswhite)

---

*[pkg/overlay/service.go, line 97 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojHIk3XMgL8ZLJWHe:-LEtdijj0swvAqSNL5GS:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/overlay/service.go#L97)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

I'd like to do that in a different PR for https://www.pivotaltracker.com/story/show/158259670. I realize there already is some code in this one for that; i can remove it from this branch if you want, otherwise it'd just be in a bit early.
</blockquote></details>

Done.

---

*[storage/redis/client.go, line 76 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojUKN1xUIAMKluHMo:-LEteRQC2wfCSskct0gX:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/redis/client.go#L76)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Thought was it allowed to check for aliveness but probably don't need it
</blockquote></details>

Done.

---

*[storage/common/common.go, line 7 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokwFxAdW7DjWTPFMQ:-LEtdqS82rynK7L7Ru5m:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L7)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

Yes, will do.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @coyle and @bryanchriswhite)

---

*[pkg/netstate/client_test.go, line 29 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_T7gBsDmx4DGlka0:-LEts1YT1A1yvZnlGgmY:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L29)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

Moved to `/internal/...` as we discussed

(see https://github.com/storj/storj/pull/87/commits/63b8512e84658aeeb6490d45f74f2478051dff2c)
</blockquote></details>

Done.

---

*[storage/redis/client.go, line 52 at r1](https://reviewable.io/reviews/storj/storj/87#-LEokXFu9jOHdbD1r69o:-LEtrXJpAltrx5K3OMD_:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/redis/client.go#L52)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Done.

---

*[storage/common/common.go, line 1 at r1](https://reviewable.io/reviews/storj/storj/87#-LEojsSF57pY2kXGUzpg:-LEtraQ0A-RDKNcI01uX:b-896fix) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/storage/common/common.go#L1)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

`OverlayDB` is too specific of a name for this interface; it is used by overlay and netstate services.

How do we feel about `Store` or `KeyValueStore` or something along those lines?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by coyle** [comment]
Review status: 0 of 20 files reviewed, 6 unresolved discussions (waiting on @bryanchriswhite and @coyle)

---

*[pkg/netstate/client_test.go, line 74 at r1](https://reviewable.io/reviews/storj/storj/87#-LEo_eLW691-2RMZIfhT:-LEtse0cBCl0qRrBWnlp:b32w12) ([raw file](https://github.com/storj/storj/blob/784ce8ffaf193d8c54447620ef97fe433d449114/pkg/netstate/client_test.go#L74)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

Agreed; does it need to be part of this PR?
</blockquote></details>

No

---

*[pkg/netstate/client_test.go, line 19 at r3](https://reviewable.io/reviews/storj/storj/87#-LEtu37m0ur5FfoiOx5p:-LEtu37nADClYEQ9owBH:bb6bzut) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/pkg/netstate/client_test.go#L19)):*
> ```Go
> 	"google.golang.org/grpc/codes"
> 	"google.golang.org/grpc/status"
> 	"storj.io/storj/internal/test"
> ```

separation between github and storj imports 

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEttmtJDPOOwKntXqFW:b-bwaq2u) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
> ```Go
> 	flag.StringVar(&bootstrapIP, "bootstrapIP", "", "Optional IP to bootstrap node against")
> 	flag.StringVar(&bootstrapPort, "bootstrapPort", "", "Optional port of node to bootstrap against")
> 	flag.StringVar(&localPort, "localPort", "8080", "Specify a different port to listen on locally")
> ```

I'm thinking we need this for now and use it vs hardcoded 8081 at Line 78

---

*[pkg/overlay/service_test.go, line 14 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttKhC6v2jeXXcNcPM:-LEttKhC6v2jeXXcNcPN:bb6bzu7) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/pkg/overlay/service_test.go#L14)):*
> ```Go
> 
> 	"github.com/stretchr/testify/assert"
> 	"google.golang.org/grpc"
> ```

separation between github and storj imports

---

*[internal/test/util.go, line 141 at r3](https://reviewable.io/reviews/storj/storj/87#-LEtuLaTCDOfc8aRnuln:-LEtuLaU6tegxl4salbz:b-sjtpwl) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/internal/test/util.go#L141)):*
> ```Go
> }
> 
> func (r *RedisServer) start() {
> ```

with all of these, instead of panicing I wonder if it would be better to pass `t *testing.T` into the function and `assert.NoError(t, err)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @coyle and @bryanchriswhite)

---

*[pkg/netstate/client_test.go, line 19 at r3](https://reviewable.io/reviews/storj/storj/87#-LEtu37m0ur5FfoiOx5p:-LEtzoY9C0fRvGgdEM9D:b-896fix) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/pkg/netstate/client_test.go#L19)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

separation between github and storj imports 
</blockquote></details>

Done.

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEtzPIM0ubm0VB1MFmR:bxa9aeb) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I'm thinking we need this for now and use it vs hardcoded 8081 at Line 78
</blockquote></details>

agreed, this one should be for the grpc server; done.

---

*[pkg/overlay/service_test.go, line 14 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttKhC6v2jeXXcNcPM:-LEu-4USA2DJm7oxsujr:b-896fix) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/pkg/overlay/service_test.go#L14)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

separation between github and storj imports
</blockquote></details>

Done.

---

*[internal/test/util.go, line 141 at r3](https://reviewable.io/reviews/storj/storj/87#-LEtuLaTCDOfc8aRnuln:-LEu3KsO3dSoaa8LHAJW:b-896fix) ([raw file](https://github.com/storj/storj/blob/c7cb3639aa2bd4ecd43cfcd8e542b26f511edb0a/internal/test/util.go#L141)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

with all of these, instead of panicing I wonder if it would be better to pass `t *testing.T` into the function and `assert.NoError(t, err)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Still fixing linter errors..

**Comment by coyle** [comment]
Review status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @coyle and @bryanchriswhite)

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEu6vEj4NHNn7AwSnw9:b1lcgil) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

agreed, this one should be for the grpc server; done.
</blockquote></details>

This one should be for the Kademlia node right? Also, don't think the change got pushed.

---

*[storage/redis/client.go, line 11 at r5](https://reviewable.io/reviews/storj/storj/87#-LEu6KN47ksFD0ADiRX0:-LEu6KN595FdlH2yP5wv:b-bx23sb) ([raw file](https://github.com/storj/storj/blob/02ef9464f973141794d334dfb20199756346916b/storage/redis/client.go#L11)):*
> ```Go
> 	"github.com/go-redis/redis"
> 	"github.com/zeebo/errs"
> 	"storj.io/storj/storage"
> ```

Separation 

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @bryanchriswhite)

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEu7X7G-nkblkgXC8qE:bxpq4dn) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

This one should be for the Kademlia node right? Also, don't think the change got pushed.
</blockquote></details>

Didn't make any change here; like you said, we need this for now.

Currently kad is doing a microTP thing and the overlay service is doing gRPC over TCP (hence the multiple ports). In the long-run we'd like to have multiple gRPC services over a microTP thing but until we implement that this is what we have.

---

*[storage/redis/client.go, line 11 at r5](https://reviewable.io/reviews/storj/storj/87#-LEu6KN47ksFD0ADiRX0:-LEu8LRjCcC-BJUXItKX:be4hh63) ([raw file](https://github.com/storj/storj/blob/02ef9464f973141794d334dfb20199756346916b/storage/redis/client.go#L11)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Separation 
</blockquote></details>

freaking goland... done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @coyle)

---

*[storage/redis/client.go, line 11 at r5](https://reviewable.io/reviews/storj/storj/87#-LEu6KN47ksFD0ADiRX0:-LEu8bHaAwF_4ysBRg1g:b-896fix) ([raw file](https://github.com/storj/storj/blob/02ef9464f973141794d334dfb20199756346916b/storage/redis/client.go#L11)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

freaking goland... done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @bryanchriswhite and @coyle)

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEuGFX-8BDgJqqqEs1W:b-k8mngw) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

Didn't make any change here; like you said, we need this for now.

Currently kad is doing a microTP thing and the overlay service is doing gRPC over TCP (hence the multiple ports). In the long-run we'd like to have multiple gRPC services over a microTP thing but until we implement that this is what we have.
</blockquote></details>

...err i think i misunderstood you. You were suggesting keeping `localPort` for now and use in place of the string below?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by coyle** [comment]
Review status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @coyle)

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEuG_jC7Gg_Omz89SLR:b-7jzv7t) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, bryanchriswhite (Bryan White) wrote…</i></summary><blockquote>

...err i think i misunderstood you. You were suggesting keeping `localPort` for now and use in place of the string below?
</blockquote></details>

right

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @coyle)

---

*[pkg/overlay/service.go, line 36 at r3](https://reviewable.io/reviews/storj/storj/87#-LEttmtJDPOOwKntXqFV:-LEuH61DE-rhAZkE1Nxj:b-896fix) ([raw file](https://github.com/storj/storj/blob/e65e115222a3def0aa4d4d2454c515f359b1796c/pkg/overlay/service.go#L36)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

right
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by coyle** [comment]
Reviewed 6 of 17 files at r1, 5 of 14 files at r3, 5 of 8 files at r4, 2 of 5 files at r5, 3 of 3 files at r6, 1 of 1 files at r7.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[storage/boltdb/client.go, line 17 at r7](https://reviewable.io/reviews/storj/storj/87#-LEuJwRY9Up2hUp0kWSo:-LEuJwRY9Up2hUp0kWSp:bm4fs4t) ([raw file](https://github.com/storj/storj/blob/38d159b9514be27fd1006bb3c478ffcd895263a6/storage/boltdb/client.go#L17)):*
> ```Go
> type boltClient struct {
> 	logger *zap.Logger
> 	DB     *bolt.DB
> ```

I don't think we want to expose this

---

*[storage/redis/client.go, line 18 at r7](https://reviewable.io/reviews/storj/storj/87#-LEuKMdC38rLeb6jhuP2:-LEuKMdC38rLeb6jhuP3:b-xvz3lb) ([raw file](https://github.com/storj/storj/blob/38d159b9514be27fd1006bb3c478ffcd895263a6/storage/redis/client.go#L18)):*
> ```Go
> // redisClient is the entrypoint into Redis
> type redisClient struct {
> 	DB  *redis.Client
> ```

Also don't think we should expose

---

*[internal/test/util.go, line 178 at r6](https://reviewable.io/reviews/storj/storj/87#-LEuH0L448poFk7XkPgC:-LEuH0L448poFk7XkPgD:b-c08g93) ([raw file](https://github.com/storj/storj/blob/48b35975e8b7dda824880cf3e8a3b5bf5a7c23ed/internal/test/util.go#L178)):*
> ```Go
> 
> 		if err := cmd.Run(); err != nil {
> 			// TODO(bryanchriswhite) error checking
> ```

should you just assert.NoError here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by bryanchriswhite** [comment]
Review status: 20 of 21 files reviewed, all discussions resolved (waiting on @coyle)

---

*[internal/test/util.go, line 178 at r6](https://reviewable.io/reviews/storj/storj/87#-LEuH0L448poFk7XkPgC:-LEuLdFkAByKkzYysVQd:bmuaimw) ([raw file](https://github.com/storj/storj/blob/48b35975e8b7dda824880cf3e8a3b5bf5a7c23ed/internal/test/util.go#L178)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should you just assert.NoError here?
</blockquote></details>

No because `cmd.Run()` does return with a thing (i don't think it's actually an error type, i think it's a status sort-of type) when we shut redis down. We should actually just be checking if the status was 0 or whatever code it returns when we call stop().

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Comment by coyle** [comment]
Reviewed 1 of 1 files at r7, 3 of 3 files at r8.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/87)*

**Pull request merged**
