### PR TITLE
.github: enable dependabot for upgrading go dependencies

### PR DESCRIPTION
**Pull request by drewwells**
What: 
Enables a Github feature to evaluate newer versions of dependencies and open PRs upgrading them. More info here: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#:~:text=Dependabot%20alleviates%20that%20pain%20by,packages%20that%20have%20known%20vulnerabilities.

Why:
After introducing new features, it becomes challenging to keep up with third party vendors they rely on. This tool is invaluable at ensuring the core developers are notified here when a vendor has been updated. Dependabot will open a PR that is easy to merge and has several features like `@dependabot rebase` to rebase them on the latest integration branch.

Please describe the tests:
 - Test 1: No tests needed, unit tests covering vendors will be relied on to prove the PRs are safe to merge
 
Please describe the performance impact:
Ideally third parties would get faster with time, but this is generally not the case in software development. I would venture a guess that performance will be negligible as dependabot is primarily going to upgrade point releases.

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by drewwells** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform), and we don't seem to have the users @drewwells on file. Once you have signed the CLA, please let us know, so we can manually review and add you to the approved contributors list.

Signed the CLA

**Comment by egonelbre** [comment]
I'm concerned about the churn it would create and as far as I know dependabot does not have a nice way to review the changes.

We have a requirement that all code must be reviewed (either internal or external). Keeping up with all the minor releases would add a lot of work.

Similarly we are keeping some of the dependencies intentionally on lower versions (not necessarily in storj/storj repo), because they have introduced dependencies that bloat the binaries.

For security alerts we already have it enabled.

**Comment by drewwells** [comment]
Since the docker image version is not checked into the Dockerfile, Dependabot won't actually update those. I'll remove them. It would be beneficial to use a single base image instead to allow Dependabot visibility in upgrading it.

As a result, dependabot will at max open 3 PRs per week. See the schedule here: https://github.com/storj/storj/pull/4092/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R30-R32

**Comment by egonelbre** [comment]
Anyways, I thought about debendabot... let's give it a try. If it does add a lot of noise, then it's always possible to remove later.

As for the same base image, I think there were two reasons we don't have same base image: 1. because you cannot refer to another file for the base image (AFAIK), 2. because they are relatively different. Ideally the Dockerfile issue would be fixed in dependabot instead.

**Review by egonelbre — APPROVED** [review]

**Review by egonelbre — APPROVED** [review]

**Review by stefanbenten — COMMENTED** [review]
As far as i can see, we do not upgrade the Dockerfile any more, correct?
If so, lets adjust the title accordingly.

Otherwise looks good to me!

**Review by stefanbenten — APPROVED** [review]

**Pull request merged**
