### PR TITLE
storagenode/web: Copy Node ID on click

### PR DESCRIPTION
**Pull request by alexottoboni**
What: When you click on the Node ID bar in the SNOHeader it automatically selects and copies the Node ID to your clipboard.

Why: Adds a bit of polish and user friendliness to the storage node page. If someone is clicking the Node ID they most likely want to copy the entire ID. Would probably be useful for the wallet address as well. 

Please describe the tests:
 - Test 1: Ran storj-sim and viewed a storage node with my changes built. Clicked on the Node ID and pasted the ID to verify it was copied to the clipboard. Don't see any automated tests for UI.
 
Please describe the performance impact: Minimal to none.

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by stefanbenten** [comment]
Hey @alexottoboni !

Thank you for your contribution. In order to process this PR, you first have to sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform)

Also the checkboxes have to be filled in by the reviewer, not yourself!

**Comment by alexottoboni** [comment]
Ah gotcha. I signed the CLA. Does this project have a way to re-trigger the check without pushing a new commit?

**Comment by crawter** [comment]
hey, @alexottoboni!  
Thanks for your contribution and for your idea!

We liked your proposal! We have already created appropriate tasks for our UI engineer and will implement it in nearest future!
If you don't mind, we will implement it by ourselves. 

Have a great day!

**Comment by crawter** [comment]
This feature will be implemented by SNO Growth team.

**Comment by crawter** [comment]
unfortunately, we could not merge your PR because it not corresponds to our style guide and it should have some UI elements approved by our designer.

**Comment by crawter** [comment]
we want a UI feature like this to stay consistent with our design guidelines, which are admittedly not public. if we gave you the design could you implement it according to it?

**Comment by alexottoboni** [comment]
I am open to implementing it with the design standards, it sounds like your org might need to make some decisions about what should be open and what is not. On the forums there is also some debate about whether docs should be open. It is slightly discouraging would be contributors if it is unclear how to contribute or if there are conflicting messages.

**Comment by crawter** [comment]
Hey, @alexottoboni!

You are totally right, we definitely should create more documentation and style guides!

So, we have prepared UI\UX for your PR
https://www.figma.com/file/bzyvRYXvqW7CcWlAEWQYeU/Node-ID?node-id=0%3A1

To implement "copying" in other places we are using next package: https://www.npmjs.com/package/vue-clipboard2 

We will be happy to review your new changes!

**Comment by crawter** [comment]
implemented in https://review.dev.storj.io/c/storj/storj/+/2345

**Pull request closed without merging**
