### PR TITLE
satellite/metainfo: enable server-side copy in production

### PR DESCRIPTION
**Pull request by nadimhq**
What: enable copy in production 

Why: Copy is working for uplink cli, having it enabled early on since some users don't use gateway and this would benefit users that use uplink

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by Erikvv** [comment]
It says "uplink cli" in the commit but this is not related to uplink-cli.

**Comment by Erikvv** [comment]
Should we wait to merge this until there is the final go-ahead from @mniewrzal ? What is the process?

**Comment by littleskunk** [comment]
@mniewrzal I believe now we are ready to enable it?

**Comment by littleskunk** [comment]
@nadimhq The unit test should fail and point out that the default config has changed without adjusting the expected default config: https://github.com/storj/storj/blob/abc9e2493f0a8a89ad7aeba5d08f02b1bdc140ec/scripts/testdata/satellite-config.yaml.lock#L572

**Comment by mniewrzal** [comment]
> @mniewrzal I believe now we are ready to enable it?

Yes.

**Review by littleskunk — APPROVED** [review]

**Review by storj-antonio — APPROVED** [review]

**Pull request merged**
