### PR TITLE
change ReputationAuditOmega (et al.) to AuditReputationWeight

### PR DESCRIPTION
**Pull request by navillasa**
What/Why: 
- changes occurrences of Reputation(Audit/Uptime)Omega to Reputation...Weight because the _w_ in the design draft actually stood for "weight," and I think it's confusing to add more Greek letters.
- also changed it from `ReputationAudit...`, `ReputationUptime...` to `AuditReputation...`, `UptimeReputation...` for readability and to be consistent with the db fields

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by navillasa** [comment]
> Does the design doc need and changes? Are you going to do lambda in another PR?

I'm open to changing lambda in the same PR! Do you have any name suggestions? `ForgetFactor`?

**Comment by ifraixedes** [comment]
> Do you have any name suggestions? ForgetFactor?

`ForgetFactor` looks good considering that [the data science document](https://github.com/storj/datascience/blob/master/reputation/Reputation_Scoring_Framework_Highlevel.pdf) mentions

> and the concept of a forgetting factor λ

**Comment by ifraixedes** [comment]
I'm thinking now if we change _lambda_ why don't we change _alpha_ and _beta_?

**Comment by navillasa** [comment]
> I'm thinking now if we change _lambda_ why don't we change _alpha_ and _beta_?

_Alpha_ and _beta_ have grown on me more than the others, but I'm in favor! Ben and Patrick just suggested `SuccessImpact` and `FailureImpact` as replacements, which I think are great.

**Comment by ifraixedes** [comment]
> Alpha and beta have grown on me more than the others, but I'm in favor! Ben and Patrick just suggested SuccessImpact and FailureImpact as replacements, which I think are great.

They look great to me too!

**Comment by navillasa** [comment]
> > Alpha and beta have grown on me more than the others, but I'm in favor! Ben and Patrick just suggested SuccessImpact and FailureImpact as replacements, which I think are great.
> 
> They look great to me too!

okay on second thought, renaming alpha and beta is going to need another dbx migration step, so in the interest of moving things along, I think I'm just going to rename lambda to `ForgetFactor` but leave the `alpha` and `beta` alone.

**Pull request merged**
