### PR TITLE
Fix "Number of valid pieces is lower then success threshold"

### PR DESCRIPTION
**Pull request by kaloyan-raev**
Fixes https://storjlabs.atlassian.net/browse/V3-1486

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by mniewrzal** [comment]
we also should add test case for this

**Comment by kaloyan-raev** [comment]
@mniewrzal sure, do you want to implement this tests in another PR. I suggest merging the fix without the test as it is an important one.

**Comment by mniewrzal** [comment]
yes, I was thinking about another PR. I can do this.

**Comment by kaloyan-raev** [comment]
Thanks!

**Pull request merged**
