### PR TITLE
Remove VOLUME /root/.local/share/storj/storagenode

### PR DESCRIPTION
**Pull request by sixcorners**
What: 
Dockerfile VOLUME /root/.local/share/storj/storagenode
Why:
It keeps creating volumes in /var/lib/docker/volumes and it doesn't seem to be used. Is it used for anything?
Please describe the tests:
none
 
Please describe the performance impact:
none

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by sixcorners** [comment]
How do I sign the CLA?

**Comment by sixcorners** [comment]
The thing says to contact the project maintainers. Like here in the ticket or do they have a preferred mode of communication?

**Comment by sixcorners** [comment]
Who are the project maintainers?

**Comment by thepaul** [comment]
The CLA can be signed at https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform .

**Comment by sixcorners** [comment]
k thanks done

**Comment by sixcorners** [comment]
rebased on master

**Pull request merged**
