### PR TITLE
satellite/marketingweb: fix broken pipe error

### PR DESCRIPTION
**Pull request by VinozzZ**
What: 

If clients drop the connection, it's expected that we will be getting an EPIPE error. Therefore, we will ignore the error in that situation

Why:

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by egonelbre** [comment]
The question is. Where are the broken pipes coming from? The server shouldn't shutdown before finishing the tests and checking the responses.

**Comment by VinozzZ** [comment]
> The tests shouldn't cause this error.

AFAIK, The reason is because we have redirect in the POST request handler, so the server would shutdown after the response from POST request, but not wait for the redirect to finish

**Comment by ifraixedes** [comment]
For the same reason than @egonelbre it looks strange to me that we need to do this.

> AFAIK, The reason is because we have redirect in the POST request handler, so the server would shutdown after the response from POST request, but not wait for the redirect to finish

I'm not convinced about this; do you have the test output log when that error false positive error happens? it may help me to understand it.

**Comment by egonelbre** [comment]
@ifraixedes, I think the current solution is the right one... the comment doesn't sound right, but the issue is the server starts writing to the connection, nothing is reading it... eventually the thing gets shut down. But also I think there should be some additional checks to ensure that the requests got the right response, not just that they succeeded.

**Comment by VinozzZ** [comment]
@egonelbre I added checks for response status code

**Pull request merged**
