### PR TITLE
dbutil: reduce defaults so sum is < 100

### PR DESCRIPTION
**Pull request by jtolds**
What: Reduce the defaults

Why: Michal says this helps! 

> I ran this test once again with modified open/idle connection setting for our DB. I set it to 60/30 open/idle (I read somehere that sum needs to be less than postgres max, default 100) and after more than 4h it still uploading (earlier after 2h I had "too many clients already" and satellite was unresponsive). I uploaded more than 130k files and its still working.

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by stefanbenten** [comment]
As i am not reaching this limit on my database, i cannot report if thats actually accurate :)

**Comment by stefanbenten** [comment]
@jtolds Also dont forget to alert our channel for config-changes please!

**Comment by mniewrzal** [comment]
Egon had a good suggestion that we have two db pools (master + pointerdb) so with this limit, we still can hit `"too many clients already"`. Maybe we can set even half of the new settings but maybe someone with better postgres knowledge can say more about it.

**Comment by stefanbenten** [comment]
@mniewrzal Reduced the numbers even more. They should be still more than plenty. 👍

**Comment by mniewrzal** [comment]
:+1

**Comment by mniewrzal** [comment]
:+1:

**Pull request merged**
