### PR TITLE
web/multinode: implement table sorting

### PR DESCRIPTION
**Pull request by psaintmalo**
#6964

What: 
Add a sorting feature in the multinode dashboard to change the order in which the nodes are displayed by clicking the respective columns.

Why:
Currently the full list of nodes can become chaotic and the information can be hard to grasp because node order is fixed.

Please describe the tests:
 - No additional test cases have been added as this only implements front-end aesthetic changes.
 
Please describe the performance impact:
 - Sorting takes place in the front end - no noticeable performance impact.

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by psaintmalo** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our new [Contributor License Agreement v2](https://forms.gle/5qfiYnT4HYi95R7JA), and we don't seem to have the users @psaintmalo on file. Once you have signed the CLA, please let us know, so we can manually review and add you to the approved contributors list.

CLA has been signed already. Could someone review it?

**Comment by onionjake** [comment]
I've passed this to the team to have them take a look.

**Comment by psaintmalo** [comment]
> I've passed this to the team to have them take a look.

Any updates on this?

**Comment by shaupt131** [comment]
> > I've passed this to the team to have them take a look.
> 
> Any updates on this?

We've added this issue to one of our team boards, and will work to get you reviews when we resume normal operation on Thursday.

**Review by jtolio — APPROVED** [review]

**Pull request merged**
