### PR TITLE
web/satellite/tests: graphql endpoint

### PR DESCRIPTION
**Pull request by storj-antonio**
What: GraphQL Security and Satellite API Testing
Why: Other than having a mechanism to regression test these features we also need to verify that there aren't any security vulnerabilities. For instance tests have been put into place to make sure users can't get or set data for other users.

Security Items Under Test

Authentication Controller
Login with invalid/unknown credentials
Brute force user 1 password (HTTP 429)
Change user 1 password
Change user 1 email address
Delete user 1

Payments Controller
List credit card 1 for user 1 payment account
Add card for user 1 payment account
List multiple cards for user 1
Make card 1 for user 1 default
Delete card for user 1
View user 1 billing history
View user 1 project charges
View user 1 account balance
Token Deposit for user 1

Bucket Controller
List all bucket names for user 1 by project id

API Controller
Delete API key by name for user 1
Delete API key by project id for user 1
Create API key for user1 by project id

GRAPHQL
Delete project member by project id and email from user 1 account
Rename project for user 1 by project id
Modify project description for user 1 by project id
Rename project and modify description for user 1 by project id
List project members from user 1 project by project id
View usage limits from user by project id
List API keys from user 1 by project id
Get bucket usage from user 1 by project id

Introspection Test

What: This test generates a file with all graphql endpoints stored in it using introspection. On each build a new file will get created and both files will be compared to determine if any new endpoints were added or if any endpoints were removed.

Why: In order to verify all endpoints, we must know if any are created or deleted. test_graphql.sh will call this test and watch the exit code. If exit code is zero then testing shall commence else break out before executing the tests and send a fail signal to Jenkins.

Please describe the tests:

Test 1: Verify graphql basic integrity is intact.
Test 2: Verify introspection is functional.
Test 3: Check to see if endpoints were created or deleted.

Other Items:
-Updated postman config json files to include fixes for user 2 security tests.
-Using API to create user 2 via postman.
-fixes to main.go. Im some instances new endpoints could be added without the script noticing.
-endpoints.go now grabs the SATELLITE_0_ADDR environment variable to generate the satellite url.
-endpoints.go now manipulates the path based on os. I have tested this in both linux and windows
-added copyright as to satisfy the linter, running test setup in local Jenkins environment.
-updated makefile to include test-sim-api and included test-sim-api.sh in the scripts directory. This was implemented as to stay consistent with existing tests. 
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by stefanbenten** [comment]
@cla-bot check

**Comment by stefanbenten** [comment]
Listing our internal Jira Ticket will not help the community much. I think it can be omitted given your Why/What explanation above.

Also make sure to properly name the PR title (package folders, etc).

**Comment by storj-antonio** [comment]
Closing this pull request to resolve the blocking issues as well as update this branch with main.

**Comment by storj-antonio** [comment]
Reopened to be more consistent with githubs PR workflow.

**Comment by storj-antonio** [comment]
Removed link to Jira task as Stefan pointed out it will be of no use to the community.

**Comment by storj-antonio** [comment]
Permissions issue is preventing this from building. As part of troubleshooting the permissions issue, modifications were made to files that were unnecessary and I am cancelling this PR. A new branch has already been created and a pull request will be submitted shortly.

**Pull request closed without merging**
