### PR TITLE
Fix uplink cp progress bar

### PR DESCRIPTION
**Pull request by mniewrzal**

### CODE REVIEW

**Comment by aleitner** [comment]
These changes look good. Can you also add something that checks if logging is on? We don't want to display the bar when uplink is printing log messages

**Comment by mniewrzal** [comment]
Sure. I will check what i can do with this.

**Comment by aleitner** [comment]
I ran the code locally and the progress bar is still displaying along with log messages. I think the log level is too far separated from `cp.go` and this would be more code than is worth to turn off the progress bar during log level output when whoever is looking can just turn the progress bar off with `--progress false`. Sorry! Just take out the log level check and you can merge

**Comment by mniewrzal** [comment]
Most probably default log level (warn) is relatively high and it will mess with progress. I agree that progress flag is enough for now to control output.

**Pull request merged**
