### PR TITLE
storagenode: use minimum time in the order for expiration

### PR DESCRIPTION
**Pull request by zeebo**
What: Use the smaller of the two expiration times in the piecestore for the order limits 

Why: So that the database is much smaller.

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact: Should help with database load.

## Code Review Checklist (to be filled out by reviewer)
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by thepaul** [comment]
I can see that the existing entries will all fall off eventually, but maybe it's worth having a migration still that updates their expiration dates so that they can fall off sooner?

45 days is a long time to wait for the full benefit.

**Comment by zeebo** [comment]
I wonder if we can just ask node operators to run `delete from used_serial` once if they want it to be smaller?

**Comment by egonelbre** [comment]
We can just delete the used_serials, the creation date will mostly protect against replays.

**Comment by zeebo** [comment]
Alright, should I add a migration to this that deletes from the table? might as well drop that index while I'm there.

**Comment by zeebo** [comment]
https://github.com/storj/storj/pull/2508 is to do the migration/drop.

**Pull request merged**
