### PR TITLE
Link Sharing service design

### PR DESCRIPTION
**Pull request by azdagron**
This PR outlines a design for a proposed link sharing service that can be used to share objects in the storage network via a simple URL.

### CODE REVIEW

**Comment by americanbanshee** [comment]
This pull request has been mentioned on **Storj Labs Community Forum: Decentralized Cloud Storage**. There might be relevant details there:

https://forum.storj.io/t/design-draft-link-sharing-service/316/1

**Comment by azdagron** [comment]
It's is intended to be an independently deployed service. It isn't tied to any one satellite.

**Comment by stefanbenten** [comment]
If the intention is to have the ability to run it seperate and on uplink/gateway great 👍

**Comment by azdagron** [comment]
Couldn't that same attacker just use the share URL to accomplish the same thing?

**Comment by azdagron** [comment]
Or are you talking about revocation? Like you register a share blob with the server and it gives you back a hash that you can expire or revoke (if the URL gets out there)?

**Comment by jtolds** [comment]
in the long term the satellite itself should be responsible for usage throttling. currently we have the same problem if someone posts their uplink CLI config to facebook

**Comment by azdagron** [comment]
The hash thing could help keep the URL small(er). Because it is currently not small at all. It does complicate the design a little bit and implies server affinity (to the group of link sharing services sharing the database holding the shares). You'd also have to come up with a strategy for keeping the data store pruned of stale mappings.

**Comment by azdagron** [comment]
Storing the share blob also gives an attacker a convenient way to get access to anything shared by that link sharing service if the database is compromised....

**Comment by zeebo** [comment]
> in the long term the satellite itself should be responsible for usage throttling. currently we have the same problem if someone posts their uplink CLI config to facebook

How often do you think someone would post their uplink CLI config to facebook versus a URL designed to be shared and sent to others?

**Comment by jtolds** [comment]
> How often do you think someone would post their uplink CLI config to facebook versus a URL designed to be shared and sent to others?

perhaps that's a bad example. let's say i share read only log bucket credentials with a log analysis service that runs amok. running amok is the problem i think the satellite should be responsible for handling anyways

**Comment by zeebo** [comment]
> perhaps that's a bad example. let's say i share read only log bucket credentials with a log analysis service that runs amok. running amok is the problem i think the satellite should be responsible for handling anyways

The difference I see is between you explicitly provisioning your credentials to some service that has no business sending those credentials out, and you sending your credentials to some service that requires leaking those credentials to anyone that wants to view the data.

Perhaps a shared encryption key with a key id in the URL? Stateless, protects credentials from leaks, share service can redirect to encrypted URLs for any unencrypted one, allows key rotation.

**Comment by zeebo** [comment]
So perhaps a compromise to avoid dealing with figuring out an encryption scheme, we design the share service to support `HEAD` as well as `GET`, and either may respond with a redirect to some other (maybe encrypted) URL. Clients can query `HEAD` when creating a share to see what URL to display to users for sending to others.

**Comment by azdagron** [comment]
I've updated the PR with the HEAD request.

**Pull request merged**
