### PR TITLE
web/multinode: add Node name field when adding a new node

### PR DESCRIPTION
**Pull request by ptdatta**
What: 
Added node name while adding nodes to the multinode dashboard.

image

### CODE REVIEW

**Comment by ptdatta** [comment]
@profclems Can you please review this PR.

**Review by profclems — DISMISSED** [review]

**Comment by profclems** [comment]
Nit: Please preserve the PR template when opening a new PR

**Comment by ptdatta** [comment]
> Nit: Please preserve the PR template when opening a new PR

**Review by profclems — APPROVED** [review]

**Review by ifraixedes — APPROVED** [review]

**Comment by ifraixedes** [comment]
Flaky test. I run the build it again

**Pull request merged**
