### PR TITLE
Easy fix: typo

### PR DESCRIPTION
**Pull request by sndrr**
What: Fixes a typo in the dashboard cmd

Why: Typos are unneeded.

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by jtolds** [comment]
Here is the form! https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform

**Comment by ifraixedes** [comment]
Thanks for your contribution.
I'm going to handle how you can get the CLA signed.

**Comment by sndrr** [comment]
Signed the CLA.

**Comment by stefanbenten** [comment]
Hey @sndrr , we just added you to the List of approved Contributors!
I updated the branch and you should be able to merge your PR in a few minutes!

**Pull request merged**
