### PR TITLE
[Mobile] Method to convert passphrase to EncryptionAccess 

### PR DESCRIPTION
**Pull request by mniewrzal**
What: New method for mobile libuplink to convert a human-readable encryption key to serialized encryption access.
+ adjustments for tests

Why: We need to expose more things to our mobile libuplink

Please describe the tests:
 - Test 1: added simple automatic test
 
Please describe the performance impact: none

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by mniewrzal** [comment]
@kaloyan-raev make sense

**Comment by mniewrzal** [comment]
@kaloyan-raev it looks that we don't need to expose new things. Everything can be done with current API. See https://github.com/storj/storj/pull/2479/files#diff-eac5462649c3334536bf53b728b34ac0R334

**Comment by kaloyan-raev** [comment]
`SaltedKeyFromPassphrase` was recently added and is not available in `libuplink-android:0.2`. We still need to release v0.3. So before doing this, it would be nice if we can also add `NewEncryptionAccessWithDefaultKey`, which seems to be still missing.

**Comment by mniewrzal** [comment]
ok, it will be visible as `new EncryptionAccess(defaultKey)`

**Pull request merged**
