### PR TITLE
Enable datarepair tests back

### PR DESCRIPTION
**Pull request by kaloyan-raev**
What: 

They were disabled with #1727 due to instability. I expected that the changes in #1785 affect them positively.

I run them 500 times locally and they look good.

Why:

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
Unfortunately, we have a failure on Travis:
```
datarepair_test.go:120: 
                Error Trace:    datarepair_test.go:120
                                            run.go:71
                Error:          Received unexpected error:
                                segment error: metainfo error: rpc error: code = Internal desc = orders error: not enough nodes available: got 0, required 3; orders error: node is offline: 12QhCwxYoPanj4fcw3thQZxVu5hsjnmFttr4pvTkUAAscq6PJnr; orders error: node is offline: 1cvKCTqnigCprVDbdijDb6Qaxste6AFZaRKF9LCCzyzkGSAyT1; orders error: node is offline: 1q1FsgzTc7mxNdLBFoCWdkZFmrJs5XGE8keKBP7hadfKG2grWC; orders error: node is offline: 19PrpCCZN6QoBiFgjH9u8eLK6FoYcoWqppqwmgjv1DPmt5mnkJ; orders error: node is offline: 12CHXY7EFJHScoHErxDCnjH6Q8YyrQJwk8qPUJ9Y1hwmQHERz7w; orders error: node is offline: 12CZ6BtYaWm3zbQ5appeyPhbwxLidxce1nosaSXYcar9b6agmLV; orders error: node is offline: 147RFG6dnQiL6LcHmeGpKSGd8MMMAD6wYD9gEdroEzEtTkYFLm
                                    storj.io/storj/uplink/metainfo.(*Metainfo).ReadSegment:154
                                    storj.io/storj/pkg/storage/segments.(*segmentStore).Get:198
                                    storj.io/storj/pkg/storage/streams.(*streamStore).Get:291
                                    storj.io/storj/pkg/stream.(*Download).resetReader:109
                                    storj.io/storj/pkg/stream.(*Download).Read:45
                                    bytes.(*Buffer).ReadFrom:207
                                    io/ioutil.readAll:36
                                    io/ioutil.ReadAll:45
                                    storj.io/storj/internal/testplanet.(*Uplink).Download:278
                                    storj.io/storj/pkg/datarepair_test.TestDataRepair.func1:119
                                    storj.io/storj/internal/testplanet.Run.func1:71
                                    testing.tRunner:865
```

**Comment by mobyvb** [comment]
Because of this commit, the data repair tests will not pass locally now https://github.com/storj/storj/commit/6ece4f11ad9cd5ce375880f35529be43209275a2

**Comment by mniewrzal** [comment]
@kaloyan-raev its still failing. can we close this PR?

**Comment by mniewrzal** [comment]
Fixed in #2099

**Pull request closed without merging**
