### PR TITLE
Expose LOG_LEVEL env variable via Dockerfile for storagenode

### PR DESCRIPTION
**Pull request by gfidente**
What: 
This change adds the ability to configure the log.level argument at run time using LOG_LEVEL env variable.

Why:
The default 'info' level for the storagenode will dump dozens of lines every second. 

Please describe the tests:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by gfidente** [comment]
CLA signed now

**Review by profclems — APPROVED** [review]

**Review by ifraixedes — APPROVED** [review]

**Comment by profclems** [comment]
@cla-bot check

**Comment by profclems** [comment]
@ifraixedes with a change like this, we would need to tag the docker image as latest when released

**Comment by gfidente** [comment]
thanks for the quick reviews round and for the effort keeping the github's PRs tidy and also ... thanks for storj :)

**Pull request merged**
