### PR TITLE
uplink: Reduce satellite request using Batch when possible

### PR DESCRIPTION
**Pull request by ifraixedes**
What: Replace all the individual requests which can be sent in a batch.

Why: Sending requests in a batch when possible reduce satellite network traffic.

Related with the ticket https://storjlabs.atlassian.net/browse/V3-2620

Description:
After https://github.com/storj/storj/pull/3311 has been merged some requests which had to be sent individually can be sent in a single `Batch` request for reducing satellite network traffic.

I only found in `uplink` package and sub-packages the following functions which make `metainfo.Client` requests which are possible to be sent in a batch:

* `uplink/storage/streams/store.go`
	* `*streamStore.Delete`
	* `*streamStore.upload`
* `storj.io/storj/uplink/storage/segments/store.go`
	* `*segmentStore.Put`

Only the first one can be replaced, the other two, request some information in one `metainfo.Client` call for performing other operations whose result matters before calling the other `metainfo.Client` functions.

For other changes that you may think are not related, please read the commit messages before commenting on that.

Please describe the tests: It's an internal refactoring, we don't test internal implementation logic, we check the output, so there is no need for additional test and the current test must pass with the committed changes.
Please describe the performance impact: Theoretically, there is some performance improvement because of the network traffic reduction.

## Code Review Checklist (to be filled out by reviewer)
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by mniewrzal** [comment]
I see one more place where we can try batch requests:
https://github.com/storj/storj/blob/521c39bda080a6c9ca0195594036f214cc4230d7/uplink/storage/streams/store.go#L301
In `Get` method we should be able to combine `metainfo.GetObject` with `metainfo.DownloadSegment` from `s.segments.Get` (few lines below GetObject).

**Comment by ifraixedes** [comment]
@mniewrzal I didn't understand that we should change the function signature.

**Comment by mniewrzal** [comment]
> @mniewrzal I didn't understand that we should change the function signature.

My understanding is that we should utilize `Batch` request as much as possible. Each optimization can reduce time we need for upload/download/delete.

**Comment by ifraixedes** [comment]
Ok, but it will be hard to ensure to find all of them.

I would rather prefer to merge these easy ones which are localized in the same function and have another PR with the ones spread across multiple functions.

**Comment by mniewrzal** [comment]
> I would rather prefer to merge these easy ones which are localized in the same function and have another PR with the ones spread across multiple functions.

Sure. I will finish my review in the morning.

**Comment by zeebo** [comment]
> request some information in one `metainfo.Client` call for performing other operations whose result matters before calling the other `metainfo.Client` functions.

I believe we designed a mechanism to thread these things through, wherein if values were left blank, they would be filled in from the responses of previous requests. Does that apply here?

**Pull request merged**
