### PR TITLE
uplink/storage/streams: Bundle out metainfo segment upload

### PR DESCRIPTION
**Pull request by ifraixedes**
What: Bundle out the logic related to `metainfo` segment upload.

Why:  Because it may be clearer the set of operations performed for uploading segments.

Please describe the tests: This is a refactoring of a single method that doesn't change the current output and it doesn't change the current behavior, hence there is no new test but the existing tests must pass.
Please describe the performance impact: none

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by mniewrzal** [comment]
@ifraixedes don't invest time in refactoring `uplink/storage` because one of our goals is to remove it completely.

**Comment by ifraixedes** [comment]
@mniewrzal This work was done for the PR https://github.com/storj/storj/pull/3429 

Theses changes led to loop reorganization; unfortunately, I've realized when I did this extraction not before, so I've committed aside for easing reviewing. The only thing that I've done extra in this branch is to rebase manually (due to ugly conflicts) from some minor fixes that I've applied in the branch of the PR https://github.com/storj/storj/pull/3429 and discovered a mistake in the bundled regarding consuming the `io.Reader`.

If we aren't going to merge this, I don't bother to resolve the linter errors, otherwise, let me know.

**Comment by ifraixedes** [comment]
@mniewrzal I'm fixing the changes with rebasing because it can be fixed automatically, so I will force push.

Let me know if you want to merge this or not due the fact that `uplink/storage` may disappear at some point in the future. After knowing that, I will know if to work in the quick fix (https://storjlabs.atlassian.net/browse/V3-3139) or wait until this gets merged if I see that it could generate too many nasty conflicts.

**Comment by ifraixedes** [comment]
Because of changes in PR https://github.com/storj/storj/pull/3555 for fixing a bug and because this logic will change in the future, I think that these changes make less sense now and not committing them will avoid introducing new possible bugs, so I'm closing it.

**Pull request closed without merging**
