### PR TITLE
web/multinode: Fix `My Nodes` sidebar item spelling

### PR DESCRIPTION
**Pull request by odarriba**
What: The `MyNodes` section of the sidebar is not correct

Why: It is currently spelled as `MyNodes` when it should be `My Nodes` to match the rest of entries in the menu.

Please describe the tests:
There are no tests for this, as it is a change in a string literal of the UI and there were no previous tests regarding this.
 
Please describe the performance impact:
It has no performing impact, as it is an UI change.

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by odarriba** [comment]
@cla-bot check

**Comment by odarriba** [comment]
I already signed the Contributor License!

**Review by profclems — APPROVED** [review]
Thanks for fixing this @odarriba!

**Comment by profclems** [comment]
@cla-bot check

**Review by Erikvv — APPROVED** [review]

**Pull request merged**
