### PR TITLE
Rename all the things

### PR DESCRIPTION
**Pull request by egonelbre**
What: 

Why:

script to rename packages:

```
#!/bin/bash

set -x
set -e

function rename_pkg() {
    gomvpkg -from storj.io/storj/$1 -to storj.io/storj/$2 -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
    goimports -local storj.io -w .
    git reset    -q -- *.pb.go *.dbx.go
    git checkout -q -- *.pb.go *.dbx.go
    git add .
}

function move_pkg() {
    gomvpkg -from storj.io/storj/$1 -to storj.io/storj/$2 -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
    goimports -local storj.io -w .
    git reset    -q -- *.pb.go *.dbx.go
    git checkout -q -- *.pb.go *.dbx.go
    git add .
    git commit -m"rename package $1 to $2"
}

move_pkg pkg/linksharing linksharing
move_pkg pkg/httpserver  linksharing/httpserver

move_pkg pkg/eestream   uplink/eestream
move_pkg pkg/stream     uplink/stream
move_pkg pkg/metainfo/kvmetainfo  uplink/metainfo/kvmetainfo

move_pkg pkg/auth/signing  pkg/signing

mkdir uplink/storage
rename_pkg pkg/storage/ec         uplink/ecclient
rename_pkg pkg/storage/meta       uplink/storage/meta
rename_pkg pkg/storage/objects    uplink/storage/objects
rename_pkg pkg/storage/segments   uplink/storage/segments
rename_pkg pkg/storage/streams    uplink/storage/streams
git commit -m"rename package pkg/storage to uplink/storage"

move_pkg pkg/accounting satellite/accounting
move_pkg pkg/audit      satellite/audit
move_pkg pkg/certdb     satellite/certdb
move_pkg pkg/discovery  satellite/discovery
move_pkg pkg/overlay    satellite/overlay

mkdir satellite/repair
rename_pkg pkg/datarepair/checker     satellite/repair/checker
rename_pkg pkg/datarepair/irreparable satellite/repair/irreparable
rename_pkg pkg/datarepair/queue       satellite/repair/queue
rename_pkg pkg/datarepair/repairer    satellite/repair/repairer
# TODO: manually, rename_pkg pkg/datarepair             satellite/repair
git commit -m"rename package pkg/datarepair to satellite/repair"
```

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
The `ecclient` is used by both the uplink and the satellite. Is it still OK to move it under `/uplink`?

**Comment by egonelbre** [comment]
@kaloyan-raev to me it feels like satellite is using uplink logic to implement reading/writing to storage node. Of course, the danger here is that we end up accidentally putting some "satellite-only" logic to uplink (like with repairer).

We have multiple things named `uplink`:
1. concept of the binary (`cmd/uplink`)
2. concept of the library (`lib/uplink`)
3. concept of the storagenode and/or satellite communication (`uplink/*`)
4. packages that only 1 and 2 need (also `uplink/*`)

So I put, `ecclient` into `uplink/` for the same reason as `pkg/eestream` and `pkg/stream`.

I think it helps to clarify things that when you wish to communicate with another storagenode to upload/download you use "uplink". For example, when implementing graceful exit one storagenode could end up using uplink to upload data to another storagenode.

We could also have a completely separate package `protocol` or similar, for 3... which I didn't think of before, but we could try to separate it out and see what the resulting folder structure would look like.

**Comment by kaloyan-raev** [comment]
@egonelbre OK. This makes sense.

**Comment by egonelbre** [comment]
Also maybe:
```
pkg/auth -> satellite/auth
pkg/auth/grpcauth -> satellite/auth
pkg/auth/signing -> pkg/signing
```

@kaloyan-raev / @mniewrzal?

**Comment by mniewrzal** [comment]
`NewAPIKeyInjector` from `pkg/auth/grpcauth` is used in `uplink` but I guess we can split `pkg/auth/grpcauth/authentication.go` into `satellite` and `uplink` version, but that would be a manual step.

**Comment by mniewrzal** [comment]
Rest looks good.

**Pull request merged**
