### PR TITLE
adds netstate pagination

### PR DESCRIPTION
**Pull request by navillasa**
Adds pagination to the netstate list function, boltdb client, and redis client.
To call list from the netstate rpc client, you can now provide a StartingPathKey and Limit:
```
	listReq := proto.ListRequest{
		StartingPathKey: []byte("test/path"),
		Limit:           5,
		APIKey:          apiKey,
	}
        listRes, err := client.List(ctx, &listReq)
        ...
```
A limit is required but StartingPathKey is not. If no start key is given, listing will begin from the first key in storage.

You can run the example client at examples/netstate-client/main.go.
Tests are located:
- pkg/netstate/netstate_test.go
- internal/test/storage.go
- storage/boltdb/client_test.go
- storage/redis/client_test.go

Redis pagination will require more work in diff pull request (for returning keys in order).

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/95)

### CODE REVIEW

**Comment by coyle** [comment]
Review status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @navillasa)

---

*[storage/common.go, line 16 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2fPRR3VBA2x0pJ0MO:-LF2fPRR3VBA2x0pJ0MP:b380lse) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/common.go#L16)):*
> ```Go
> 
> // Limit indicates how many keys to return when calling List
> type Limit int64
> ```

int64 might be overkill

---

*[storage/common.go, line 23 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2ftC3-Og-Ir0o6XbM:-LF2ftC4C875pox26yo6:b-hg7v2x) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/common.go#L23)):*
> ```Go
> 	Put(Key, Value) error
> 	Get(Key) (Value, error)
> 	List(Key, Limit) (Keys, error)
> ```

you need to update the redis List method as well since it uses this interface

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LF2g3Zu8XiKo2kjkwfc:bmy6243) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
> ```Go
> 	err := c.db.Update(func(tx *bolt.Tx) error {
> 		cur := tx.Bucket(c.Bucket).Cursor()
> 		for k, _ := cur.Seek(startingKey); k != nil; k, _ = cur.Next() {
> ```

should the error be ignored here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed, 8 unresolved discussions (waiting on @navillasa)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @navillasa)

---

*[pkg/netstate/netstate.go, line 124 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15WcH8TnJtwqz4K_9:-LF2gF7i6bNmj1-8K8Pj:b175e6c) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate.go#L124)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

make sure to write a test about this!
</blockquote></details>

I did write a test (https://github.com/storj/storj/pull/95/files#diff-98811e39c7c388c6bb62fb97b54bcb6cR244) but granted it was in that monster test file and with my reverse definition of truncated 😂. Yeah I misunderstood, I thought if we returned less than the requested limit of keys, that meant the results were truncated. But I'll fix this, thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @navillasa and @jtolds)

---

*[storage/common.go, line 16 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2fPRR3VBA2x0pJ0MO:-LF2hTnjAWduT33Z3uAk:bpuh33) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/common.go#L16)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

int64 might be overkill
</blockquote></details>

Agree. If it's not too much of a hassle could you look at the netstate proto file and let me know what other int64s should be taken out?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @navillasa, @jtolds, and @coyle)

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LF2hliR1XCDPEgO5zML:b-1vp8yx) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

should the error be ignored here?
</blockquote></details>

Oh! No, good catch!

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by jtolds** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @navillasa, @jtolds, and @coyle)

---

*[pkg/netstate/netstate.go, line 124 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15WcH8TnJtwqz4K_9:-LF3-HBt5Gv10WoeWEg8:bfi61s0) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate.go#L124)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

I did write a test (https://github.com/storj/storj/pull/95/files#diff-98811e39c7c388c6bb62fb97b54bcb6cR244) but granted it was in that monster test file and with my reverse definition of truncated 😂. Yeah I misunderstood, I thought if we returned less than the requested limit of keys, that meant the results were truncated. But I'll fix this, thanks!
</blockquote></details>

whoops! sorry! i missed it. good job!

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LF3-Q-X59-b-TKAVp1-:b-rmrkin) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

Oh! No, good catch!
</blockquote></details>

i went and checked, Seek and Next don't return errors.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @jtolds, @navillasa, and @coyle)

---

*[pkg/netstate/netstate.go, line 102 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15JXnD9UNn7fHFtNf:-LF37vM4BxIf03xqg_de:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate.go#L102)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

you don't need to log the error and return in general. returning the error is sufficient. somewhere it will get logged!
</blockquote></details>

Done.

---

*[pkg/netstate/netstate.go, line 105 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15ROO4bm9ULdhrptB:-LF37ycx8J2gtjRhzff7:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate.go#L105)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

<= 0?
</blockquote></details>

Done.

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LF3anPK9lGlsbohqKIq:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

i went and checked, Seek and Next don't return errors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: 3 of 12 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[pkg/netstate/netstate_test.go, line 37 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15l932K0PByD0eRHk:-LFrSTNo49yk6FD0iMPt:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate_test.go#L37)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

this is a pretty long single test with lots of little logical tests inside.

do you think you could break this test up with some setup helper functions so that you can have a bunch of little tests?
</blockquote></details>

Done.

---

*[storage/boltdb/client_test.go, line 68 at r1](https://reviewable.io/reviews/storj/storj/95#-LF16Cxw8oapMMq-nsQt:-LFxWsrIEKpkTlMThzb2:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client_test.go#L68)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

same. think we could break these all up into a bunch of little tests? you'd want to share setup and tear down with helper functions across all the tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: 3 of 14 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[storage/common.go, line 23 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2ftC3-Og-Ir0o6XbM:-LFyjcSR6BbwfZIkKP7U:b-896fix) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/common.go#L23)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

you need to update the redis List method as well since it uses this interface
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Reviewed 2 of 13 files at r2.
Review status: 5 of 15 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[internal/test/storage.go, line 99 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyqxq12nGKv9R38g4a:-LFyqFHXCZBKEq0z1Icv:b-d1jqb8) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L99)):*
> ```Go
> 	keySlice := mapIntoSlice(m.Data)
> 
> 	if startingKey == nil {
> ```

starting.Key will never be nil it's zero type is an empty Key

---

*[internal/test/storage.go, line 122 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyrCOJ0C1wMYefS-0l:-LFyrCOKCKPgDIAf5nQD:b-v9pujz) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L122)):*
> ```Go
> 	keySlice := make([]string, len(data))
> 	i := 0
> 	for k := range data {
> ```

nit - this could be `for i, k := range data {`

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: 5 of 15 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[internal/test/storage.go, line 99 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyqxq12nGKv9R38g4a:-LG1-OdC2RK0I9tkuKUw:b1lnsnk) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L99)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

starting.Key will never be nil it's zero type is an empty Key
</blockquote></details>

so should this be `if startingKey == 0` ? or `if startingKey == emptyKey` ..?

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: 5 of 15 files reviewed, 7 unresolved discussions (waiting on @coyle, @jtolds, and @navillasa)

---

*[internal/test/storage.go, line 122 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyrCOJ0C1wMYefS-0l:-LG11Acp9EF1kRrxQJYS:b6dxpya) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L122)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

nit - this could be `for i, k := range data {`
</blockquote></details>

that would make i a string which causes an error

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Review status: 5 of 15 files reviewed, 5 unresolved discussions (waiting on @coyle and @jtolds)

---

*[internal/test/storage.go, line 99 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyqxq12nGKv9R38g4a:-LG14wCLAJ3Edc1KUjp6:b-75xcxr) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L99)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

so should this be `if startingKey == 0` ? or `if startingKey == emptyKey` ..?
</blockquote></details>

ignore me

---

*[internal/test/storage.go, line 122 at r2](https://reviewable.io/reviews/storj/storj/95#-LFyrCOJ0C1wMYefS-0l:-LG166yc-CFNA8zZM218:b3ekrgv) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L122)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

that would make i a string which causes an error
</blockquote></details>

I didn't take the time to see what type `data` was sorry :( ignore me

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Reviewed 10 of 13 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @jtolds)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
:lgtm:

---

Review status: all files reviewed, 5 unresolved discussions (waiting on @jtolds)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95#-:-LG5w8h5EszMshUwBHa_:bnfp4nl)*

**Comment by jtolds** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @navillasa)

---

*[internal/test/storage.go, line 102 at r2](https://reviewable.io/reviews/storj/storj/95#-LG62k147jLD8WfJMh6C:-LG62k147jLD8WfJMh6D:b-e3g2lr) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L102)):*
> ```Go
> 		startingKey = []byte(keySlice[0])
> 	}
> 	started := false
> ```

an easier thing to do might be to just make started = true if startingKey == nil. that way you can have an empty keySlice in some tests

---

*[pkg/netstate/netstate_test.go, line 37 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15l932K0PByD0eRHk:-LG63gST6JY-Mhb1MW4o:b-nl8pz) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate_test.go#L37)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

lol that "Done" encapsulates so much work!!

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LG648O_1BNEK05090zy:b-2niqst) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
<details><summary><i>Previously, navillasa (Natalie Villasana) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

one thing you could do here to reduce code duplication is just decide whether to call cur.First or cur.Seek based on startingKey, then have the rest of the for loop be the same for loop for both codepaths

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by jtolds** [comment]
:lgtm:

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @navillasa)

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95#-:-LG64lzQ3RQ1_UYROkB3:bnfp4nl)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @navillasa)

---

*[internal/test/storage.go, line 102 at r2](https://reviewable.io/reviews/storj/storj/95#-LG62k147jLD8WfJMh6C:-LG65r1N0vFh1p2r99JT:bd2ij19) ([raw file](https://github.com/storj/storj/blob/2990e4f731b442b426d0cc16808e41d32771c20b/internal/test/storage.go#L102)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

an easier thing to do might be to just make started = true if startingKey == nil. that way you can have an empty keySlice in some tests
</blockquote></details>

oh! good idea

---

*[pkg/netstate/netstate_test.go, line 37 at r1](https://reviewable.io/reviews/storj/storj/95#-LF15l932K0PByD0eRHk:-LG65mVKB4JAp3mZDl95:b1zhiii) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/pkg/netstate/netstate_test.go#L37)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

lol that "Done" encapsulates so much work!!
</blockquote></details>

lol I was very excited to click the done button, thanks!

---

*[storage/boltdb/client.go, line 86 at r1](https://reviewable.io/reviews/storj/storj/95#-LF2g3Zu8XiKo2kjkwfb:-LG65i_sCQIBPPFCQzOP:b5zttqa) ([raw file](https://github.com/storj/storj/blob/963896276db0288c62a6450e920639b23cb30850/storage/boltdb/client.go#L86)):*
<details><summary><i>Previously, jtolds (JT Olio) wrote…</i></summary><blockquote>

one thing you could do here to reduce code duplication is just decide whether to call cur.First or cur.Seek based on startingKey, then have the rest of the for loop be the same for loop for both codepaths
</blockquote></details>

oh I was looking for a way to do this, thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by navillasa** [comment]
Review status: all files reviewed, 1 unresolved discussion

---

*[storage/redis/client_test.go, line 58 at r3](https://reviewable.io/reviews/storj/storj/95#-LG6zn_e22seOfPkHWpB:-LG6zn_e22seOfPkHWpC:b9ovzkm) ([raw file](https://github.com/storj/storj/blob/b7ff83833314c873ac22a8e8fb3062684c85e6d1/storage/redis/client_test.go#L58)):*
> ```Go
> 		rt.HandleErr(err, "Failed to list")
> 	}
> }
> ```

the reason for deleting this check is because the code for making this redis test and list function more sturdy should be in a separate PR

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Comment by coyle** [comment]
Reviewed 2 of 3 files at r4, 7 of 7 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/95)*

**Pull request merged**
