### PR TITLE
Remove storj-v2-cli

### PR DESCRIPTION
**Pull request by jtolds**
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/85)

### CODE REVIEW

**Comment by coyle** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jtolds and @kaloyan-raev)

---

*[internal/app/cli/app.go, line 11 at r1](https://reviewable.io/reviews/storj/storj/85#-LEjWpaO9F1ekjvoObVr:-LEjWpaO9F1ekjvoObVs:b-alopr1) ([raw file](https://github.com/storj/storj/blob/4f5986be5cd1ea418b372e1a31f1247f48a3d37f/internal/app/cli/app.go#L11)):*
> ```Go
> 
> 	"github.com/urfave/cli"
> 	client "storj.io/storj/pkg/clientv2"
> ```

nit -- should we use the vgo syntax ? 

client "storj.io/storj/v2/pkg/client"

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/85)*

**Comment by kaloyan-raev** [comment]
@jtolds How about just removing all this code from master? It will still remain in the git history.

**Comment by jtolds** [comment]
i'm okay with that. should i update this pr to do that?

**Comment by kaloyan-raev** [comment]
I can do it.

**Comment by jtolds** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jtolds)

---

*[internal/app/cli/app.go, line 11 at r1](https://reviewable.io/reviews/storj/storj/85#-LEjWpaO9F1ekjvoObVr:-LEjmj_C55F-lpL1BZZp:bjo73ki) ([raw file](https://github.com/storj/storj/blob/4f5986be5cd1ea418b372e1a31f1247f48a3d37f/internal/app/cli/app.go#L11)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

nit -- should we use the vgo syntax ? 

client "storj.io/storj/v2/pkg/client"
</blockquote></details>

We're just going to remove it. That said, the v2 was actually a reference to Storj v2 and not library version v2

---


*Comments from [Reviewable](https://reviewable.io/reviews/storj/storj/85)*

**Pull request merged**
