### PR TITLE
Fix to issue error for empty enc key

### PR DESCRIPTION
**Pull request by aligeti**
What: 
Require an encryption key to be set when the user runs the uplink setup command
https://storjlabs.atlassian.net/browse/V3-1717
Why:
An encryption key is required to be set
Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by ifraixedes** [comment]
@aligeti could you mention why has it been closed?

**Comment by aligeti** [comment]
> @aligeti could you mention why has it been closed?

Got two reviewers approval. and the code is merged. Once it is merged the PR is close and deleted. Am I missing anything?

**Comment by aligeti** [comment]
oops I might have not merged. Let me check

**Comment by ifraixedes** [comment]
It looks not merged to me, but I may be wrong.
I see that you have restored the branch, so you're figuring it out.

**Pull request closed without merging**
