### PR TITLE
Identity V2

### PR DESCRIPTION
**Pull request by bryanchriswhite**
Adds identity version 2.

Thanks for submitting a PR!

## Code Review Checklist (to be filled out by reviewer)
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Could the PR be broken into smaller PRs?
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?

### CODE REVIEW

**Comment by mniewrzal** [comment]
@bryanchriswhite do you plan to continue developing this PR?

**Comment by bryanchriswhite** [comment]
> I'm adding a fake review to stop the spam.

understandable, sorry

**Comment by jenlij** [comment]
Note: We may want to resume this at some point. Keeping in github until transferred to gerrit.

**Comment by jtolds** [comment]
We probably don't want to merge this, given that we do want to merge something more like https://github.com/storj/storj/pull/3271

**Pull request closed without merging**
