### PR TITLE
satellite/repair: new timeout applying to entire repair op

### PR DESCRIPTION
**Pull request by thepaul**
What: 

Add a new timeout applying to the entire repair operation

Why:

There are already config items for Timeout and DownloadTimeout, which
govern long-tail cutoff times for uploading repaired pieces and
downloading pieces for repair, respectively. But we need something
that covers the entire repair operation, including the point in time
where the repair entry is removed from the queue, so we can safely
expect that a repairer will not work on an entry from the queue for
more than this time period.

This still isn't 100% reliable: if the host is under load, the context
timeout goroutine might not be scheduled immediately when the timeout
has elapsed, and it may take an unspecified amount of time for the
canceler to run and for all of the relevant pieces to quit. We allow
45 minutes for that (15 minutes HardRepairTimeout + 45 minutes = 1 hour
time before other repair workers are allowed to pick up an entry on the
repair queue showing a recent attempt time).

We should fix this at some point so that repairs are more safely kept to
a single worker but also returned safely to the queue if that worker
crashes.

Important note: I just found https://review.dev.storj.io/c/storj/storj/+/124 ,
which conflicts with these changes and which does at least some things
better, like setting better values for testplanet. I'll talk to Jeff to see how
amenable he is to moving the repair timeout scope a little higher up so
that it can include the queue fetch step.

Please describe the tests:
 - A test is probably needed still
 
Please describe the performance impact:
- negligible

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by zeebo** [comment]
Oh cool. Yeah, 124 fixes a lot of things necessary to get tests to pass: testplanet needs defaults set explicitly, new config options need to go into yamls, etc. I'm happy with the queue being part of the timeout, and I'd also be happy pulling that into 124, or pulling the necessary bits from 124 into this. Whatever makes people happy.

**Comment by thepaul** [comment]
Ok I'll close out this and propose a change to 124 for the timeout scope change, if that's ok

**Comment by thepaul** [comment]
This won't work as is. Even if we fix the thing where it cancels the goroutine immediately on defer, the timeout will include the time it takes for the Limiter to become active, which is a lot more likely to exceed 15 minutes. We might need to redo the looping logic here in order to get the timeout put in the right place.

**Comment by thepaul** [comment]
Closed in favor of #3645.

**Pull request closed without merging**
