### PR TITLE
pkg/peertls/tlsopts: use min TLS 1.2 for grpc

### PR DESCRIPTION
**Pull request by egonelbre**
What: Use TLS 1.2 as a minimum for GRPC. Go default is TLS 1.0.

Why:

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [x] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by egonelbre** [comment]
I wonder why, the old versions should support 1.2 as well.

**Comment by stefanbenten** [comment]
seems like the negotiation is not working correctly then.

**Comment by zeebo** [comment]
I’m on board with upgrading the minimum version. To my knowledge, this isn’t that big of a deal because you have to ask for the lower version as a client, and I don’t think there are any downgrade attacks. I agree I don’t expect this is backwards incompatible. @stefanbenten how are you determining something is wrong with negotiation?

**Comment by tedder** [comment]
Stefan: do you have logs/errors/panics showing how this breaks older nodes?

**Pull request merged**
