### PR TITLE
storage/filestore: monkit event for delete queuing

### PR DESCRIPTION
**Pull request by thepaul**
What: 

add a monkit event for delete queuing

Why:

so we can know if this ever even happens in real life, and whether we
can just get rid of the queue.

some discussion at http://github.com/storj/storj/pull/3401#discussion_r341195429

Please describe the tests:
 - if this doesn't work, then monkit doesn't work at all
 
Please describe the performance impact:
 - precisely zero, except in the case of a queued delete, in which case it is negligible

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by thepaul** [comment]
Oh! I don't know anything about this lock file. What does it track?

**Comment by VinozzZ** [comment]
> Oh! I don't know anything about this lock file. What does it track?

Yea, I just learned about it too. It's the `monkit.lock` file. I think it's tracking the monkit metric calls

**Comment by thepaul** [comment]
Oh, ok, this looks like Data Science wants to be able to lock some of the metrics so that they won't be moved or changed without them knowing. Nice!

I don't think this will be one of the metrics that they depend on that need the locking, though. I'm only thinking of us in engineering using it for a while to see whether the delete queue is even worth keeping, and then we take it out. Or what do you think?

**Comment by VinozzZ** [comment]
> Oh, ok, this looks like Data Science wants to be able to lock some of the metrics so that they won't be moved or changed without them knowing. Nice!
> 
> I don't think this will be one of the metrics that they depend on that need the locking, though. I'm only thinking of us in engineering using it for a while to see whether the delete queue is even worth keeping, and then we take it out. Or what do you think?

Oh, that sounds fine to me. If this is just temporary, I think we probably don't need to keep track of it

**Comment by thepaul** [comment]
Thank you for letting me know about that list, though. That will be good to know about in the future!

**Pull request merged**
