### PR TITLE
point release v1.89.2

### PR DESCRIPTION
**Pull request by andriikotko**
What: 

Why:
fix for jenkins job to make it clean 
Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by mobyvb** [comment]
@andriikotko can you also include this commit from the UI point release? https://github.com/storj/storj/compare/v1.89.0-rc...v1.89.1-rc-ui

**Comment by andriikotko** [comment]
> @andriikotko can you also include this commit from the UI point release? [v1.89.0-rc...v1.89.1-rc-ui](https://github.com/storj/storj/compare/v1.89.0-rc...v1.89.1-rc-ui)

only this one? https://github.com/storj/storj/commit/ece771f8af04c6d39786397db81ae621ff316ee3
Is it in tag only, not in main?

**Comment by mobyvb** [comment]
> > @andriikotko can you also include this commit from the UI point release? [v1.89.0-rc...v1.89.1-rc-ui](https://github.com/storj/storj/compare/v1.89.0-rc...v1.89.1-rc-ui)
> 
> only this one? [ece771f](https://github.com/storj/storj/commit/ece771f8af04c6d39786397db81ae621ff316ee3) Is it in tag only, not in main? @mobyvb

@andriikotko it is on main: https://github.com/storj/storj/commit/9587e09c78d8d714c4229377b1a7aa7f84186309

**Comment by andriikotko** [comment]
closed because of cla-sign issue
commit from @halkyon will be cherry-picked after adding him to whitelist

**Pull request closed without merging**
