### PR TITLE
satellite/audit: do not report offline to overlay

### PR DESCRIPTION
**Pull request by thepaul**
What: 

Do not report offline-ness to overlay when a node seems to be offline during audit

Why:

It seems this makes nodes overly susceptible to unfair disqualification. Presumably
we'll reenable this once offline detection works more reliably.

Please describe the tests:
 - Test 1: 
 - Test 2:
 
Please describe the performance impact:
- none

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by Fadila82** [comment]
Now that I'm reading the checklist and especially this point:  "Does the new code have enough tests? (every PR should have tests or justification otherwise. Bug-fix PRs especially)"

I wonder...shouldn't there be tests that need to be adapted? (It seems not, as jenkins sees no problem)

**Comment by thepaul** [comment]
@Fadila82 yeah, it seems like we don't currently test that offline nodes _are_ reported to the overlay, so there weren't any tests that needed adjusting. I'm not sure whether this deserves a test since it's only removing functionality and not adding any? But maybe I'm just being lazy and rationalizing. I'll look for a good way to test.

**Comment by Fadila82** [comment]
I was just curious about the existing tests. I agree with you that it's strange to add a test when removing a functionality. Maybe to be sure than no other part of the code reports offliness to the overlay? (I don't know if that's possible)

**Comment by thepaul** [comment]
@ifraixedes I think I'd rather leave those intact; the nodes _were_ offline from the audit system's perspective, and someone trying to debug the auditor later would want to know about them. We just don't want to pass that information on to the overlay at this time.

**Pull request merged**
