### PR TITLE
look at delete object function

### PR DESCRIPTION
**Pull request by kmozurkewich**
Is the correct context being used?  We're currently having to get the child's context to perform the delete:

	scope := bucket.scope.child()

	if err := bucket.DeleteObject(scope.ctx, C.GoString(path)); err != nil {
		*cerr = C.CString(fmt.Sprintf("%+v", err))
		return
	}

What: Is the default context being used the correct context to delete an object from?

Why: Accessing the correct context for object operations

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
@kmozurkewich Thank you for your PR! I think you need to apply your change in this file: https://github.com/storj/storj/blob/master/lib/uplinkc/object.go#L347

**Comment by egonelbre** [comment]
In this case it shouldn't be necessary to create the child context since from the caller side there's no life-cycle to be managed and no place for it to cancel the context.

**Comment by kaloyan-raev** [comment]
@kmozurkewich Could you also complete and sign the CLA: https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform

**Comment by kmozurkewich** [comment]
@kaloyan-raev - thanks!  will update re-submit the PR.

**Comment by kaloyan-raev** [comment]
@kmozurkewich You could have just updated this PR.

**Comment by kmozurkewich** [comment]
@kaloyan-raev updated.  Was getting some odd messages from the CLA bot....

**Comment by kaloyan-raev** [comment]
@kmozurkewich Could you describe what problems or errors do you see when using `delete_object` without the proposed changes?

**Comment by stefanbenten** [comment]
@kmozurkewich I am adding you to the CLA approved list now. This is currently a manual review process. See https://github.com/storj/storj/pull/2720

**Pull request closed without merging**
