### PR TITLE
Fix link to whitepaper in README.md

### PR DESCRIPTION
**Pull request by reefloretto**
###### What
Update README.md to reference the latest PDF whitepaper.

###### Why
The existing link navigates to a 404.

Screen Shot 2021-05-02 at 5 53 10 PM (2)

## Code Review Checklist (to be filled out by reviewer)
 - [x] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation need updating?
 - [x] Do the database access patterns make sense?

### CODE REVIEW

**Comment by reefloretto** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSdVzD5W8rx-J_jLaPuG31nbOzS8yhNIIu4yHvzonji6NeZ4ig/viewform), and we don't seem to have the users @reefloretto on file. Once you have signed the CLA, please let us know, so we can manually review and add you to the approved contributors list.

just signed the CLA 🙏

**Review by stefanbenten — APPROVED** [review]

**Comment by stefanbenten** [comment]
[clabot:check]

**Comment by stefanbenten** [comment]
@cla-bot check

**Review by ifraixedes — APPROVED** [review]

**Comment by ifraixedes** [comment]
@reefloretto thanks for your contributtion.

**Pull request merged**
