### PR TITLE
Mutex/nsclient- WIP

### PR DESCRIPTION
**Pull request by nfarah86**
@coyle

---
This change is [Reviewable](https://reviewable.io/reviews/storj/storj/104)

### CODE REVIEW

**Comment by nfarah86** [comment]
@kaloyan-raev please review the mock test for PUT. Let me know what you think. All the tests are passing. This is a WIP.

**Comment by kaloyan-raev** [comment]
@nfarah86 So far so good! I left a few minor comments.

**Comment by nfarah86** [comment]
___
*[pkg/netstate/netstate_test.go, line 43 at r10](https://reviewable.io/reviews/storj/storj/104#-LH-Szr1DGRcCJCjIfY0:-LH7KCkK3rMO74oxhJme:b-xwuwpv) ([raw file](https://github.com/storj/storj/blob/da5918d354f579b2cdaab2d48d92892b7a117787/pkg/netstate/netstate_test.go#L43)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

The intention for such a test (in the package you copied it from) was to test the constructor (in your case `NewNetstateClient()`) and assert the fields of the returned struct. Which also means you don't need the mock in the previous line.
</blockquote></details>

I'll follow up with you on this, thanks!

**Comment by nfarah86** [comment]
___
*[pkg/netstate/netstate_test.go, line 50 at r10](https://reviewable.io/reviews/storj/storj/104#-LH-STqu2Lg4TUboK02X:-LH7KvMk0rb8dW23MuTg:b-kl8g4z) ([raw file](https://github.com/storj/storj/blob/da5918d354f579b2cdaab2d48d92892b7a117787/pkg/netstate/netstate_test.go#L50)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- there is no need for this to be a public function, right?
</blockquote></details>

good catch

**Comment by nfarah86** [comment]
___
*[pkg/netstate/netstate_test.go, line 102 at r10](https://reviewable.io/reviews/storj/storj/104#-LH-SGlu59lw8QZ3ZEN9:-LH7L2J37I-Fe74ejhtx:b37tcjh) ([raw file](https://github.com/storj/storj/blob/da5918d354f579b2cdaab2d48d92892b7a117787/pkg/netstate/netstate_test.go#L102)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

You don't really need the `InOrder` wrapper if you expect only one method call.
</blockquote></details>

yup! ill fix that, thanks!

**Comment by nfarah86** [comment]
This file should have code that:
a) provides a client interface to PUT, GET, DELETE, LIST
b)Test and mock code that checks client interface
c) modified PATHS to convert string to bytes
d) modified example code to show how to use the client side implementation

**Comment by nfarah86** [comment]
___
*[examples/pointerdb-client/main.go, line 22 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXXrdJ3ZLLQbn1Vsrn:-LHZ1Ne0CStjla1DBdBF:b-vdpn5o) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/examples/pointerdb-client/main.go#L22)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- what was wrong with the `port` var name? We have just one port used in this program, so we don't really benefit from the longer var name.
</blockquote></details>

The port name is a global variable that was having conflict with another port variable. During the merge, I was getting a 'redefining port name' error conflict.  So, I renamed the port.  Turns out when you use flags library, you need to have unique variable names or create a library that takes care of that.  You can prefix the variable names with  package name or something. But  different and distinct names should be used.

**Comment by nfarah86** [comment]
___
*[examples/pointerdb-client/main.go, line 42 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXYDD9A52VLhPdpb3l:-LHZ42BjEg48zbeLaKRv:b4d5lgz) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/examples/pointerdb-client/main.go#L42)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- if you just need to concat two strings, you can do it without formatting like this: `fmt.Sprintln("client dialed port", pointerdbClientPort)`. Note that space will be automatically added between the two params.
</blockquote></details>

thanks for that suggestion. will update repo.

**Comment by nfarah86** [comment]
___
*[pkg/paths/paths.go, line 30 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXYtR14m5xsN6LXxVO:-LHZ4glfBMEpee1oRz3C:bk98c7u) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/paths/paths.go#L30)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

We need a doc comment here, like: `// Bytes serializes the current path to []byte`
</blockquote></details>

will add that to the repo. thanks for the suggestion

**Comment by nfarah86** [comment]
___
*[pkg/paths/paths_test.go, line 77 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXZIJ55kDT6z6jz44m:-LHZ5q1A2yFZoOQAci9L:bs7iist) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/paths/paths_test.go#L77)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- `[]byte{}` is the more expressive notation for an empty []byte than `[]byte("")`.
</blockquote></details>

fixed! thank you.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 53 at r15](https://reviewable.io/reviews/storj/storj/104#-LHY9fR-7SP6a2YuDx_u:-LHZTZ7qBUr4jQlu8TX3:b-hy1v63) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L53)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

All Put, Get, List and Delete methods should have telemetry added, i.e. `defer mon.Task()(&ctx)(&err)` at the beginning of the method.
</blockquote></details>

will add that, thanks!

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 59 at r15](https://reviewable.io/reviews/storj/storj/104#-LHX_K3sEYpmRDmvmWKG:-LHZcMBe8GRBdyCFQhRg:b-pi0tsu) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L59)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- you can replace the about 4 lines with just `return err`.
</blockquote></details>

i see that, thanks~! changes made

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 97 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXaYV-0yj_woJ0R6sz:-LHZcZXZ4QlpHQb_60jI:b-7fxib5) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L97)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- you can replace the about 4 lines with just return err.
</blockquote></details>

yup!!

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/pointerdb_test.go, line 194 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXbwN1E2hF1PmBF5FK:-LHZcrZTA65k6YETyVMc:b-7rhg0c) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/pointerdb_test.go#L194)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

nit -- you can omit the `0` in the slice range, i.e. it's the same as `[:tt.limt]`.
</blockquote></details>

yup!  either way works. I'll delete the 0

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/pointerdb_test.go, line 199 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXcaBXAgXTsaqF0B6z:-LHZdRfp57kAMZt7vJq7:bos6tkj) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/pointerdb_test.go#L199)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

Hmm. Do you really need this line?
</blockquote></details>

nope! i can delete it, that was extra. thanks!

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/pointerdb_test.go, line 199 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXcaBXAgXTsaqF0B6z:-LH_2m53EDpapYi2XquR:b-896fix) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/pointerdb_test.go#L199)):*
<details><summary><i>Previously, nfarah86 (nfarah86) wrote…</i></summary><blockquote>

nope! i can delete it, that was extra. thanks!
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/pointerdb_test.go, line 170 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXdD9eCcJ7F-8pYlA3:-LH_2paN4eYtL457vAa5:bsdxs33) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/pointerdb_test.go#L170)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

It looks like you haven't formatted the code with gofmt. I see this on many places. Please make sure to run all changed files through gofmt. VSCode should do it automatically if you have gofmt installed.
</blockquote></details>

I did~ it's weird.  I ran make and formatted all the files that had issues. I'll do it again. Thanks for the catch

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/pointerdb_test.go, line 170 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXdD9eCcJ7F-8pYlA3:-LH_2yVw9iVh8FJTYg3-:b-896fix) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/pointerdb_test.go#L170)):*
<details><summary><i>Previously, nfarah86 (nfarah86) wrote…</i></summary><blockquote>

I did~ it's weird.  I ran make and formatted all the files that had issues. I'll do it again. Thanks for the catch
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
___
*[examples/pointerdb-client/main.go, line 22 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXXrdJ3ZLLQbn1Vsrn:-LH_3kO29Cy_q9u0eBv9:b26o63b) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/examples/pointerdb-client/main.go#L22)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

Interesting. Maybe it should not be a global var at all.
</blockquote></details>

it's actually from the flags library.  When you use flags, that's what happens

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 43 at r15](https://reviewable.io/reviews/storj/storj/104#-LHX_jvV-KH9tk44AM9b:-LH_3sdwAJoPh5o13fla:b-896fix) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L43)):*
<details><summary><i>Previously, nfarah86 (nfarah86) wrote…</i></summary><blockquote>

you are correct -  I see that. fixed. thanks!
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 53 at r15](https://reviewable.io/reviews/storj/storj/104#-LHY9fR-7SP6a2YuDx_u:-LHZcVx18-vGLT6meTkj:b-896fix) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L53)):*
<details><summary><i>Previously, nfarah86 (nfarah86) wrote…</i></summary><blockquote>

will add that, thanks!
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 44 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXZdlH-aS2J25eZxpl:-LH_45rn39MFu5RMVSKM:b-9295db) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L44)):*
<details><summary><i>Previously, kaloyan-raev (Kaloyan Raev) wrote…</i></summary><blockquote>

@coyle, when we reviewed the TransportClient, you said that it should be used for dialing any node in the network. Should it be used here too, i.e. the PointerDB Client to dial the PointerDB service node?
</blockquote></details>

i'll leave this open and have dennis resolve it.

**Comment by nfarah86** [comment]
fixed pr with @kaloyan-raev suggestions. need another review

**Comment by kaloyan-raev** [comment]
@nfarah86 Great work! I am approving to not block the merge.

But please check with @coyle if the client should dial the service node using the Transport Client. It would be nice if you could figure out why the code is not formatted.

**Comment by nfarah86** [comment]
@kaloyan-raev weird, weird. I ran `make lint` and `make` and no issues came up!!! ill investigate more

**Comment by nfarah86** [comment]
___
*[examples/pointerdb-client/main.go, line 39 at r19](https://reviewable.io/reviews/storj/storj/104#-LHebA365pjGrXSDy1nn:-LHj4vu50tce-wdvqH4B:b-lxfwlt) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/examples/pointerdb-client/main.go#L39)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

you should stop processing if you don't have a client right ?
</blockquote></details>

yup. I will handle that now.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 27 at r19](https://reviewable.io/reviews/storj/storj/104#-LHebYe831Nw3XXgKB4f:-LHj6-xkBCNS9chGy9Um:b-hdak1e) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/pkg/pointerdb/client.go#L27)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I know it seems nitpicky but it would be nice to have all our client interfaces throughout our repo be consistent to ease people learning the codebase and easily contributing.
</blockquote></details>

ok Sure! I'm usually really descriptive with my naming. feel free to call me out to be consistent with everyone else! will make this change.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 27 at r19](https://reviewable.io/reviews/storj/storj/104#-LHebYe831Nw3XXgKB4f:-LHjEPc03wfXU7rq4Djv:b-kevat4) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/pkg/pointerdb/client.go#L27)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Yea, descriptive is great. In this example, Client will be used by other packages by calling `pointerdb.Client`
</blockquote></details>

great! perfect.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 36 at r19](https://reviewable.io/reviews/storj/storj/104#-LHebiUW7o97Iw3Djr1S:-LHjEYUA1dw9zlCDSch1:b9lq8jg) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/pkg/pointerdb/client.go#L36)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

nit - `NewClient`
</blockquote></details>

got it! will resolve. thanks

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 48 at r19](https://reviewable.io/reviews/storj/storj/104#-LHec7RB2blAFkka9p4L:-LHjFSwiAybt6CtdNRDq:by21sxq) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/pkg/pointerdb/client.go#L48)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

I think this is only used internally right? Meaning you want users of pointerdb to only use `NewPointerDBClient`?
</blockquote></details>

correct. NewPointerDBClient is outward facing. I'll make the outward facing func NewClient (what you suggested before) and rename this function

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 48 at r19](https://reviewable.io/reviews/storj/storj/104#-LHec7RB2blAFkka9p4L:-LHjG6Kd8GxQGHxKRcP0:b-896fix) ([raw file](https://github.com/storj/storj/blob/a48b4f9a99d47f4024f9f138f1dfb91ca4b081a7/pkg/pointerdb/client.go#L48)):*
<details><summary><i>Previously, nfarah86 (nfarah86) wrote…</i></summary><blockquote>

correct. NewPointerDBClient is outward facing. I'll make the outward facing func NewClient (what you suggested before) and rename this function
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
___
*[pkg/pointerdb/client.go, line 44 at r15](https://reviewable.io/reviews/storj/storj/104#-LHXZdlH-aS2J25eZxpl:-LHjG8GYD_pifixv0mNg:b-7bua8q) ([raw file](https://github.com/storj/storj/blob/c980bf1b1a3366f4003a3cef7d97baa6129a1210/pkg/pointerdb/client.go#L44)):*
<details><summary><i>Previously, coyle (Dennis Coyle) wrote…</i></summary><blockquote>

Yes, it should use the transport client, but this Pr is already pretty large maybe @nfarah86 create another PR fixing this?
</blockquote></details>

I'll resolve this and add a ticket for upcoming sprints.

**Pull request merged**
